### ISSUE TITLE
listen tcp4 0.0.0.0:53: bind: address already in use

### ISSUE THREAD

**Issue by tdesaules** [docker/for-win#10601]
Hello,

I run a coredns container that map udp/53 from the container to my windows host.
I just upgrade from 3.2.0 to 3.2.1 and I have an error regarding the binding address : 

ERROR: for coredns  Cannot start service coredns: driver failed programming external connectivity on endpoint coredns (cb716dd6cfc4c81b089bd06d31a256653413c10e6403e01f2a34201b06a03c12): Error starting userland proxy: listen tcp4 0.0.0.0:53: bind: address already in use

I use WSL.
Docker Desktop look fine in 3.2.0 and start to fail in 3.2.1.

```
netstat -ano
Connexions actives
Proto  Adresse locale         Adresse distante       État
UDP    0.0.0.0:53             *:*                                    11016
UDP    0.0.0.0:53             *:*                                    11016
```
The PID come from SharedAccess service

look related to that : https://github.com/microsoft/WSL/issues/4818

Thank you

**Comment by stephen-turner** [comment]
Thank you for the ticket. We had one other report of this but the reporter concluded that the bug was in WSL 2 not Docker and filed microsoft/WSL#6646.

**Comment by stephen-turner** [comment]
But if downgrading to an earlier version of Docker fixes it, that would suggest that it's something we've changed.

**Comment by tdesaules** [comment]
Yes, in my case I try a rallback and the udp/53 port was working in docker desktop 3.2.0 with an ubuntu 20.04 wsl backend for it.
I also follow a issue from ms/wsl github that seem related but I think this come from Docker Desktop

**Comment by stephen-turner** [comment]
The only change between 3.2.0 and 3.2.1 was that we took a new version of the engine from upstream. So I'll ask the engine maintainers if they can think of anything.

**Comment by stephen-turner** [comment]
@tdesaules Are you certain that this worked in 3.2.0? We have a suspicion which change is to blame (we changed some of the DNS code) but that would have been between 3.1.0 and 3.2.0.

**Comment by Axel-PJ** [comment]
Hi @stephen-turner , 
I have the exact same problem with the versions that you stated in your last comment (3.1.0 and 3.2.1) and i can reproduce the bug

I run a pihole in docker with WSL2 which used to be fine but after the last update that docker for windows did, I encountered the same problem.

Steps to reproduce:

1. Install Docker for Windows from : https://hub.docker.com/editions/community/docker-ce-desktop-windows/
version 3.1.0

2. Start container with : docker run -d --name pihole -e ServerIP=192.168.1.XXX -e WEBPASSWORD=***** -e TZ=Europe/Paris -e DNS1=127.17.0.1 -e DNS2=1.1.1.1 -e DNS3=1.0.0.1 -p 80:80 -p 53:53/tcp -p 53:53/udp -p 443:443 --restart=unless-stopped pihole/pihole:latest

The containers run fine, and pihole works.

3. Run the update that is proposed by docker for windows. upgrade to -> 3.2.1

4. The container can't restart with the same error message as in the first post ( [...] Error starting userland proxy: listen tcp4 0.0.0.0:53: bind: address already in use)

the diagnostic is the same in the cmd, the ICS service is binded on 53 and can't be stopped or disabled


Best Regards , Axel PJ

**Comment by tdesaules** [comment]
@stephen-turner from my part it is hard to tell.

1) was working docker-version unknow
2) don't work after upgrade in 3.2.1
3) rollback (uninstall then reinstall) from 3.2.1 to 3.2.0 working
4) update in 3.2.1 then not working

I think it's come from the 3.2.1 update but i don't know how is manage docker desktop update (about binding port, reload engine etc...)

**Comment by cbs-clicrdv** [comment]
@stephen-turner from my part I didn't try the rollback to version 3.2.0, to be sure I went back directly to version 3.1.0.

**Comment by tdesaules** [comment]
Well I confirm that the container work fine in 3.1.0 till I don't restart it (update forced)

**Comment by rg9400** [comment]
For me, the issue arose between the update from 3.1.0 to 3.2.0. I noticed the issue instantly after updating to 3.2.0 as my adguard container would not spin up, despite it running prior to the update.

**Comment by pietermsft** [comment]
I'm using docker to run pi-hole which is a DNS server that blocks lots of adds. Earlier today I noticed it was no longer working bringing down my complete network (well, the DNS part). After troubleshooting I noticed that UDP/53 was already used on the host by ICS which is impossible to stop, even after setting the service to disabled and rebooting it's re-enabled and running, probably used by WSL and/or Docker? Not sure what has changed but I would be a big fan of reverting the change. Thanks.

**Comment by drytoastman** [comment]
I accidentally posted in for-mac but I think they are having the same issue.  I can confirm what others are seeing.  3.1.0 worked, automatic update to 3.2.1 and it broke.  Things I discovered (all TCP based for me):

Windows ICS is not the problem.   It was running in both the 3.1.0 and 3.2.1 scenario.   Oddly enough Windows will let you bind other programs at the same TCP IP:port as ICS.  Only the 'last' socket seems to receive the traffic at that point.  Unusual but I don't think its the problem (luckily) because if WSL is running, you cannot stop ICS.

However, if I specify any local interface IPs to bind to, it will still work.  Even the WSL interfaces.  i.e.

-p 127.0.0.1:53:53 -p 192.168.x.y:53:53 -p 172.x.y.z:53:53

will continue to work.  Only when using the wildcard:

-p 53:53  OR  -p 0.0.0.0:53:53

will you get the already in use issue.  I'm not sure what other interfaces the wildcard is seeing that I'm not, I'm guessing something that docker-for-win keeps hidden.

**Comment by tdesaules** [comment]
Well, I rollback in 3.1.0

In my case I'm able to bypass the update because my user is not directly administrator on the computer so I have a popup to enter my credentials and update (popup that I can close and the update doesn't start).

@stephen-turner do you know if the team identify the problem ?

**Comment by stephen-turner** [comment]
Yes, we understand the problem. We're working on it.

**Comment by BootsSiR** [comment]
How do I go to v3.2.0 and stay on it without docker desktop trying to update itself?

**Comment by pietermsft** [comment]
@stephen-turner great news that a solution is being worked on. Let us know if you need folks to test, I'd be happy to.

**Comment by SaleenTheGod** [comment]
@BootsSiR AFAIK you cannot stop Docker Desktop from updating versions. It's actually a huger oversight.

**Comment by BootsSiR** [comment]
@SaleenTheGod this situation right here is enough to justify not having forced updates.  Broken build and users are forced to use it.  I used this as an opportunity to move from Docker Desktop to running Docker inside WSL.  I had systems I rely on not working due to this bug.

**Comment by SaleenTheGod** [comment]
@BootsSiR Totally agree. I hope the developers realize that not being able to disable automatic updates is a disaster waiting to happen. I was able to jank-ily stop it from updating by not allowing the server to get to any docker subdomains.

**Comment by blundercode** [comment]
Same problem here, was my first time downloading docker for windows so I thought something was wrong with my PC I am glad to see others having an issue. Hopefully rolling back versions is not too difficult.

**Comment by maxmengtr** [comment]
Same error as "Error starting userland proxy: listen tcp4 0.0.0.0:53: bind: address already in use."
It happens on 3.2.1 and 3.2.0.
Rolled back to 3.1.0

**Comment by stephen-turner** [comment]
We're planning to have a fix for this early next week. On the automatic updates, see the comment I just posted at https://github.com/docker/roadmap/issues/183#issuecomment-797412882.

**Comment by BootsSiR** [comment]
@stephen-turner that sounds like a great solution 👍

**Comment by wp4nuv** [comment]
For reference, there are more reports of issues with 3.2.1 in other framework which use bind for internal container DNS:
https://github.com/cytopia/devilbox/issues/796

I will reference this issue there for their benefit.

**Comment by fLyRhyTHeMz** [comment]
I can confirm the same issue on Docker Desktop for Mac. Upgraded from 3.1 to 3.2.1, and no longer able to bind port 53 udp or tcp, which has killed my pihole. Running `lsof -nP | grep LISTEN` does not return anything running on 53, and it was working prior to docker upgrade.

**Comment by StefanScherer** [comment]
@tdesaules @maxmengtr @blundercode @pietermsft @drytoastman @Axel-PJ @cbs-clicrdv  While we're preparing a patch release 3.2.2 next week I can share a bugfix installer [Docker Desktop for Windows, build 61849](https://desktop-stage.docker.com/win/stable/amd64/61849/Docker%20Desktop%20Installer.exe) 
It would be great to get early feedback if everything works fine for your use-cases.

**Comment by drytoastman** [comment]
I can confirm that wildcard works now:

```
docker run --rm -p 53:53 alpine ls
docker run --rm -p 0.0.0.0:53:53 alpine ls
```

Binding to localhost and ethernet work as well:

`docker run --rm -p 127.0.0.1:53:53 -p 192.168.x.y:53:53  alpine ls`

Binding to any Hyper-V Virtual Adapters ( "**Default Switch**" and "**WSL**" ) will indicate an error:

`Ports are not available: listen tcp 172.24.176.1:53: can't bind on the specified endpoint.`

That may be correct behavior, not sure.  This is Windows 10 Pro so I believe **Default Switch** is for the normal Hyper-V VMs.

**Comment by Senpai-Ruku** [comment]
I am also experiencing the same problem. Killed off my PiHole install, had to downgrade to 3.1.0

**Comment by Bright625** [comment]
The same problem on 3.2.1, rolled back to 3.2.0, it persisted. Finally when I rolled back to 3.1.0 it worked

**Comment by EC-AU** [comment]
> @tdesaules @maxmengtr @blundercode @pietermsft @drytoastman @Axel-PJ @cbs-clicrdv While we're preparing a patch release 3.2.2 next week I can share a bugfix installer [Docker Desktop for Windows, build 61849](https://desktop-stage.docker.com/win/stable/amd64/61849/Docker%20Desktop%20Installer.exe)
> It would be great to get early feedback if everything works fine for your use-cases.

I have tested the linked build (61849) & confirm it resolves my issue also (Pihole Fails to start after auto-update to 3.2.1) - thanks - I was stuck in a loop of downgrading to 3.1 only to be auto-updated to 3.2.1 multiple times in the past few days.

**Comment by Axel-PJ** [comment]
@StefanScherer Thank you for the updated build, I can confirm that everything works fine now. Great work solving our issues that fast, thanks to the team

**Comment by ralphwillgoss** [comment]
@StefanScherer Thanks for the build, I was having a similar error to others when trying to run pihole:
```
ERROR: for pihole  Cannot start service pihole: driver failed programming external connectivity on endpoint
pihole (d3c0b9ea0348be4cb3dd18f8e77aac290a7ef12e2d2dee604cdfd8c35800b119): 
Error starting userland proxy: listen tcp4 0.0.0.0:53: 
bind: address already in use
```
Edition: Windows 10 Pro
Version: 20H2
OS build: 19042.867

I can confirm the new build 61849 fixes this issue.
Thanks!

**Comment by wp4nuv** [comment]
@StefanScherer , just ran that build against Devilbox 1.9.0 which includes a bind server. All ok!

**Comment by pietermsft** [comment]
> @tdesaules @maxmengtr @blundercode @pietermsft @drytoastman @Axel-PJ @cbs-clicrdv While we're preparing a patch release 3.2.2 next week I can share a bugfix installer [Docker Desktop for Windows, build 61849](https://desktop-stage.docker.com/win/stable/amd64/61849/Docker%20Desktop%20Installer.exe)
> It would be great to get early feedback if everything works fine for your use-cases.

@StefanScherer, I can confirm this fixes the issue. Thank you!

**Comment by Bright625** [comment]
> @tdesaules @maxmengtr @blundercode @pietermsft @drytoastman @Axel-PJ @cbs-clicrdv While we're preparing a patch release 3.2.2 next week I can share a bugfix installer [Docker Desktop for Windows, build 61849](https://desktop-stage.docker.com/win/stable/amd64/61849/Docker%20Desktop%20Installer.exe)
> It would be great to get early feedback if everything works fine for your use-cases.

The bugfix installer fix it, thanks a lot!

**Comment by tdesaules** [comment]
> @tdesaules @maxmengtr @blundercode @pietermsft @drytoastman @Axel-PJ @cbs-clicrdv While we're preparing a patch release 3.2.2 next week I can share a bugfix installer [Docker Desktop for Windows, build 61849](https://desktop-stage.docker.com/win/stable/amd64/61849/Docker%20Desktop%20Installer.exe)
> It would be great to get early feedback if everything works fine for your use-cases.

good to me too :) 
do I close the issue ?

**Comment by stephen-turner** [comment]
We'll close the ticket when the fix is released.

**Comment by stephen-turner** [comment]
Now released in version 3.2.2.

**Comment by crud42** [comment]
@stephen-turner Just to be sure: Does this fix also applies to Socker for Mac/Docker Desktop? Experiencing the same issue `listen tcp4 0.0.0.0:53: bind: address already in use` there.
Best

**Comment by StefanScherer** [comment]
@crud42 Yes this is also fixed for Mac.

**Comment by AkikoOrenji** [comment]
I still have the problem and am running the 'fixed' version 

![image](https://user-images.githubusercontent.com/30274508/113220501-ce4cd180-9272-11eb-8848-33dbded6ce30.png)

![image](https://user-images.githubusercontent.com/30274508/113220616-048a5100-9273-11eb-8b80-4c24d4ef3bf3.png)

![image](https://user-images.githubusercontent.com/30274508/113220667-1c61d500-9273-11eb-8abd-d288b758e021.png)

![image](https://user-images.githubusercontent.com/30274508/113220762-487d5600-9273-11eb-8f37-3b301429b799.png)

**Comment by stephen-turner** [comment]
@AkikoOrenji Your screenshot shows a different error from the one being discussed in this thread?

**Comment by AkikoOrenji** [comment]
Hi Steve, 

Same problem just different outputs i have provided (updated the last image showing the port UDP 53 being open by SharedAccess process (ICS) which is the same issue others were experiencing).

My screens show ICS launched so subsequently I can't launch any UDP 53 listeners on my machine since ICS already has that socket open for no other reason apart from docker.
