### ISSUE TITLE
Docker Desktop Crashing Windows on Startup - AMD Machine

### ISSUE THREAD

**Issue by okakade05** [docker/for-win#10951]
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior
Windows shows blue screen of death when restarted after installing Docker Desktop, only way to get to login is through safe mode.
Uninstalled Docker Desktop after booting through safe mode.

### Expected behavior
Windows should restart normally and docker desktop should be usable on the machine without any issues.

### Information

  - Windows Version: Windows 10 Home Build 19042.928
  - Docker Desktop Version: 3.3.0
  - WSL2 or Hyper-V backend?  WSL1
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No
  - CPU - AMD Ryzen 7 4700U with Radeon Graphics 2.00 GHz
### Steps to reproduce the behavior

  1. Install Docker Desktop for Windows on the machine with the above spec
  2. Accept Restart to complete installation
  3. Machine keeps restarting showing error and crash on startup.

**Comment by piyush-gupta1999** [comment]
Same Thing is happening with me. Only way to get to login in system is through safe mode. Uninstalled Docker Desktop after booting through safe mode.

**Information** 
Windows Version: Windows 10 Home Single Language
Docker Desktop Version: 3.3.0
WSL2 or Hyper-V backend? WSL1
Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No
CPU - AMD Ryzen 5 4600U with Radeon Graphics 2.00 GHz

**Comment by wendelfabianchinsamy** [comment]
+1 this feature is still working well. I wish this could get fixed.

**Comment by vishmanihub** [comment]
Same thing is happening to me with AMD Ryzon 7.0 and Windows Pro. Docker Desktop restart end up in Blue screen. I am booting to Ubuntu in the same machine and the Docker works fine.

Is there a fix available for Docker Desktop 3.0 On Windows 10 for Ryzon 7.0 ?

**Comment by ChristianGChamula** [comment]
Same thing is happening to me with AMD Ryzon 7.0 4800H and Windows Pro. Docker Desktop restart end up in Blue screen.

**Comment by egbakou** [comment]
I have the same issue with AMD Ryzen 5, Windows 10 Pro.

**Comment by EtharAlali** [comment]
Same here. However, it may not be Docker's fault.

The Ryzen systems seem to have an issue with virtualisation more generally. A lot of people are reporting it happening with RealTek PCIe network cards, but I'm yet to be convinced this combo is definitely the culprit. It's always Rayez + BIOS + Virtualisation. Many new BIOS's don't allow you to switch off the network card to find out. It may be worth getting a WiFi dongle to try it for some people.

**Comment by AlexanderSchaetzel** [comment]
Problem is still not solved. Anybody got it fixed meanwhile?
For me the error occures when I've installed the chipset driver.

**Comment by EtharAlali** [comment]
@AlexanderSchaetzel I ended up returning that laptop and got an i7 instead. It's interesting you got this when you installed the chipset driver. It's not something I tried (as it was already installed) but it would make some sense. If you switch virtualisation off from your BIOS to get into Windows and uninstall the chipset drivers, then return to the BIOS to enable virtualisation again, does it work?
