### ISSUE TITLE
Crash while switching from Linux to Windows containers or startup in windows mode

### ISSUE THREAD

**Issue by rkg-a-greensmith** [docker/for-win#12431]
- [X ] I have tried with the latest version of Docker Desktop
  - [ X] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:  D8BDF449-57F3-4057-9506-BF391CFCA7B1/20211209131742

### Actual behavior
Docker Desktop will timeout or crash due to panic.log being readonly when the docker data folder is not in the default install location.

### Expected behavior
Docker desktop should start normally after a machine reboot.

### Information

  - Windows Version: Windows Pro 1909 and 20H2
  - Docker Desktop Version: 4.2.0 and 4.3.0
  - WSL2 or Hyper-V backend?  HyperV
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: Running on standard desktop machines.

### Steps to reproduce the behavior

  1. Install Docker Desktop (4.2.0 or 4.3.0) in Windows desktop machine (1909 or 20H2)
  2. set Docker Desktop to windows container mode
  2. set the docker data root to something non standard e.g.  "data-root": "e:\\dockerdata"
  3. reboot host PC
  4. attempt to run Docker Desktop
  5. Docker will fail to run 100% of the time on all 16 machines I have tested on.

**Comment by thaJeztah** [comment]
I know there is a workaround for this issue in Docker Desktop, but _possibly_ the workaround doesn't account for the non-default storage location.

Docker Engine 20.10.11 should have a fix for this issue (see https://github.com/moby/moby/pull/42987), but this fix would only work when _creating_ the `panic.log` file, so if the file was already created by an older version of the Docker Engine (and if the Docker Desktop workaround didn't apply due to the non-default storage location), then that could explain the problem.

To verify that idea; if you're able to test the upgrade scenario on a machine, does it work if you;

- install Docker Desktop 4.2.0
- manually change permissions of the `panic.log` file (remove the read-only bit); https://github.com/docker/for-win/issues/11899#issuecomment-900084477
- upgrade to Docker Desktop 4.3.0

**Comment by rkg-a-greensmith** [comment]
Hi @thaJeztah,  
your upgrade scenario is what I have been doing in practice since the issue came in on 3.6.0.  
With every update I've been hoping the issue was resolved.  In my setup I run Docker Desktop on TeamCity build agents which reboot every so often and this takes a build agent out for an amount of time until it is noticed.   
When the issue is noticed we manually set the permissions on panic.log and start Docker Desktop, however when the machine next reboots the read-only flag has been set again creating the same issue.
We had serval machines which didn't experience the issue though after the original fix. After some investigating, they were the ones where the data-root was still in the default location.
I know I really should have reported this at the time but I was hoping it was in the works.  When I noticed the update to 4.3.0 still had the issue I assumed I was using a setup that wasn't the norm.

**Comment by thaJeztah** [comment]
Thank you for the additional details!!

So, the temporary (pending the "engine" fix to be released) workaround that was implemented in desktop was to automate that process. Now that the fix is available in an engine release, the problem should no longer occur on "fresh" installs and upgrades from 4.3.0, but there likely will be some transition period.

> When I noticed the update to 4.3.0 still had the issue I assumed I was using a setup that wasn't the norm.

Looks like you were spot-on; it looks indeed that the workaround implemented in Desktop did not take that scenario into account.

Given that there may be some transition period (as mentioned above), we should have a look if we can address this. I have yet to have a look at the code that's used for the workaround, but my "guess" is that that part of the code in the startup sequence may not have the daemon configuration available (and thus, is not aware of the custom data directory), so we'd have to look if we can provide that information in that code path 😅.

**Comment by Hnasar** [comment]
I didn't have any trouble with Docker until I updated to 4.7.1 on 2022-04-29. Now I cannot start Docker in windows container mode. I have my Docker directory on a different drive.

In windows event viewer I see:

```fatal: open D:\Docker\panic.log: Access is denied.```

Removing this file doesn't fix it; ensuring it's read/write doesn't fix it.

**Comment by fschmied** [comment]
(See also https://github.com/docker/for-win/issues/12744.)
