### ISSUE TITLE
Images not visible in docker images tab of Docker Desktop for Windows software

### ISSUE THREAD

**Issue by erjain** [docker/for-win#12693]
Images are not visible in the docker images tab of Docker Desktop for Windows software, but the list shows docker images when I am running the command `docker images` in cli.

**Comment by matthewDDennis** [comment]
I have the same issue

**Comment by StefanScherer** [comment]
You could try the latest 4.8.1 release to see if it's fixed. If you'd like us to investigate further, could you create and upload diagnostics and copy your diagnostic ID, following the steps at https://docs.docker.com/docker-for-win/troubleshoot?

**Comment by CodeMan99** [comment]
@StefanScherer I've been having this issues as well. Diagnostic ID below.

```
40F6398B-AC44-49D9-8DD7-37B6E7A10EFC/20220513151736
```

I'll add that I have this problem a lot on cold starts of my machine. The other tabs seem to also have trouble ☹️

**Comment by sk3p71c** [comment]
I am also having this issue running 4.8.2 (79419). Diagnostic ID is:

    CECFA572-8673-4F9C-898A-1F9D5B763EE6/20220531150640

The issue did not occur immediately. The image list in the GUI has been working fine until today when I removed and rebuilt an image (something I've successfully done many times before). This time, the GUI successfully removed the image but did not show the new image when created. Two other existing images were still shown. The following command in Powershell correctly shows all three images (the new image plus the two pre-existing images):

    docker images

I have tried re-creating the image, which had no effect. I tried restarting Docker; following the restart no images at all are visible. I've also tried doing a `docker system prune`, which also had no effect. Thanks.

**Comment by andrei-z-albu** [comment]
Closing this issue as a fix has been pushed with the new release of Docker Desktop 4.12.0. See [release notes](https://docs.docker.com/desktop/release-notes/) for more details.

**Comment by lizzthabet** [comment]
docker desktop 4.12.0 makes a couple improvements to how the image list is fetched. it should address most cases where the image list is blank in the ui, but the `docker images` cli output is accurate. if you try 4.12.0+ and you're still seeing the issue, please let us know! we can take a look if you [upload diagnostics](https://docs.docker.com/desktop/troubleshoot/overview/).
