### ISSUE TITLE
Can't pull docker images despite being logged in

### ISSUE THREAD

**Issue by mnemyx** [docker/for-win#12715]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: F1DCE808-2C6E-4292-8F27-B23A85176C55/20220510190143

### Actual behavior
After logging in via the Docker Desktop for Windows GUI, I'm not able to pull any docker images either via the GUI or the cmd command

### Expected behavior
After logging in via the Docker Desktop for Windows GUI, I should be able to pull docker images either via the GUI or the cmd command.

### Information

  - Windows Version: Windows 10 Enterprise
  - Docker Desktop Version: 4.8.1 (78998)
  - WSL2 or Hyper-V backend? Hyper-V Backend 
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Output of `& "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check`
```
time="2022-05-10T12:26:57-07:00" level=info msg="unable to query WSL distros: exit status 0xffffffff"
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[SKIP] DD0028: is there available VM disk space?
[PASS] DD0031: does the Docker API work?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0001: is the application running?
[PASS] DD0018: does the host support virtualization?
[PASS] DD0002: does the bootloader have virtualization enabled?
[PASS] DD0020: is the Hyper-V Windows Feature enabled?
[PASS] DD0017: can a VM be started?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0005: is the user in the docker-users group?
[PASS] DD0007: is the backend responding?
[PASS] DD0014: are the backend processes running?
[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[PASS] DD0006: is the Docker Desktop Service responding?
[FAIL] DD0012: is the VM networking working? network checks failed: failed to ping host: exit status 1
[2022-05-10T19:27:04.466529800Z][com.docker.diagnose.exe][I] ipc.NewClient: 7285653c-diagnose-network -> \\.\pipe\dockerDiagnosticd diagnosticsd
[common/pkg/diagkit/gather/diagnose.runIsVMNetworkingOK()
[       common/pkg/diagkit/gather/diagnose/network.go:34 +0xdd
[common/pkg/diagkit/gather/diagnose.(*test).GetResult(0x19af8a0)
[       common/pkg/diagkit/gather/diagnose/test.go:46 +0x43
[common/pkg/diagkit/gather/diagnose.Run.func1(0x19af8a0)
[       common/pkg/diagkit/gather/diagnose/run.go:17 +0x5a
[common/pkg/diagkit/gather/diagnose.walkOnce.func1(0x2?, 0x19af8a0)
[       common/pkg/diagkit/gather/diagnose/run.go:140 +0x77
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x1, 0x19af8a0, 0xc0004df730)
[       common/pkg/diagkit/gather/diagnose/run.go:146 +0x36
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x0, 0xcb00000012?, 0xc0004df730)
[       common/pkg/diagkit/gather/diagnose/run.go:149 +0x73
[common/pkg/diagkit/gather/diagnose.walkOnce(0x137a960?, 0xc00035f890)
[       common/pkg/diagkit/gather/diagnose/run.go:135 +0xcc
[common/pkg/diagkit/gather/diagnose.Run(0x19afea0, 0x1374300?, {0xc00035fb20, 0x1, 0x1})
[       common/pkg/diagkit/gather/diagnose/run.go:16 +0x1cb
[main.checkCmd({0xc0001163b0?, 0xc0001163b0?, 0x4?}, {0x0, 0x0})
[       common/cmd/com.docker.diagnose/main.go:132 +0x105
[main.main()
[       common/cmd/com.docker.diagnose/main.go:98 +0x27f
[2022-05-10T19:27:04.466529800Z][com.docker.diagnose.exe][I] (9aa459d1) 7285653c-diagnose-network C->S diagnosticsd POST /check-network-connectivity: {"ips":["10.161.197.158","172.17.240.1","192.168.1.217"]}
[2022-05-10T19:27:04.990657000Z][com.docker.diagnose.exe][W] (9aa459d1) 7285653c-diagnose-network C<-S 442968ac-diagnosticsd POST /check-network-connectivity (524.1241ms): failed to ping host: exit status 1

[FAIL] DD0032: do Docker networks overlap with host IPs? network bridge has subnet 172.17.0.0/16 which overlaps with host IP 172.17.240.1
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0033: does the host have Internet access?

Please investigate the following 2 issues:

1 : The test: is the VM networking working?
    Failed with: network checks failed: failed to ping host: exit status 1

VM seems to have a network connectivity issue. Please check your host firewall and anti-virus settings in case they are blocking the VM.

2 : The test: do Docker networks overlap with host IPs?
    Failed with: network bridge has subnet 172.17.0.0/16 which overlaps with host IP 172.17.240.1

If the subnet used by a Docker network overlaps with an IP used by the host, then containers
won't be able to contact the overlapping IP addresses.

Please try configuring the IP address range used by networks: in your docker-compose.yml.
See https://docs.docker.com/compose/compose-file/compose-file-v2/#ipv4_address-ipv6_address
```

### Steps to reproduce the behavior

  1. Start Docker Desktop for Windows
  2. Successfully login on browser w/ proxy settings
  3. Click on 'Run' on one of the featured images and get: 
![image](https://user-images.githubusercontent.com/770706/167707410-00fe706c-e33b-43d1-9baf-82c30256df57.png)
  4. Using cmd commands return:
![image](https://user-images.githubusercontent.com/770706/167708042-eb9f3af1-eb65-496f-845f-8f00b382f543.png)
  5. This happens whether I'm on the company's VPN w/ proxy settings AND when I'm on my home's internet with no proxies.

I was previously running Docker Desktop for Windows 3.0.0 version and had no problems. My forte isn't networking so any help would be appreciated if it is something with the subnet settings. Unfortunately, I do not have admin rights to my own work PC, so if it's really a firewall issue, I guess I'm SOL.

**Comment by laurazard** [comment]
Hi @mnemyx, thanks for submitting this issue! In 4.8 we made a change to enable Docker Desktop to read the OS proxy settings and automatically use those, but we also introduced a regression where the manual proxy overrides you can set in the GUI were not being honored. I believe we've fixed the latter issue, could you test [this build](https://desktop-stage.docker.com/win/main/amd64/79160/Docker%20Desktop%20Installer.exe) and experiment with the manual proxy overrides also to see if it fixes your issue?

Thank you!

**Comment by dmduggan** [comment]
The new build fixed this for me.

**Comment by data4n6s** [comment]
Thanks so much. I was having the exact same issue. I couldn't figure out why Docker wasn't using the set proxies. The new build fixed it.

**Comment by mnemyx** [comment]
> Hi @mnemyx, thanks for submitting this issue! In 4.8 we made a change to enable Docker Desktop to read the OS proxy settings and automatically use those, but we also introduced a regression where the manual proxy overrides you can set in the GUI were not being honored. I believe we've fixed the latter issue, could you test [this build](https://desktop-stage.docker.com/win/main/amd64/79160/Docker%20Desktop%20Installer.exe) and experiment with the manual proxy overrides also to see if it fixes your issue?
> 
> Thank you!

Thank you for the response! I tried the 4.9.0 (79160) version, but I still get an error response when trying to pull.

I'm pretty sure the manual proxy overrides do work now because the error response in the first one is when I'm using the manual override proxy while I'm on my work VPN, and the 2nd error is what I get when I don't use the manual proxy overrides when I'm on my home internet:
![image](https://user-images.githubusercontent.com/770706/168157960-e9768719-0608-4506-a936-32c74598891e.png)

Proxies aside, my home internet doesn't use one, so I don't think this was my original problem.

**Comment by koraysaritas** [comment]
I have the same problem. The strange thing is that I can pull images if I switch to Windows containers.

**Comment by mat007** [comment]
Hi, we have just released Docker Desktop 4.8.2 with a fix. Thanks!

**Comment by mnemyx** [comment]
You guys really did fix this, thank you!! It took me this long to test it, but it worked.
