### ISSUE TITLE
Docker failed to start on Windows 10 with Bitlocker policy

### ISSUE THREAD

**Issue by saicrazyfire** [docker/for-win#1297]
### Expected behavior

Docker to start properly with no warnings/errors.

### Actual behavior

Warning dialog pops up with the text:

![image](https://user-images.githubusercontent.com/1043534/32516147-53cc5c56-c3d0-11e7-8dbd-a90bf0b34a26.png)

After clicking OK, the docker system icon is red. Running any docker terminal command results in an error

```
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.34/containers/json: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.
```

### Information

![image](https://user-images.githubusercontent.com/1043534/32516166-6d27ed46-c3d0-11e7-9238-8e7d1b494eaf.png)

Docker Version:
------------------------
Docker Community Edition
Version 17.11.0-ce-rc2-win37 (13978)
Channel: edge
19d223a

A diagnostic was uploaded with id: E50AD702-ACC9-4E66-A5D4-19FAD4BE3B88/2017-11-07_15-29-52

Windows Version:
------------------------
Windows 10 Enterprise (CBB branch, not LTSB)
Domain-joined Work computer with Bitlocker encryption. Unlikely to disable the Bitlocker "Deny write access to fixed drives not protected by Bitlocker" policy.

### Steps to reproduce the behavior

  1. Install Docker CE - Edge channel
  2. Launch Docker CE

**Comment by friism** [comment]
I think error message states what's the solution:

> Please disable it and retry the operation

If that's not an option, consider trying Docker Toolbox or other ways to run Docker: https://docs.docker.com/toolbox/toolbox_install_windows/

**Comment by saicrazyfire** [comment]
Sure, I don't think I can disable the policy so I'll try the Toolbox.

**Comment by abarke** [comment]
I have the same issue. I cant disable it as it is a company policy. There should be another solution to this issue.

**Comment by adailsonfilho** [comment]
@saicrazyfire , as far as I understand, my hypothesis is: Docker for windows run upon Hyper-V and access the host driver directly. When bitlocker is used it's not possible to read data right from the disk, we need to read through the Operational System itself, cause it's encrypted. Docker toolbox uses a VM of virtualbox as host, that by default, does not use bitlocker, so the data in its virtual drive its available right away.

**Comment by alexverboon** [comment]
There seems to be a fix for Windows Server as mentioned here: https://blogs.technet.microsoft.com/virtualization/2018/01/22/a-smaller-windows-server-core-container-with-better-application-compatibility/

We fixed this issue reported on GitHub and User Voice related to BitLocker and FDVDenyWriteAccess policy: Users were not able to run basic Docker commands like Docker Pull.
https://github.com/Microsoft/Virtualization-Documentation/issues/530
https://github.com/Microsoft/Virtualization-Documentation/issues/355
https://windowsserver.uservoice.com/forums/304624-containers/suggestions/18544312-fix-docker-load-pull-build-issue-when-bitlocker-is

so hopefully Microsoft will also address this for Windows 10.

**Comment by allanbarklie** [comment]
I'm seeing this same issue with:
Windows 10 Pro Version 10.0.17134 Build 17134 
Docker for Windows Version 18.06.0-ce-win72 (19098) Channel: stable 5513f91

From my reading there are 2 parts:
1) make windows and docker work well together in the presence of bitlocker
2) remove the the docker check that stops you from using windows container if the bitlocker flag is set

The links above show that Microsoft have made changes to address (1)

It's not clear to me at the moment when these will be in a non insider build of Windows 10 Pro and also if the Docker team have a plan to disable the check once this is the case.

Does anyone have more up to date information on this?

**Comment by mocroft** [comment]
Hey,
we are currently evaluating the use of docker in our company and encountered the same problem. We are forced however to use Bitlocker. Is there already a solution coming up for this problem?

**Comment by christianacca** [comment]
I still get this problem on Win 10 machines. According to the comment above, it should be fixed on Win server 1803.

In theory this Win 10 should get fixed once 1809 is released as it seems that the Win 10 and Win server 2019 share the same kernel.

In the meantime, whilst working in dev on win 10, I have found the registry setting update below get's around the problem (use at your own caution - I copied it from someone else when researching the same problem)

```
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Policies\Microsoft\FVE]
"FDVDenyWriteAccess"=dword:00000000
```

**Comment by mgonzales3** [comment]
Using winver win10 build 1809 with docker ce v18.03.1 (17513) and still receive this message.

**Comment by bennyvanlyssebettens** [comment]
![image](https://user-images.githubusercontent.com/38490754/53803160-25710280-3f44-11e9-89ea-1abcfb35bc05.png)
 
Problem NOT solved

**Comment by Poltergeisen** [comment]
Any updates on this? Still getting this error on Version	10.0.17134 Build 17134

**Comment by DC-Erok** [comment]
I have the same issue when trying to use windows or linux containers on windows 10 Enterprise. Corporate policy has bitlocker enabled. I can't turn it off... Are there any new estimates when a fix might occur?

**Comment by mikenri** [comment]
I have this same issue, running Windows 10 Enterprise 1809.
I can run Linux containers but can't switch to Windows. 

Bitlocker is required on fixed drives by corporate policy, it's a security requirement and can't be disabled.

**Comment by RupenAnjaria** [comment]
Same issue, if I disable then I get the message that please enable it.

**Comment by weberjon** [comment]
No idea how permanent this will be, but anyone watching, @christianacca fix did just work for me. I'm running Win10 x64 1809.4. After changing "[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Policies\Microsoft\FVE]" "FDVDenyWriteAccess" to a "0" Docker worked. Didn't need to restart the PC.

**Comment by goodisontoffee** [comment]
This is also an issue for me.
Win10 Enterprise v1903 OS build 18362.535
Docker Desktop Community 2.1.0.5 (40693) stable channel

**Comment by AndreM0211** [comment]
Just follow the registry edit stated before:  "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Policies\Microsoft\FVE]" "FDVDenyWriteAccess" set to a "0". 

It will work.

**Comment by mikenri** [comment]
The registry edit is not a real solution for secure environments that need to enforce fixed disk encryption by Bitlocker.  

If that is enforced by group policy, the next time group policy refreshes docker desktop will fail to start again.

**Comment by predatorian3** [comment]
So, something I and a collague did was install Docker Desktop 2.0.0 and then upgrade to Docker Desktop 2.2.0.3. That worked for us currently.

**Comment by StefanScherer** [comment]
A heads-up for those who run into this problem. We've done a fix for Windows Containers + BitLocker in DD and we plan to ship this in DD 4.18.
