### ISSUE TITLE
A timeout occured while waiting for a WSL integration agent to become ready. -- SOLUTION

### ISSUE THREAD

**Issue by LeviPesin** [docker/for-win#13426]
Solution for:
https://github.com/docker/for-win/issues/13357
https://github.com/docker/for-win/issues/13395
https://github.com/docker/for-win/issues/13409
https://github.com/docker/for-win/issues/13413
https://github.com/docker/for-win/issues/13414
https://github.com/docker/for-win/issues/13425

Based on https://github.com/docker/for-win/issues/13357#issuecomment-1515724479 and https://github.com/docker/for-win/issues/13357#issuecomment-1519701644.

Solution:
- Run `wsl --shutdown`,
- Open the settings file (`C:\Users\USERNAME\AppData\Roaming\Docker\settings.json`) and set there `"integratedWslDistros": []` and `"enableIntegrationWithDefaultWslDistro": false`,
- Docker Desktop should start properly.

If you need the WSL integration to continue to work, after these steps open Docker Desktop GUI's settings, go to `Resources -- WSL integration`, re-enable integration, and press "Apply & restart" button (please wait a bit for it to go gray). Note that if you'll stop Docker Desktop you will be required to perform all the steps from the very beginning again.

**Comment by Mnish55** [comment]
Thank you, Problem solved

**Comment by ashmalvayani** [comment]
I am currently logged in as an administrator, and I am having trouble finding the Docker folder inside AppData. (first image)
![image](https://user-images.githubusercontent.com/56957881/234133263-c89d2561-599c-4b9f-b0f7-3fd44be96161.png)

I've another defaultuser but have only a "Local" folder inside the app data and no "Roaming" folder here. What could be the issue here?
![image](https://user-images.githubusercontent.com/56957881/234133316-3a7f0596-3ea6-44b6-9fbc-920db875c687.png)

**Comment by YouveGotMeowxy** [comment]
lmao. So now they broke WSL integration too? First they broke networking, now wsl integration Did they fire all their original devs and hire the 3 Stooges?

**Comment by LeviPesin** [comment]
> I've another defaultuser but have only a "Local" folder inside the app data and no "Roaming" folder here. What could be the issue here?

I don't think you could log in as "Default" or "Public". Are you sure you aren't logging in as "Hp" or "defaultuser100000"?

**Comment by 4nandP** [comment]
Works but then as soon as I re-enable integration it kills it again. I don't consider this a solution, it's more of a hacky workaround

**Comment by LeviPesin** [comment]
Obviously yes, it's a workaround, but at least it works... Obviously the developers should fix it more properly.

**Comment by Marshal27** [comment]
+1 on the workaround @LeviPesin provided, as it has solved my problem.

One important detail for me was, when clicking the `Apply & Restart` button, it acts like it isn't doing anything, but it is... let it sit there until it goes gray on it's own... if you rage click to click the button again it will immediately go gray, but, I think this may interrupt the integration setup and it will not work properly.

Once I followed the workaround provided by @LeviPesin and patiently waited for the button to go gray on it's own, I now have  DD 4.19 running with WSL 2 Ubuntu distro and my VS Code Docker extension is showing all images and containers like it should.

**Comment by LeviPesin** [comment]
> One important detail for me was, when clicking the Apply & Restart button, it acts like it isn't doing anything, but it is... let it sit there until it goes gray on it's own... if you rage click the button again it will immediately go gray, but, I suspect this may interrupt the integration setup and it will not work properly.

Added this to the solution.

**Comment by LeviPesin** [comment]
Seems like this (waiting for the DD to restart) takes much longer time in 4.19 than in 4.18... Another regression maybe?

**Comment by stephdotnet** [comment]
Thanks, it worked 🥳

**Comment by Kennedylelei** [comment]
Thank you so much...this really works

**Comment by niraj2998** [comment]
It worked !!! Thank you so much.

**Comment by barhun** [comment]
The bug related to this issue seems to have been fixed with the release v4.20.0. I haven't encountered any errors since I re-enabled integration with the default WSL distro after the upgrade.

**Comment by Marshal27** [comment]
> The bug related to this issue seems to have been fixed with the release v4.20.0. I haven't encountered any errors since I re-enabled integration with the default WSL distro after the upgrade.

I cannot confirm this on my end. 

I upgraded to v4.20.0 this morning, enabled WSL integration to my default WSL instance, rebooted my machine and currently stuck on the "Starting the Docker Engine" spinner... Will do some more testing/reboots to make sure... but so far... this issue is still present for me in the v4.20.0 release.

**Comment by MrJanuszJasinski** [comment]
Still present for me also

**Comment by barhun** [comment]
> > The bug related to this issue seems to have been fixed with the release v4.20.0. I haven't encountered any errors since I re-enabled integration with the default WSL distro after the upgrade.
> 
> I cannot confirm this on my end.
> 
> I upgraded to v4.20.0 this morning, enabled WSL integration to my default WSL instance, rebooted my machine and currently stuck on the "Starting the Docker Engine" spinner... Will do some more testing/reboots to make sure... but so far... this issue is still present for me in the v4.20.0 release.

I'd also upgraded WSL to the latest version before that and you may need to do the same. What is the output to the command `wsl --version`? Mine is as follows:

```
WSL version: 1.2.5.0
Kernel version: 5.15.90.1
WSLg version: 1.0.51
MSRDC version: 1.2.3770
Direct3D version: 1.608.2-61064218
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22000.2057
```

**Comment by Marshal27** [comment]
> > > The bug related to this issue seems to have been fixed with the release v4.20.0. I haven't encountered any errors since I re-enabled integration with the default WSL distro after the upgrade.
> > 
> > 
> > I cannot confirm this on my end.
> > I upgraded to v4.20.0 this morning, enabled WSL integration to my default WSL instance, rebooted my machine and currently stuck on the "Starting the Docker Engine" spinner... Will do some more testing/reboots to make sure... but so far... this issue is still present for me in the v4.20.0 release.
> 
> I'd also upgraded WSL to the latest version before that and you may need to do the same. What is the output to the command `wsl --version`? Mine is as follows:
> 
> ```
> WSL version: 1.2.5.0
> Kernel version: 5.15.90.1
> WSLg version: 1.0.51
> MSRDC version: 1.2.3770
> Direct3D version: 1.608.2-61064218
> DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
> Windows version: 10.0.22000.2057
> ```

This is not a factor for me as I am using the same version.

```
WSL version: 1.2.5.0
Kernel version: 5.15.90.1
WSLg version: 1.0.51
MSRDC version: 1.2.3770
Direct3D version: 1.608.2-61064218
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22621.1555
```

**Comment by LeviPesin** [comment]
It seems this issue doesn't occur anymore in 4.21.1?

**Comment by Marshal27** [comment]
> It seems this issue doesn't occur anymore in 4.21.1?

confirmed on my system... happy to see this functionality finally restored.

**Comment by charger89** [comment]
> after these steps open Docker Desktop GUI's settings

Yet it's still stuck at this step
![image](https://github.com/docker/for-win/assets/66736719/4eefd872-7913-43aa-9eae-e976d5fcbd25)

God I love Windows.

**Comment by barhun** [comment]
Having upgraded to the version `4.24.0`, I am occasionally experiencing similar issues again; but not everytime, about only once for every three trials. It says, in the release notes, that they've fixed a bug that caused DD to fail to start on Windows hosts; maybe those changes had some side-effects? I was enjoying a seamless experience with the version 4.23.0, having start and quit times so tiny that I couldn't believe at first. Anyone else with these problems?
