### ISSUE TITLE
vpnkit does not always start with Docker

### ISSUE THREAD

**Issue by andrewdedesko** [docker/for-win#1741]
### Expected behavior
When Docker for Windows starts, vpnkit should also start.

### Actual behavior
Sometimes Docker for Windows starts, but vpnkit does not, and so services are not available through `localhost` port forwarding.  Services are available at the Moby linux host's ip address (interface `hvint0`).  For example, from my Windows host I can reach Couchbase at `http://10.0.75.2:8091` but not `http://localhost:8091`.

vpnkit seems to consistently fail to start when cold booting the physical host.  When rebooting the physical Windows host, vpnkit sometimes comes up (most of the time I think).  When restarting only Docker, vpnkit seems to always start.  My current workaround is to restart Docker from the Settings dialog.  At least one of my co-workers is also able to reproduce this.  We haven't tried on other computers.

### Information

  - Windows
    - Edition: `Windows 10 Enterprise`
    - Version: `1709`
    - OS Build: `16299.248`

  - Docker
    - Version: `17.12.0-ce-win47 (15139)`
    - Channel: `stable`
    - `9c692cd` (build number?  not sure what this is)

  - Hypervisor: `Hyper-V`
    - `vmms.exe` product version: `10.0.16299.192`

  - Diagnostics
    - While `vpnkit` **is not** running: `81D46013-DB01-480F-BBFB-C00D3EAB9FEE/2018-02-22_09-14-31`
    - While `vpnkit` **is** running: `81D46013-DB01-480F-BBFB-C00D3EAB9FEE/2018-02-22_11-55-20`

  Today I cannot find anything in Docker's logs about vpnkit other than what looks like info from uploading the diagnostic (e.g. "Sending DownloadVpnKitLogs(C:\Users\adedesko\AppData\Local\Temp\kjfjexlp.isu\pcap.tar)...").  `pcap.tar` is 0 bytes (when vpnkit was not running).

### Steps to reproduce the behavior

  1. Cold boot physical host (start from off; NOT a reboot; rebooting does not always seem to trigger this issue)
  2. Login to Windows
  3. Wait for the desktop notification informing you that Docker has started
  4. Docker will now be up, but `vpnkit` will not
    - Verify `vpnkit` is not running in *Task Manager*
    - Verify I cannot reach services through `localhost` (I just nagivate to `http://localhost:8091` in Firefox: I get the *Unable to connect* page)
    - Verify I can reach the services through the node's `ingress` ip address (e.g. `http://10.0.75.2:8091`)
  5. Restart Docker: right click Whale icon in task tray > *Settings...* > Select *Reset* > *Restart Docker*
  6. Wait for Docker to restart
  7. Verify `vpnkit` is running and services are available through `localhost`
    - Verify `vpnkit` is running (*Task Manager*)
    - Verify I can reach services through `localhost` (e.g. `http://localhost:8091`)

#### Add dependency on vmcompute
Wondering if this might be a race condition between Docker and Hyper-V, configured `com.docker.service` to depend on `vmcompute`.  Shut down, booted, logged in, no joy: vpnkit did not start.  Removed service dependency.

#### Change com.docker.service to Automatic Delayed Start
Again, wondering if Docker needed more time for other services to start, tried changing `com.docker.service` from `Automatic` to `Automatic (Delayed Start)` Startup Type.  Shut down, booted, logged in: vpnkit did not start.

**Comment by falco467** [comment]
I can even reproduce the issue fairly regularly as follows:
-> Disable Docker autostart with Windows
-> cold boot windows pc
-> start docker
-> vpn-kit fails to start ~70% of the time

**Comment by andrewdutton** [comment]
Looks like it's related to fast startup - disabling it (Power Options -> "choose what the power buttons do" -> Uncheck "Turn on fast startup" ) is a workaround.

digging into the issue, looks like the docker service has a powershell wmi query to detect boot mode - this query tends to fail b/c of the way it's written (class is Docker.Backend.BootHelper) - it can be handled better with something like:

`(Get-WinEvent -FilterHashtable @{ProviderName="Microsoft-Windows-Kernel-boot";  ID=27} | Select-Object -First 1).Message`

**Comment by andrewdedesko** [comment]
Since disabling fast startup `vpnkit` starts as expected at boot.

**Comment by prisar** [comment]
I am getting this same error. I restarted the WMI and reinstalled docker for windows. Now it says 
`docker is running`

**Comment by falco467** [comment]
Network is simply not working after initial start of Docker, I have to right-click -> Restart Docker... every time to get Network running

**Comment by andrewdedesko** [comment]
@falco467 have you tried disabling `fast startup`?

**Comment by falco467** [comment]
@andrewdedesko Disabling Fast Startup in Windows does not solve the problem, after rebooting and starting Docker the network is not available. I still have to manually restart Docker from the Systray-Menu to get Networks running...

**Comment by piers7** [comment]
Release notes for 18.06.0-ce-win70 claim this is fixed ... and link back to this issue. Should this not be marked as closed or something?

**Comment by MAliNaqvi** [comment]
@piers7 I have confirmed that this issue has not been fixed. This problem can be replicated by a user logout and login:

Before logout:
```
PS C:\Program Files\Docker\Docker\resources> Get-Process "*vpnkit*"

Handles  NPM(K)    PM(K)      WS(K)     CPU(s)     Id  SI ProcessName
-------  ------    -----      -----     ------     --  -- -----------
    272     106    20344      12532       0.09  20432   7 vpnkit
```
After user logout and login (and once Docker for Windows is ready):

```
PS C:\Program Files\Docker\Docker\resources> Get-Process "*vpnkit*"
PS C:\Program Files\Docker\Docker\resources>
```

I even tried to run vpnkit.exe manually (obtained the command using the procexp64.exe)

```
"vpnkit.exe" --ethernet hyperv-connect://3af325d9-63f7-4b4d-a335-11a222e53f29
             --port //./pipe/dockerVpnKitControl
             --port hyperv-connect://3af325d9-63f7-4b4d-a335-11a222e53f29
             --dns "C:\Users\alnaca\AppData\Roaming\Docker\resolv.conf"
             --dhcp "C:\Users\alnaca\AppData\Roaming\Docker\dhcp.json"
             --diagnostics \\.\pipe\dockerVpnKitDiagnostics
             --host-names host.docker.internal,docker.for.win.host.internal,docker.for.win.localhost
             --gateway-names gateway.docker.internal,docker.for.win.gateway.internal,docker.for.win.http.internal
             --listen-backlog 32
```

While the vpnkit turns on successfully, the connection to containers via `localhost` is still down.

This problem persists both on Windows 10 and Windows server 2016.

Here is my docker version: Version 18.06.0-ce-win70 (19075)

**Comment by MAliNaqvi** [comment]
Another way to replicate the issue is just to kill the vpnkit.exe process. `localhost` can't be used even after vpnkit.exe is restarted, to connect to the various services.

**Comment by KishoreNamala** [comment]
I still get this issue even with the latest release - 2.1.0.1 (37199)
