### ISSUE TITLE
Trouble switching to Windows Containers when Bitlocker Policy is enabled. 

### ISSUE THREAD

**Issue by alexverboon** [docker/for-win#1798]
### Actual behavior
We have Docker for Windows Version 17.12.0-ce-win47 (15139) installed on Windows 10 Enterprise 1709. We also have Bitlocker enabled and the following policy set:

HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Policies\Microsoft\FVE
FDVDenyWriteAccess = 1

When switching to Windows containers , Docker displays the following message 

![image](https://user-images.githubusercontent.com/6444073/37079026-7005c1c2-21e1-11e8-87f3-b68beed9417f.png)

At present , the only workaround is to temporarely disable the policy, but that can only be done if you're an administrator. 

This blog post, seems to indicate that the very same issue has been resolved on Windows Server 2016 1709, https://blogs.technet.microsoft.com/virtualization/2018/01/22/a-smaller-windows-server-core-container-with-better-application-compatibility/

_We fixed this issue reported on GitHub and User Voice related to BitLocker and FDVDenyWriteAccess policy: Users were not able to run basic Docker commands like Docker Pull._

Are there any plans for solving this issue on the Windows 10 Client as well? Knowing that the Docker and Microsoft teams work together closely, I hope there is going to be a solution for this, as otherwise using Docker for Windows in an Enterprise environment with no local admin privileges makes using Docker for Windows impossible. 

### Expected behavior
Allow switching to Windows containers when Bitlocker is enabled. 

### Information
 Docker for Windows Version 17.12.0-ce-win47 (15139) installed on Windows 10 Enterprise 1709.
  I was unable to find any trace of this in the log files. 

### Steps to reproduce the behavior

 1. Install Windows 10 Enterprise 1709
 2. Enable Hyper-V and Container Features

`
### Enable Hyper-V Features
Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Hyper-V-All
### Enable Container Features
Enable-WindowsOptionalFeature -Online -FeatureName Containers
`

 3. Enable Bitlocker
 4. Enable Bitlocker policy manuall or via [GPO](https://getadmx.com/?Category=Windows_10_2016&Policy=Microsoft.Policies.VolumeEncryption::FDVDenyWriteAccess_Name). 
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Policies\Microsoft\FVE
FDVDenyWriteAccess = 1

5. Install Docker 17.12.0-ce-win47 (15139) 
6. Switch to Windows Containers.

**Comment by jasonbivins** [comment]
Hi @alexverboon 
This thread indicates that the issue is fixed in the newest insider preview (17074)

https://github.com/MicrosoftDocs/Virtualization-Documentation/issues/530

**Comment by alexverboon** [comment]
Hi @jasonbivins , thanks for the reply, let me test this, and I'll share the findings.

**Comment by LucasVerberne** [comment]
Hi,

When I start up my docker it seems to work fine. But when I select option 'Switch to Windows containers' I get the message: "_Current operation failed because Windows policy "Deny write access 
to fixed drives not protected by Bitlocker" is enabled. 
Please disable it and retry the operation_"

Now it happens that I have admin rights on my computer, so I disabled the policy in the group policy editor and restarted my computer. When I select the option again it still returns with the same error message. So far I didnt found any suggestions on whats happening or how to fix it :/

Any ideas? :)

Regards

**Comment by tjgalama** [comment]
looks like a duplicate of #1297 ?

**Comment by archeedev** [comment]
November 2019, Docker 19.03.4, Windows 10 1809 - this is still an issue
