### ISSUE TITLE
High cpu load associated with Docker.service after 18.03.0-ce upgrade 

### ISSUE THREAD

**Issue by bmweller** [docker/for-win#1900]
Please, check https://docs.docker.com/docker-for-win/troubleshoot/.
Issues without logs and details cannot be debugged, and will be closed.

  - [ x ] I have tried with the latest version of my channel (Stable or Edge)
  - [ x ] I have submitted Diagnostics
  - [ x ] I have included the Diagnostics ID in this Issue
  - Windows Version: Windows 10 Pro version 1709
  - Docker for Windows Version: Version 18.03.0-ce-win59 (16762) Channel: stable d70d80d

### Expected behavior
Minimal cpu (<2%) load associated with Docker.service 

### Actual behavior
High cpu (20% of 4 core system) load associated with Docker.service and 10GB memory use on 64GB system

### Information
  - Diagnostic ID 2FC0055D-C745-4E89-8721-BA2C6804ECA5/2018-03-30_09-37-40

### Steps to reproduce the behavior

  1. Start docker
  2. no running containers

**Comment by bmweller** [comment]
same behavior seen after performing a docker reset to factory defaults

**Comment by rn** [comment]
@djs55 the logs are full of:
```
[22:14:26.134][VpnKit         ][Info   ] vpnkit.exe: IP.output: could not determine link-layer address for local network (0.0.0.0/0) ip 10.0.75.1
[22:14:26.134][VpnKit         ][Warning] vpnkit.exe: Could not find 10.0.75.1 on the local network
[22:14:26.134][VpnKit         ][Warning] vpnkit.exe: Error sending TCP packet via IP: no route to destination: no response for IP on local network
[22:14:26.134][VpnKit         ][Warning] vpnkit.exe: ARP table has no entry for 10.0.75.1
[22:14:26.134][VpnKit         ][Info   ] vpnkit.exe: IP.output: could not determine link-layer address for local network (0.0.0.0/0) ip 10.0.75.1
[22:14:26.134][VpnKit         ][Warning] vpnkit.exe: Could not find 10.0.75.1 on the local network
[22:14:26.134][VpnKit         ][Warning] vpnkit.exe: Error sending TCP packet via IP: no route to destination: no response for IP on local network
[22:14:26.135][VpnKit         ][Warning] vpnkit.exe: ARP table has no entry for 10.0.75.1
[22:14:26.135][VpnKit         ][Info   ] vpnkit.exe: IP.output: could not determine link-layer address for local network (0.0.0.0/0) ip 10.0.75.1
[22:14:26.135][VpnKit         ][Warning] vpnkit.exe: Could not find 10.0.75.1 on the local network
```
several a second. I could image this causing a high CPU load. Any idea where this comes from?

**Comment by hasonhai** [comment]
Anyone know how to detect with container causing high load? I enable kubernetes cluster, then the load is quite high. I reset kubernetes, blue screen of death. I also cannot deactivate kubernetes.

**Comment by Stradivario** [comment]
Same thing here on 18.03 and Ubuntu 18.04

**Comment by hasonhai** [comment]
In my case, because the hyperV VM for docker-for-win is set with too little memory (2GBs) so it hanged Kubernetes. After increase the memory for the VM in the setting of Docker, everything run smoothly.

**Comment by Stradivario** [comment]
In my case i found out that pm2@2.10.3 is causing this behavior and my app starts eith 1 minute delay and 100% cpu usage so i reverted to pm2@2.10.2

**Comment by farin99** [comment]
same issue with docker v18.02.0-ce and pm2@2.10.3. Thanks @Stradivario

**Comment by Kugelschieber** [comment]
Same issue with docker 18.03.1-ce-win65 (17513).
![unbenannt](https://user-images.githubusercontent.com/6115423/40046694-e202b938-582d-11e8-9cb3-d9111efc18b2.PNG)
Is this ever going to be fixed? Having it for month.

**Comment by hecaidi** [comment]
Same issue for me with docker 18.03.1-ce-win65 (17513).
The behaviour seems random to me.
Sometimes com.docker.service just consumes a bit of RAM, sometimes it cannot stop increasing the consumption.
Sometimes there are container running, sometimes there aren't any.

I usually solve the problem by restarting the computer. Sometimes it helps, sometimes it does not.
It happens to me since I've started to use an image containing docker out of docker + ansible.
But I can happen even if there is not any container in execution.

Logs is plenty of 
[15:47:17.503][VpnKit         ][Info   ] vpnkit.exe: IP.output: could not determine link-layer address for local network (0.0.0.0/0) ip 10.0.75.1  
[15:47:17.503][VpnKit         ][Warning] vpnkit.exe: Could not find 10.0.75.1 on the local network                                                 
[15:47:17.503][VpnKit         ][Warning] vpnkit.exe: Error sending TCP packet via IP: no route to destination: no response for IP on local network 
[15:47:17.503][VpnKit         ][Warning] vpnkit.exe: ARP table has no entry for 10.0.75.1                                                          
[15:47:17.503][VpnKit         ][Info   ] vpnkit.exe: IP.output: could not determine link-layer address for local network (0.0.0.0/0) ip 10.0.75.1  
[15:47:17.503][VpnKit         ][Warning] vpnkit.exe: Could not find 10.0.75.1 on the local network                                                 
[15:47:17.503][VpnKit         ][Warning] vpnkit.exe: Error sending TCP packet via IP: no route to destination: no response for IP on local network 
[15:47:17.503][VpnKit         ][Warning] vpnkit.exe: ARP table has no entry for 10.0.75.1                                                          
[15:47:17.503][VpnKit         ][Info   ] vpnkit.exe: IP.output: could not determine link-layer address for local network (0.0.0.0/0) ip 10.0.75.1  
[15:47:17.503][VpnKit         ][Warning] vpnkit.exe: Could not find 10.0.75.1 on the local network                                                 
[15:47:17.503][VpnKit         ][Warning] vpnkit.exe: Error sending TCP packet via IP: no route to destination: no response for IP on local network

**Comment by djs55** [comment]
The log from `vpnkit` mentioning `10.0.75.1` are unexpected as `10.0.75.1` should be routed by Linux through the hyperV network adapter, bypassing `vpnkit`. Perhaps the routing/NAT is leaking and sending some packets to the wrong interface. Interestingly `vpnkit` attempts to `connect` to `10.0.75.1` and fails with "no route to destination" which is odd because `10.0.75.1` should be the host IP on the hyperV network. So maybe the hyperV network has gone missing and some process in the VM is still trying to contact the host over it (perhaps for CIFS). I'll take a look at the logs.

**Comment by djs55** [comment]
@bmweller I notice in your diagnostics there are 13175 outgoing connections on port 443 which is consuming a large amount of memory. I suspect this is [moby/vpnkit#371] which should be fixed in the most recent [D4win 18.05.0-ce-win67](https://download.docker.com/win/edge/18263/Docker%20for%20Windows%20Installer.exe). This doesn't explain the logs about `10.0.75.1` though, which is probably what is consuming the CPU in both `vpnkit` and `Docker.Service`.

**Comment by hecaidi** [comment]
@djs55 I am about to test de vpnkit.exe you have proposed at  [moby/vpnkit#371](https://github.com/moby/vpnkit/issues/371). 
I think tomorrow I will know if it works for me or not.
By the moment it's OK, but too soon to be sure

**Comment by djs55** [comment]
Here is where the log messages come from in the code:
- [Could not find ... on the local network](https://github.com/mirage/mirage-tcpip/blob/f7ef42ac137adf018550181343dbee602db6e71a/src/ipv4/static_ipv4.ml#L57)
- [Error sending TCP packet via IP...](https://github.com/mirage/mirage-tcpip/blob/f7ef42ac137adf018550181343dbee602db6e71a/src/tcp/wire.ml#L84)
- [ARP table has no entry for...](https://github.com/moby/vpnkit/blob/ae22283b503090803481dfa5e7bf1f431905dc11/src/hostnet/arp.ml#L80)
- [IP.output: count not determine link-layer address for local network...](https://github.com/mirage/mirage-tcpip/blob/f7ef42ac137adf018550181343dbee602db6e71a/src/ipv4/routing.ml#L31)]

Since `vpnkit` does not know about the address of `hvint0` (10.0.75.1) it must be responding to packets it received, which suggests that Linux is sending a packet on `eth0` (192.168.65.3) but with a return address of `10.0.75.1` (from `hvint0`)

**Comment by hecaidi** [comment]
I have left the computer running all the night. When I have arrived, RAM consumption was about 200 Mb, but now it has arrived to 1Gb and increasing.
The log is again full with 
[08:25:41.557][VpnKit         ][Warning] vpnkit.exe: Could not find 10.0.75.1 on the local network
[08:25:41.557][VpnKit         ][Warning] vpnkit.exe: Error sending TCP packet via IP: no route to destination: no response for IP on local network
[08:25:41.558][VpnKit         ][Warning] vpnkit.exe: ARP table has no entry for 10.0.75.1
[08:25:41.558][VpnKit         ][Info   ] vpnkit.exe: IP.output: could not determine link-layer address for local network (0.0.0.0/0) ip 10.0.75.1

**Comment by hecaidi** [comment]
I have tried too to revert to a docker previous version, 17.12.0-ce-win47 (15139).
I haven't tested time enough but I have seen a difference with 18.03.1: in 18.03.1 I can use route add for accessing docker subnetworks from the host.
For example:
  docker network create --subnet=172.18.0.0/24 envdev
  docker run --net envdev --ip 172.18.0.20 mycontainer
  route add 172.18.0.0 MASK 255.255.0.0 10.0.75.2
Then ping 172.18.0.20 is OK.

With same commands at 17.12.0, there were no response to ping.
Could this improvement be related with the problem?

**Comment by djs55** [comment]
@hecaidi interesting -- I'll investigate that.

Meanwhile if this bug is manifesting it would be interesting to see what traffic is being sent to `vpnkit`. Try the following command:
```
docker run -it --net=host djs55/tcpdump -n -i eth0
```
This will print a one-line summary of each packet, including the source and destination IP addresses.

For more in-depth analysis the command:
```
docker run -it --net=host -v C:\Users\<username>:/out djs55/tcpdump -n -s 0 -w /out/capture.pcap -i eth0
```
This will create a file `C:\Users\<username>\capture.pcap` containing the network packets.

**Comment by hecaidi** [comment]
@djs55 Today when I have turned on my computer the bug was directly manifesting, I had two containers at exited status
PS V:\> docker ps -a
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                  PORTS               NAMES
b59044344d7b        djs55/tcpdump       "/usr/sbin/tcpdump -…"   2 days ago          Exited (0) 2 days ago                       boring_yonath
dbe0a3b38244        djs55/tcpdump       "/usr/sbin/tcpdump -…"   2 days ago          Exited (0) 2 days ago                       eager_minsky

Result of 
  docker run -it --net=host djs55/tcpdump -n -i eth0

PS V:\> docker run -it --net=host djs55/tcpdump -n -i eth0
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on eth0, link-type EN10MB (Ethernet), capture size 262144 bytes
07:54:50.951309 IP 10.0.75.1.56084 > 172.18.57.23.443: Flags [S], seq 1752844363, win 64240, options [mss 1460,nop,wscale 8,nop,nop,sackOK], length 0
07:54:50.952430 IP 10.0.75.1.56085 > 172.18.11.223.443: Flags [S], seq 2443654481, win 64240, options [mss 1460,nop,wscale 8,nop,nop,sackOK], length 0
07:54:50.957077 IP 10.0.75.1.56087 > 172.18.11.223.443: Flags [S], seq 1063857914, win 64240, options [mss 1460,nop,wscale 8,nop,nop,sackOK], length 0
07:54:50.958803 IP 10.0.75.1.56088 > 172.18.11.223.443: Flags [S], seq 2100854126, win 64240, options [mss 1460,nop,wscale 8,nop,nop,sackOK], length 0
07:54:50.959964 IP 10.0.75.1.56089 > 172.18.57.23.443: Flags [S], seq 276041580, win 64240, options [mss 1460,nop,wscale 8,nop,nop,sackOK], length 0
07:54:50.961105 IP 10.0.75.1.56090 > 172.18.57.23.443: Flags [S], seq 1443770221, win 64240, options [mss 1460,nop,wscale 8,nop,nop,sackOK], length 0
07:54:50.962236 IP 10.0.75.1.56091 > 172.18.11.223.443: Flags [S], seq 699044980, win 64240, options [mss 1460,nop,wscale 8,nop,nop,sackOK], length 0
07:54:50.963506 IP 10.0.75.1.56092 > 172.18.11.223.443: Flags [S], seq 2292298954, win 64240, options [mss 1460,nop,wscale 8,nop,nop,sackOK], length 0
07:54:50.966775 IP 10.0.75.1.56093 > 172.18.11.223.443: Flags [S], seq 4147724211, win 64240, options [mss 1460,nop,wscale 8,nop,nop,sackOK], length 0
07:54:50.966828 IP 10.0.75.1.56094 > 172.18.57.23.443: Flags [S], seq 718011799, win 64240, options [mss 1460,nop,wscale 8,nop,nop,sackOK], length 0
07:54:50.968739 IP 10.0.75.1.56095 > 172.18.57.23.443: Flags [S], seq 2081003040, win 64240, options [mss 1460,nop,wscale 8,nop,nop,sackOK], length 0
07:54:50.970046 IP 10.0.75.1.56096 > 172.18.57.23.443: Flags [S], seq 684928274, win 64240, options [mss 1460,nop,wscale 8,nop,nop,sackOK], length 0
07:54:50.973409 IP 10.0.75.1.56097 > 172.18.57.23.443: Flags [S], seq 448195686, win 64240, options [mss 1460,nop,wscale 8,nop,nop,sackOK], length 0
07:54:50.974627 IP 10.0.75.1.56098 > 172.18.57.23.443: Flags [S], seq 908389450, win 64240, options [mss 1460,nop,wscale 8,nop,nop,sackOK], length 0
07:54:50.976647 IP 10.0.75.1.56099 > 172.18.11.223.443: Flags [S], seq 2790909770, win 64240, options [mss 1460,nop,wscale 8,nop,nop,sackOK], length 0
07:54:50.982683 IP 10.0.75.1.56100 > 172.18.57.23.443: Flags [S], seq 609996930, win 64240, options [mss 1460,nop,wscale 8,nop,nop,sackOK], length 0
07:54:50.984636 IP 10.0.75.1.56101 > 172.18.57.23.443: Flags [S], seq 498512624, win 64240, options [mss 1460,nop,wscale 8,nop,nop,sackOK], length 0
07:54:50.984658 IP 10.0.75.1.56102 > 172.18.11.223.443: Flags [S], seq 2087359714, win 64240, options [mss 1460,nop,wscale 8,nop,nop,sackOK], length 0
07:54:50.986559 IP 10.0.75.1.56103 > 172.18.11.223.443: Flags [S], seq 3115395019, win 64240, options [mss 1460,nop,wscale 8,nop,nop,sackOK], length 0
07:54:50.988785 IP 10.0.75.1.56104 > 172.18.11.223.443: Flags [S], seq 214428278, win 64240, options [mss 1460,nop,wscale 8,nop,nop,sackOK], length 0
07:54:50.990332 IP 10.0.75.1.56105 > 172.18.11.223.443: Flags [S], seq 3742131567, win 64240, options [mss 1460,nop,wscale 8,nop,nop,sackOK], length 0
07:54:50.991900 IP 10.0.75.1.56106 > 172.18.57.23.443: Flags [S], seq 2492127273, win 64240, options [mss 1460,nop,wscale 8,nop,nop,sackOK], length 0
07:54:50.993054 IP 10.0.75.1.56107 > 172.18.57.23.443: Flags [S], seq 4278026140, win 64240, options [mss 1460,nop,wscale 8,nop,nop,sackOK], length 0
07:54:50.994154 IP 10.0.75.1.56108 > 172.18.11.223.443: Flags [S], seq 259292269, win 64240, options [mss 1460,nop,wscale 8,nop,nop,sackOK], length 0
07:54:50.995644 IP 10.0.75.1.56109 > 172.18.11.223.443: Flags [S], seq 2628553902, win 64240, options [mss 1460,nop,wscale 8,nop,nop,sackOK], length 0
07:54:50.997590 IP 10.0.75.1.56110 > 172.18.11.223.443: Flags [S], seq 2824729837, win 64240, options [mss 1460,nop,wscale 8,nop,nop,sackOK], length 0
07:54:50.998979 IP 10.0.75.1.56111 > 172.18.57.23.443: Flags [S], seq 1531628097, win 64240, options [mss 1460,nop,wscale 8,nop,nop,sackOK], length 0
07:54:51.000337 IP 10.0.75.1.56112 > 172.18.57.23.443: Flags [S], seq 2906087497, win 64240, options [mss 1460,nop,wscale 8,nop,nop,sackOK], length 0
07:54:51.003840 IP 10.0.75.1.52040 > 172.18.57.23.443: Flags [S], seq 1569714431, win 64240, options [mss 1460,nop,wscale 8,nop,nop,sackOK], length 0
07:54:51.004588 IP 10.0.75.1.63445 > 172.18.57.23.443: Flags [S], seq 1273797451, win 64240, options [mss 1460,nop,wscale 8,nop,nop,sackOK], length 0
07:54:51.004614 IP 10.0.75.1.63456 > 172.18.11.223.443: Flags [S], seq 4098939804, win 64240, options [mss 1460,nop,wscale 8,nop,nop,sackOK], length 0
07:54:51.004619 IP 10.0.75.1.52093 > 172.18.11.223.443: Flags [S], seq 1705330276, win 64240, options [mss 1460,nop,wscale 8,nop,nop,sackOK], length 0
07:54:51.004623 IP 10.0.75.1.63441 > 172.18.11.223.443: Flags [S], seq 1011757838, win 64240, options [mss 1460,nop,wscale 8,nop,nop,sackOK], length 0
07:54:51.004626 IP 10.0.75.1.52089 > 172.18.57.23.443: Flags [S], seq 210241023, win 64240, options [mss 1460,nop,wscale 8,nop,nop,sackOK], length 0
07:54:51.004629 IP 10.0.75.1.52051 > 172.18.11.223.443: Flags [S], seq 3883923230, win 64240, options [mss 1460,nop,wscale 8,nop,nop,sackOK], length 0
07:54:51.005821 IP 10.0.75.1.56114 > 172.18.57.23.443: Flags [S], seq 2681655610, win 64240, options [mss 1460,nop,wscale 8,nop,nop,sackOK], length 0
07:54:51.006891 IP 10.0.75.1.56115 > 172.18.57.23.443: Flags [S], seq 4212690420, win 64240, options [mss 1460,nop,wscale 8,nop,nop,sackOK], length 0
07:54:51.009376 IP 10.0.75.1.56116 > 172.18.11.223.443: Flags [S], seq 1905844637, win 64240, options [mss 1460,nop,wscale 8,nop,nop,sackOK], length 0
07:54:51.011670 IP 10.0.75.1.63436 > 172.18.57.23.443: Flags [S], seq 1050511509, win 64240, options [mss 1460,nop,wscale 8,nop,nop,sackOK], length 0
07:54:51.011690 IP 10.0.75.1.52095 > 172.18.57.23.443: Flags [S], seq 3543957671, win 64240, options [mss 1460,nop,wscale 8,nop,nop,sackOK], length 0
07:54:51.011694 IP 10.0.75.1.63455 > 172.18.11.223.443: Flags [S], seq 3347315572, win 64240, options [mss 1460,nop,wscale 8,nop,nop,sackOK], length 0
07:54:51.011697 IP 10.0.75.1.63451 > 172.18.57.23.443: Flags [S], seq 1454651859, win 64240, options [mss 1460,nop,wscale 8,nop,nop,sackOK], length 0
07:54:51.011701 IP 10.0.75.1.63428 > 172.18.57.23.443: Flags [S], seq 830207922, win 64240, options [mss 1460,nop,wscale 8,nop,nop,sackOK], length 0
07:54:51.011704 IP 10.0.75.1.63424 > 172.18.11.223.443: Flags [S], seq 3614884606, win 64240, options [mss 1460,nop,wscale 8,nop,nop,sackOK], length 0
07:54:51.011707 IP 10.0.75.1.63429 > 172.18.11.223.443: Flags [S], seq 1880087963, win 64240, options [mss 1460,nop,wscale 8,nop,nop,sackOK], length 0
07:54:51.013859 IP 10.0.75.1.56118 > 172.18.57.23.443: Flags [S], seq 1188632660, win 64240, options [mss 1460,nop,wscale 8,nop,nop,sackOK], length 0
07:54:51.015901 IP 10.0.75.1.56119 > 172.18.11.223.443: Flags [S], seq 687339496, win 64240, options [mss 1460,nop,wscale 8,nop,nop,sackOK], length 0
07:54:51.015991 IP 10.0.75.1.56120 > 172.18.11.223.443: Flags [S], seq 2612267808, win 64240, options [mss 1460,nop,wscale 8,nop,nop,sackOK], length 0
07:54:51.018220 IP 10.0.75.1.56121 > 172.18.11.223.443: Flags [S], seq 2255050175, win 64240, options [mss 1460,nop,wscale 8,nop,nop,sackOK], length 0
07:54:51.022572 IP 10.0.75.1.56122 > 172.18.11.223.443: Flags [S], seq 56871156, win 64240, options [mss 1460,nop,wscale 8,nop,nop,sackOK], length 0
07:54:51.024773 IP 10.0.75.1.56123 > 172.18.57.23.443: Flags [S], seq 2092704780, win 64240, options [mss 1460,nop,wscale 8,nop,nop,sackOK], length 0
07:54:51.032252 IP 10.0.75.1.56124 > 172.18.57.23.443: Flags [S], seq 2996028772, win 64240, options [mss 1460,nop,wscale 8,nop,nop,sackOK], length 0
07:54:51.033646 IP 10.0.75.1.56125 > 172.18.11.223.443: Flags [S], seq 1705795461, win 64240, options [mss 1460,nop,wscale 8,nop,nop,sackOK], length 0
07:54:51.036159 IP 10.0.75.1.56126 > 172.18.11.223.443: Flags [S], seq 2682763341, win 64240, options [mss 1460,nop,wscale 8,nop,nop,sackOK], length 0
07:54:51.039930 IP 10.0.75.1.56127 > 172.18.11.223.443: Flags [S], seq 2768580084, win 64240, options [mss 1460,nop,wscale 8,nop,nop,sackOK], length 0
07:54:51.041057 IP 10.0.75.1.52061 > 172.18.57.23.443: Flags [S], seq 2417118811, win 64240, options [mss 1460,nop,wscale 8,nop,nop,sackOK], length 0
07:54:51.041064 IP 10.0.75.1.63477 > 172.18.11.223.443: Flags [S], seq 1044033333, win 64240, options [mss 1460,nop,wscale 8,nop,nop,sackOK], length 0
07:54:51.041069 IP 10.0.75.1.52106 > 172.18.57.23.443: Flags [S], seq 2211326445, win 64240, options [mss 1460,nop,wscale 8,nop,nop,sackOK], length 0
07:54:51.041072 IP 10.0.75.1.52110 > 172.18.11.223.443: Flags [S], seq 1889867030, win 64240, options [mss 1460,nop,wscale 8,nop,nop,sackOK], length 0


I have also generated a .pcap file, but I don't know how to send it to you.

**Comment by djs55** [comment]
@hecaidi thanks for the trace and the capture. I notice the source IP `10.0.75.1` is the hyper V network adapter on the host while the destination IP `172.18.x.y` is a container address.

Here is my best guess so far:
- Something on the host (a web browser) connects to a web server in a container using the internal container IP `172.18.11.223`.
- Since there is a route on the host to this network via the hyper V network, the source IP is set to `10.0.75.1` and the packet is transmitted to `10.0.75.2`.
- The packet arrives in the VM for further routing.
- My guess is that the `docker network` with range `172.18.0.0/24` is down. Therefore there is no route to it. The packet matches the default route instead.
- The packet leaves the VM on the `vpnkit` network and is logged as an error.

Could you check inside the VM whether the interface for the bridge / network `envdev` exists? For example:
```
$ docker network ls
NETWORK ID          NAME                DRIVER              SCOPE
322390d4a25f        bridge              bridge              local
2b7d2081388b        host                host                local
ef881867c0b8        none                null                local
9a0f488d1a30        envdev              bridge              local
^^^^^^
```
and then
```
$ docker run -it --privileged --pid=host justincormack/nsenter1
/ # ifconfig
...
br-9a0f488d1a30 Link encap:Ethernet  HWaddr 02:42:56:70:9B:D6
          inet addr:172.18.0.1  Bcast:172.18.0.255  Mask:255.255.255.0
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
...
/ #  route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         192.168.65.1    0.0.0.0         UG    0      0        0 eth0
127.0.0.0       0.0.0.0         255.0.0.0       U     0      0        0 lo
172.17.0.0      0.0.0.0         255.255.0.0     U     0      0        0 docker0
172.18.0.0      0.0.0.0         255.255.255.0   U     0      0        0 br-9a0f488d1a30
^^^^
192.168.65.0    0.0.0.0         255.255.255.0   U     0      0        0 eth0
```
Perhaps also upload a diagnostic in this state so I can have a quick look at the logs.

**Comment by hecaidi** [comment]
@djs55 Here you have the results you have asked me for, today after restarting the computer, with the problem going on. 

PS V:\> docker network ls
NETWORK ID          NAME                DRIVER              SCOPE
135c7fde3f13        bridge              bridge              local
9d17bc0c0ec9        envdev              bridge              local
472bd10a4c91        host                host                local
1283c184607a        none                null                local

PS V:\> docker ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES

PS V:\> docker run -it --privileged --pid=host justincormack/nsenter1

/ # ifconfig
br-9d17bc0c0ec9 Link encap:Ethernet  HWaddr 02:42:2E:A6:B9:B3
          inet addr:172.18.0.1  Bcast:172.18.0.255  Mask:255.255.255.0
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)


/ # route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         192.168.65.1    0.0.0.0         UG    205    0        0 eth0
10.0.75.0       0.0.0.0         255.255.255.0   U     0      0        0 hvint0
127.0.0.0       0.0.0.0         255.0.0.0       U     0      0        0 lo
172.17.0.0      0.0.0.0         255.255.0.0     U     0      0        0 docker0
172.18.0.0      0.0.0.0         255.255.255.0   U     0      0        0 br-9d17bc0c0ec9
192.168.65.0    0.0.0.0         255.255.255.0   U     205    0        0 eth0


A diagnostic was uploaded with id: 75B15EBC-1149-4272-8F7E-26C07F194858/2018-06-26_09-46-29

**Comment by hecaidi** [comment]
@djs55 I think you have made a really good point there.
I have just made the changes:
  docker network create --subnet=172.18.0.0/24 envdev
  docker run --net envdev --ip 172.18.0.20 mycontainer
  route add 172.18.0.0 MASK 255.255.255.0 10.0.75.2

By the moment (too soon of course) everything is OK. I have even manually pinged 172.18.57.23 to force the error.
Tomorrow I will confirm you that the problem is not back, but I feel really confident about this.
Thanks a lot for all your help.

Would be this the right wait to made visible a container subnetwork to the host? 
Publishing ports were not enough for our projet needs.

**Comment by djs55** [comment]
@hecaidi thanks again for the fast update. Glad to hear it's working so far.

Regarding whether this is the right way or not: I suspect there isn't one perfect way that works for everyone. I'm interested to find out how well this approach works for you. Also could you describe your use-case a little more to help me understand why publishing ports didn't work well enough?

Thanks!

**Comment by hecaidi** [comment]
@djs55 We have an image of a third-party application server which makes redirections using its own port.
This port is in use both in the container and in the host. So for publishing it we must use a different value for the host.
When the application server uses the redirection, it is unhappily pointing to a different application in the host.

Of course it could be other work-arounds, but I find creating subnets the simplest one.

**Comment by hecaidi** [comment]
@djs55 I've been working now for a whole day with docker and the problem has not been reproduced.
So for me, it's resolved.
Thanks again for all your help

**Comment by djs55** [comment]
@hecaidi thanks again for the prompt update -- I'm glad we figured this out! I'm curious to find out how well this approach work in practice so please let me know if you encounter any other problems.

@bmweller have you had a chance to try the most recent [D4win 18.05.0-ce-win67](https://download.docker.com/win/edge/18263/Docker%20for%20Windows%20Installer.exe) with the memory leak fix? Do you have a similar routing problem to @hecaidi?

**Comment by rn** [comment]
Closing this issue. We believe this is fixed. Please comment/re-open if it is not. Thanks for the help debugging

**Comment by Fr1kki3** [comment]
Not fixed

**Comment by zvinger** [comment]
Not fixed too

**Comment by zvinger** [comment]
1D8E2F8F-AFFA-47B4-AB95-A3BB703C8546/20180816100950 this is diagnose id. The log errors of vpnkit are same

**Comment by paolosalvatori** [comment]
Definitely not fixed. I have to set low priority to minimize the CPU consumption any time I start the machine. Not good.

**Comment by industrial64** [comment]
This is not natively fixed.
However I fixed by setting the SWAP and Mem much higher to cope with Docker imperfectly assigning resources to K8s. Silly CPU load gone.

**Comment by DealWithMeal** [comment]
still not fixed :(

**Comment by maeglindeveloper** [comment]
@djs55 , is there more investigation regarding this issue? :s 
Thanks in advance :)

**Comment by dannyk81** [comment]
@djs55 this seems like a recurring issue, I tried the suggested fixes here, but nothing helps 😞 

Here's my Diagnostic ID: 5459E06B-6398-479F-B0E7-08E317758B02/20180920140710

My stack:
```
Docker Version 2.0.0.0-beta1-win75 (19925)
Windows 10 Insider Preview 17758.1 (rs5_release)
```
Kubernetes is disabled and I increased RAM allocation to 3GB.

In my case, the issue seem worse when connecting to VPN, I start seeing a lot of these messages and CPU usage spikes:
```
[11:16:12.447][DnsUpdater     ][Info   ] Network configuration change detected
[11:16:12.447][PowerShell     ][Info   ] Run script '$(Find-NetRoute -RemoteIPAddress 8.8.8.8).InterfaceIndex[0]'...
[11:16:12.775][DnsUpdater     ][Info   ] Network configuration change detected
[11:16:12.775][PowerShell     ][Info   ] Run script '$(Find-NetRoute -RemoteIPAddress 8.8.8.8).InterfaceIndex[0]'...
[11:16:13.098][DnsUpdater     ][Info   ] Network configuration change detected
[11:16:13.098][PowerShell     ][Info   ] Run script '$(Find-NetRoute -RemoteIPAddress 8.8.8.8).InterfaceIndex[0]'...
[11:16:13.459][DnsUpdater     ][Info   ] Network configuration change detected
[11:16:13.459][PowerShell     ][Info   ] Run script '$(Find-NetRoute -RemoteIPAddress 8.8.8.8).InterfaceIndex[0]'...
[11:16:13.781][DnsUpdater     ][Info   ] Network configuration change detected
[11:16:13.782][PowerShell     ][Info   ] Run script '$(Find-NetRoute -RemoteIPAddress 8.8.8.8).InterfaceIndex[0]'...
[11:16:14.100][DnsUpdater     ][Info   ] Network configuration change detected
[11:16:14.100][PowerShell     ][Info   ] Run script '$(Find-NetRoute -RemoteIPAddress 8.8.8.8).InterfaceIndex[0]'...
[11:16:14.446][DnsUpdater     ][Info   ] Network configuration change detected
[11:16:14.446][PowerShell     ][Info   ] Run script '$(Find-NetRoute -RemoteIPAddress 8.8.8.8).InterfaceIndex[0]'...
[11:16:14.772][DnsUpdater     ][Info   ] Network configuration change detected
[11:16:14.772][PowerShell     ][Info   ] Run script '$(Find-NetRoute -RemoteIPAddress 8.8.8.8).InterfaceIndex[0]'...
[11:16:15.087][DnsUpdater     ][Info   ] Network configuration change detected
[11:16:15.087][PowerShell     ][Info   ] Run script '$(Find-NetRoute -RemoteIPAddress 8.8.8.8).InterfaceIndex[0]'...
```

and more deatils here as well --> https://github.com/docker/for-win/issues/1772#issuecomment-421586273

**Comment by cforce** [comment]
Please reopen and fix ..its still there.

**Comment by dannyk81** [comment]
@rn @djs55 kindly 🙏 please re-open this issue and investigate this further, it is clearly still an issue and affects many users.

The exact same thing is being report here https://github.com/docker/for-win/issues/1772 as well.

If there's any information you're missing, please give us a shout. I know that I for one use docker on my workstation daily and right now have to constantly start/stop it, which is huge PITA to say the least.

Thank you!

**Comment by Stradivario** [comment]
Consider switching to linux it is a dead zone for me to work with virtual docker machine.Before 3 years due to 40 GB RAM usage of 44 GB with only  10 docker containers i decided to format C: and install linux distribution (Ubuntu 16.10) since then my development process is far more effective!

**Comment by bmweller** [comment]
Yep, that's what I did (dual boot). Ubuntu Bionic works super well on my
Lenovo P50. As an added bonus I can use my GPU via nvidia-docker, something
which is not support in MS Hyper-v.

Shame really but that's the reality.

**Comment by EduardoLeonMiranda** [comment]
still not fixed :(

**Comment by techpavan** [comment]
Occurred to me since two days. I realized that the issue was due to addition of a persistent route as a solution for https://github.com/docker/for-win/issues/221 

Resolution for high CPU usage in my case was to remove the persistent route - `route -p delete IP_ADDRESS` 

IP_ADDRESS can be viewed using this command `route print -4` and scroll to bottom under persistent routes.

**Comment by thiagoki** [comment]
techpavan,
I had the same problem and your solution worked for me!
Thanks

**Comment by whitecolor** [comment]
@techpavan and how did you solve #221 related issue?

**Comment by MJPA** [comment]
@rn this is not fixed. It is caused by the workaround for #221 - removing the route and memory usage is stable. Adding the route and memory usage goes up and up until the host runs out of memory and the docker service needs restarting.

This is an issue for plenty of people because of the poor performance of volumes on Windows. A php web app is horrendously slow if you mount from the host. You can get around this by using proper Docker volumes but then you can't edit the files on the host. Workaround is to have a samba server as a Docker container that shares the volume back to the host. Problem is, the host can't access the container without the workaround for #221. If this can actually be fixed, it solves a major headache for a lot people and makes Docker on Windows usable for them.
