### ISSUE TITLE
Kubernetes fails to start (hangs in starting phase)

### ISSUE THREAD

**Issue by unjello** [docker/for-win#1962]
Please, check https://docs.docker.com/docker-for-win/troubleshoot/.
Issues without logs and details cannot be debugged, and will be closed.

  - [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have submitted Diagnostics
  - [x] I have included the Diagnostics ID in this Issue
  - Windows Version: Windows 10; version 1803; OS build: 17133.73; Hyper-V enabled.
  - Docker for Windows Version: Docker Edge 18.04.0-ce-win62 (17151) - but it happened before too.

### Expected behavior

Kubernetes cluster should start, Settings panel should have green dot saying *Kubernetes is running*.
`kubectl get pods` should return empty set.

### Actual behavior

Kubernetes is stuck in *Kubernetes is starting* phase. `kubetctl get pods` hangs.

### Information

Diagnostic ID: 943836AC-0B99-4BEE-BC82-900781400047/2018-04-17_23-06-41

### Steps to reproduce the behavior

This issue looks a lot like https://github.com/docker/for-win/issues/1845, which I am not sure why OP closed.

  1. Enter `Settings`
  2. Go to `Kubernetes` menu
  3. Select `Enable Kubernetes`
  4. Hit `Apply`

Tried `Reset to factory settings` and different combinations of resetting. The port `6445` seems to be correctly tunneled, as I see `vpnkit.exe` listening on it. K8s images are downloaded, no k8s dockers are visible in `docker ps` and docker logs include following entries:

```
[23:04:53.517][ApiProxy       ][Info   ] time="2018-04-17T23:04:53+02:00" msg="Node status error: Get https://localhost:6445/api/v1/nodes: EOF"
[23:04:54.513][ApiProxy       ][Info   ] time="2018-04-17T23:04:54+02:00" msg="Node status error: Get https://localhost:6445/api/v1/nodes: EOF"
...
[23:05:59.014][ApiProxy       ][Info   ] time="2018-04-17T23:05:59+02:00" msg="Node status error: the server was unable to return a response in the time allotted, but may still be processing the request (get nodes)"
...
[23:06:52.721][ApiProxy       ][Info   ] time="2018-04-17T23:06:52+02:00" msg="Node status error: Get https://localhost:6445/api/v1/nodes: http2: server sent GOAWAY and closed the connection; LastStreamID=3, ErrCode=NO_ERROR, debug=\"\""
```

**Comment by cuiping1004** [comment]
have the same issue

**Comment by cuiping1004** [comment]
I resolve this issue by delete ./kube/config

**Comment by vmilitello** [comment]
Same issue. Things that I tried:
1) deleting %userprofile%/.kube/config as suggested by @cuiping1004 
2) Reset Docker to Factory 
3) Reinstall Docker Edge
4) Remove IPV6 from all the Switch created by HyperV
5) Pray every God (included SpongeBob and Jimy Hendrix)  

The error reported in the log file is always the same

[13:57:05.303][**ApiProxy**       ][Info   ] time="2018-06-06T13:57:05-07:00" msg="**Node status error: Get https://localhost:6445/api/v1/nodes: EOF**"
[13:57:06.305][ApiProxy       ][Info   ] time="2018-06-06T13:57:06-07:00" msg="Node status error: Get https://localhost:6445/api/v1/nodes: EOF"
[13:57:07.305][ApiProxy       ][Info   ] time="2018-06-06T13:57:07-07:00" msg="Node status error: Get https://localhost:6445/api/v1/nodes: EOF"
[13:57:08.305][**VpnKit**         ][Error  ] **vpnkit.exe: Hvsock.read: An established connection was aborted by the software in your host machine.**

Funny fact: Docker itself works great. I tried 

```sh
docker run hello-world
```
as well as 
```sh 
docker run -it ubuntu bash
```
With both container I had no problem whatsoever.

Inside the ubuntu container, I was able to call apt-get update and apt-get install, so external connection works fine.

**Comment by bacongobbler** [comment]
surprisingly, @cuiping1004's solution worked for me. My steps:

1. disable Kubernetes from the Settings window
2. Open a Powershell terminal and `rm -r .\.kube` from within my home directory
3. Re-enable Kubernetes from the Settings window

After that `kubectl cluster-info` connects and returns cluster information, whereas before it'd hang and fail with a connection error.

fwiw I still see the error `vpnkit.exe: Hvsock.read: An established connection was aborted by the software in your host machine.` in my logs, but everything seems to be just fine.

```
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

PS C:\Users\mafishe> kubectl get nodes
NAME                 STATUS    ROLES     AGE       VERSION
docker-for-desktop   Ready     master    25m       v1.10.3
PS C:\Users\mafishe> kubectl -n kube-system get pods
NAME                                         READY     STATUS    RESTARTS   AGE
etcd-docker-for-desktop                      1/1       Running   1          24m
kube-apiserver-docker-for-desktop            1/1       Running   2          24m
kube-controller-manager-docker-for-desktop   1/1       Running   1          24m
kube-dns-86f4d74b45-7cs57                    3/3       Running   3          25m
kube-proxy-zgbqf                             1/1       Running   1          25m
kube-scheduler-docker-for-desktop            1/1       Running   1          24m
```

**Comment by bacongobbler** [comment]
As far as diagnostic information goes:

Version 18.05.0-ce-win67 (18263)
Channel: edge
0c7f1aa

And indeed, docker itself was working fine the entire time, just not `kubectl`.

**Comment by vilinski** [comment]
Same issue. 

- after activating kubernetes, the dialog "installing kubernetes cluster" appears, but nothing happens. 
- after some time I close the dialog. Complete Kubernetes window is still disabled.
- can't disable Kubernetes from settings window. 
- set `"KubernetesEnabled": false`, in the `%appdata%/Docker/settings.json`. Didn't help. 
- Tried to remove `%appdata%/{Docker,Kubernetes}` and reinstall docker. Didn't help.

**Comment by dfme** [comment]
I have the same issue which I already have reported here: https://github.com/docker/for-win/issues/2065

**Comment by kasvith** [comment]
having the same issue here

**Comment by giftkugel** [comment]
I've got the same Issue on my Windows machine.
Was stuck in the "Kubernetes is starting" procedure and couldn't disable Kubernetes from the settings window.

I have chosen the "Reset to factory defaults" from the settings window to get rid of the hanging Kubernetes instance. **This will delete your MobyLinuxVM Hyper-V VM and get rid of everything!**

For a second try I fully disabled my Windows firewalls and tried again.

Now Kubernetes is installed and up and running. 😄 

Maybe the Docker configuration should setup the Windows firewall rules for Docker+Kubernetes!

![image](https://user-images.githubusercontent.com/9103924/44995342-eb2da500-afa2-11e8-9ac4-8f363364a39e.png)

**Comment by anwalkers** [comment]
Diagnostic ID: 51BE916F-11C1-4855-9037-9EE0541E1A40/20180905161830

I have tried every firewall rule with IT. They have added vpnkit.exe to the rule set to BitDefender to allow every outgoing connection. Still no luck.

```log
[16:05:08.952][ApiProxy       ][Info   ] time="2018-09-05T16:05:08-07:00" msg="Starting kubernetes cluster"
[16:05:08.952][ApiProxy       ][Debug  ] time="2018-09-05T16:05:08-07:00" msg="socket.DialUnix: \\\\.\\pipe\\dockerBackendToGui"
[16:05:08.967][KubernetesState][Info   ] received kubernetesstate command - SetState : starting
[16:05:09.296][ApiProxy       ][Info   ] Init returned
[16:05:09.296][ApiProxy       ][Info   ] time="2018-09-05T16:05:09-07:00" msg="Cluster config received"
[16:05:09.336][ApiProxy       ][Info   ] get_ip returned {192.168.65.3}
[16:05:09.337][VpnKit         ][Info   ] vpnkit.exe: Using protocol TwoThousand msize 16384

[16:05:09.338][ApiProxy       ][Info   ] Expose tcp:0.0.0.0:6445:tcp:192.168.65.3:6443
[16:05:09.338][ApiProxy       ][Info   ] Failed to walk to [tcp:0.0.0.0:6445:tcp:192.168.65.3:6443] 9p: file not found
[16:05:09.342][ApiProxy       ][Info   ] Expose tcp:0.0.0.0:6445:tcp:192.168.65.3:6443: succeeded with tcp:0.0.0.0:6445:tcp:192.168.65.3:6443
[16:05:10.138][VpnKit         ][Info   ] vpnkit.exe: Connected Ethernet interface f6:16:36:bc:f9:c6

[16:05:10.138][VpnKit         ][Info   ] vpnkit.exe: UDP interface connected on 192.168.65.1

[16:05:10.347][VpnKit         ][Error  ] vpnkit.exe: Hvsock.read: An established connection was aborted by the software in your host machine.


[16:05:10.348][ApiProxy       ][Info   ] time="2018-09-05T16:05:10-07:00" msg="Cannot list nodes: Get https://localhost:6445/api/v1/nodes: EOF"
[16:05:11.348][ApiProxy       ][Info   ] time="2018-09-05T16:05:11-07:00" msg="Cannot list nodes: Get https://localhost:6445/api/v1/nodes: EOF"
[16:05:12.347][VpnKit         ][Error  ] vpnkit.exe: Hvsock.read: An established connection was aborted by the software in your host machine.


[16:05:12.347][ApiProxy       ][Info   ] time="2018-09-05T16:05:12-07:00" msg="Cannot list nodes: Get https://localhost:6445/api/v1/nodes: EOF"
[16:05:13.346][VpnKit         ][Error  ] vpnkit.exe: Hvsock.read: An established connection was aborted by the software in your host machine.


[16:05:13.347][ApiProxy       ][Info   ] time="2018-09-05T16:05:13-07:00" msg="Cannot list nodes: Get https://localhost:6445/api/v1/nodes: EOF"
[16:05:14.347][VpnKit         ][Error  ] vpnkit.exe: Hvsock.read: An established connection was aborted by the software in your host machine.


[16:05:14.348][ApiProxy       ][Info   ] time="2018-09-05T16:05:14-07:00" msg="Cannot list nodes: Get https://localhost:6445/api/v1/nodes: EOF"
[16:05:15.345][VpnKit         ][Error  ] vpnkit.exe: Hvsock.read: An established connection was aborted by the software in your host machine.


[16:05:15.346][ApiProxy       ][Info   ] time="2018-09-05T16:05:15-07:00" msg="Cannot list nodes: Get https://localhost:6445/api/v1/nodes: EOF"
[16:05:15.779][VpnKit         ][Info   ] vpnkit.exe: Connected Ethernet interface f6:16:36:bc:f9:c6

[16:05:15.779][VpnKit         ][Info   ] vpnkit.exe: UDP interface connected on 172.23.110.15

[16:05:16.347][VpnKit         ][Error  ] vpnkit.exe: Hvsock.read: An established connection was aborted by the software in your host machine.


[16:05:16.348][ApiProxy       ][Info   ] time="2018-09-05T16:05:16-07:00" msg="Cannot list nodes: Get https://localhost:6445/api/v1/nodes: EOF"
[16:05:17.350][VpnKit         ][Error  ] vpnkit.exe: Hvsock.read: An established connection was aborted by the software in your host machine.


[16:05:17.353][ApiProxy       ][Info   ] time="2018-09-05T16:05:17-07:00" msg="Cannot list nodes: Get https://localhost:6445/api/v1/nodes: EOF"
[16:05:18.172][VpnKit         ][Info   ] vpnkit.exe: Connected Ethernet interface f6:16:36:bc:f9:c6

[16:05:18.172][VpnKit         ][Info   ] vpnkit.exe: UDP interface connected on 74.125.195.82

[16:05:18.346][VpnKit         ][Error  ] vpnkit.exe: Hvsock.read: An established connection was aborted by the software in your host machine.


[16:05:18.346][ApiProxy       ][Info   ] time="2018-09-05T16:05:18-07:00" msg="Cannot list nodes: Get https://localhost:6445/api/v1/nodes: EOF"
[16:05:18.805][VpnKit         ][Info   ] vpnkit.exe: Connected Ethernet interface f6:16:36:bc:f9:c6

[16:05:18.805][VpnKit         ][Info   ] vpnkit.exe: UDP interface connected on 172.217.3.176

[16:05:19.347][ApiProxy       ][Info   ] time="2018-09-05T16:05:19-07:00" msg="Cannot list nodes: Get https://localhost:6445/api/v1/nodes: EOF"
[16:05:20.345][VpnKit         ][Error  ] vpnkit.exe: Hvsock.read: An established connection was aborted by the software in your host machine.


[16:05:20.346][ApiProxy       ][Info   ] time="2018-09-05T16:05:20-07:00" msg="Cannot list nodes: Get https://localhost:6445/api/v1/nodes: EOF"
[16:05:21.346][ApiProxy       ][Info   ] time="2018-09-05T16:05:21-07:00" msg="Cannot list nodes: Get https://localhost:6445/api/v1/nodes: EOF"
[16:05:21.668][ApiProxy       ][Info   ] time="2018-09-05T16:05:21-07:00" msg="proxy >> GET /_ping\n"
[16:05:21.669][ApiProxy       ][Info   ] time="2018-09-05T16:05:21-07:00" msg="proxy << GET /_ping\n"
[16:05:21.670][ApiProxy       ][Info   ] time="2018-09-05T16:05:21-07:00" msg="proxy >> GET /v1.38/containers/json?all=1\n"
[16:05:21.673][ApiProxy       ][Info   ] time="2018-09-05T16:05:21-07:00" msg="proxy << GET /v1.38/containers/json?all=1\n"
[16:05:22.353][VpnKit         ][Error  ] vpnkit.exe: Hvsock.read: An established connection was aborted by the software in your host machine.


[16:05:22.355][ApiProxy       ][Info   ] time="2018-09-05T16:05:22-07:00" msg="Cannot list nodes: Get https://localhost:6445/api/v1/nodes: EOF"
[16:05:23.346][VpnKit         ][Error  ] vpnkit.exe: Hvsock.read: An established connection was aborted by the software in your host machine.


[16:05:23.347][ApiProxy       ][Info   ] time="2018-09-05T16:05:23-07:00" msg="Cannot list nodes: Get https://localhost:6445/api/v1/nodes: EOF"
[16:05:24.347][VpnKit         ][Error  ] vpnkit.exe: Hvsock.read: An established connection was aborted by the software in your host machine.


[16:05:24.348][ApiProxy       ][Info   ] time="2018-09-05T16:05:24-07:00" msg="Cannot list nodes: Get https://localhost:6445/api/v1/nodes: EOF"
```

![image](https://user-images.githubusercontent.com/3085122/45126632-3376cf80-b129-11e8-893b-8e0a7e636263.png)

![image](https://user-images.githubusercontent.com/3085122/45126701-894b7780-b129-11e8-8474-6ff140f7d2ae.png)

**Comment by HaleLu** [comment]
@anwalkers +1

**Comment by patrickbadley** [comment]
@anwalkers Have you had any luck with this?  I'm running into the same issue.

**Comment by anwalkers** [comment]
@patrickbadley No luck...

**Comment by anwalkers** [comment]
@patrickbadley I did try it at home and succeeded to get it running on my surface, not on the corporate network. 

Diagnostic ID for the successful startup: 4CE55FC1-174C-4F00-AD3D-75E954F136D2/20180918213135

**Comment by JohanSellberg** [comment]
I had the same problem.
Similar to @anwalkers I had problem when connected to the corporate network. But when I instead used 4G connection on the same computer it worked fine. So probably blocked somehow in corporate firewall for me. 

Docker hello-world worked fine for me too with corporate network so downloading images and such was not a problem but something else was blocked when trying kubernetes.

**Comment by anwalkers** [comment]
@JohanSellberg @patrickbadley I have it running. I had to change my DNS services from our corporate servers to a public server. I am using the Verisign DNS servers and changed both the IPv4 and IPv6 protocols. I still have the vpnkit firewall rule in place as well. Hope this helps...

![image](https://user-images.githubusercontent.com/3085122/46232685-d1267e80-c324-11e8-89b9-5c607240f3c7.png)

**Comment by jherman** [comment]
@anwalkers Where did you change the DNS? On the DockerNAT adapter?  I changed it there, but still no luck for me.

**Comment by anwalkers** [comment]
@jherman on my host machine. Not in Hyper-V or Docker.

**Comment by jherman** [comment]
I initially installed Docker on my desktop that's my devbox.  Couldn't get K8s working and ran through the gamut of the suggestions here and other threads, but none of them worked.

Got tired of fussing around on that so I installed on a clean windows 10 environment on my laptop where HyperV had not been installed yet.  K8s worked right away.  However 3 hours later when I rebooted the machine, I started seeing that K8s wouldn't come back up and once again seeing the same exact issue on my laptop:

```
[11:09:33.606][ApiProxy       ][Info   ] time="2018-10-03T11:09:33-07:00" msg="Cannot list nodes: Get https://localhost:6445/api/v1/nodes: EOF"
[11:09:34.604][VpnKit         ][Error  ] vpnkit.exe: Hvsock.read: An established connection was aborted by the software in your host machine.
```

A day later, I tried running it again on my desktop that morning.  Still failing.  Try again in the afternoon, and all of sudden it starts working.  WTF?

There has to be something fundamentally wrong... maybe there is a timing issue within the containers...

**Comment by emarques** [comment]
I also have my laptop sitting behind a corporate network doing the steps of:
Creating a rule for the VPNkit and changing my DNS server names to public ones did it for me

**Comment by anwalkers** [comment]
I tried another experiment and it seems to have solved the corporate DNS server and firewall issue. I changed the DNS setting on the network tab of the docker settings to be "fixed" to goggle's DNS server (8.8.8.8). With this small change kubernetes has not problem spinning up after a reset.

![image](https://user-images.githubusercontent.com/3085122/46764842-66653380-cc92-11e8-986b-ce16ad4db243.png)

**Comment by jherman** [comment]
I've tried doing that as well, but I only get the following results:

```
 time="2018-10-10T13:53:47-07:00" msg="2/3 system pods running, waiting..."
[13:53:48.766][ApiProxy       ][Info   ] time="2018-10-10T13:53:48-07:00" msg="2/3 system pods running, waiting..."
[13:53:48.995][DnsUpdater     ][Info   ] Network configuration change detected
[13:53:48.995][DnsUpdater     ][Error  ] Unable to update dns settings: Value cannot be null.
Parameter name: first
[13:53:49.098][DnsUpdater     ][Info   ] Network configuration change detected
[13:53:49.103][DnsUpdater     ][Error  ] Unable to update dns settings: Value cannot be null.
Parameter name: first
[13:53:49.768][ApiProxy       ][Info   ] time="2018-10-10T13:53:49-07:00" msg="2/3 system pods running, waiting..."
[13:53:50.033][DnsUpdater     ][Info   ] Network configuration change detected
[13:53:50.034][DnsUpdater     ][Error  ] Unable to update dns settings: Value cannot be null.
Parameter name: first
[13:53:50.186][DnsUpdater     ][Info   ] Network configuration change detected
[13:53:50.187][DnsUpdater     ][Error  ] Unable to update dns settings: Value cannot be null.
Parameter name: first
[13:53:50.766][ApiProxy       ][Info   ] time="2018-10-10T13:53:50-07:00" msg="2/3 system pods running, waiting..."
[13:53:51.767][ApiProxy       ][Info   ] time="2018-10-10T13:53:51-07:00" msg="2/3 system pods running, waiting..."
[13:53:52.766][ApiProxy       ][Info   ] time="2018-10-10T13:53:52-07:00" msg="2/3 system pods running, waiting..."
[13:53:53.164][DnsUpdater     ][Info   ] Network configuration change detected
[13:53:53.164][DnsUpdater     ][Error  ] Unable to update dns settings: Value cannot be null.
Parameter name: first
[13:53:53.765][ApiProxy       ][Info   ] time="2018-10-10T13:53:53-07:00" msg="2/3 system pods running, waiting..."
[13:53:54.766][ApiProxy       ][Info   ] time="2018-10-10T13:53:54-07:00" msg="2/3 system pods running, waiting..."
[13:53:55.793][ApiProxy       ][Info   ] time="2018-10-10T13:53:55-07:00" msg="2/3 system pods running, waiting..."
[13:53:56.766][ApiProxy       ][Info   ] time="2018-10-10T13:53:56-07:00" msg="2/3 system pods running, waiting..."
[13:53:57.768][ApiProxy       ][Info   ] time="2018-10-10T13:53:57-07:00" msg="2/3 system pods running, waiting..."
[13:53:58.767][ApiProxy       ][Info   ] time="2018-10-10T13:53:58-07:00" msg="2/3 system pods running, waiting..."
[13:53:59.767][ApiProxy       ][Info   ] time="2018-10-10T13:53:59-07:00" msg="2/3 system pods running, waiting..."
[13:54:00.776][ApiProxy       ][Info   ] time="2018-10-10T13:54:00-07:00" msg="2/3 system pods running, waiting..."
[13:54:01.788][ApiProxy       ][Info   ] time="2018-10-10T13:54:01-07:00" msg="2/3 system pods running, waiting..."
[13:54:02.781][ApiProxy       ][Info   ] time="2018-10-10T13:54:02-07:00" msg="2/3 system pods running, waiting..."
[13:54:02.912][VpnKit         ][Error  ] vpnkit.exe: Socket.UDPv4.read: udp -> 8.8.8.8:53 caught Lwt.Resolution_loop.Canceled returning Eof

[13:54:03.789][ApiProxy       ][Info   ] time="2018-10-10T13:54:03-07:00" msg="2/3 system pods running, waiting..."
[13:54:04.831][ApiProxy       ][Info   ] time="2018-10-10T13:54:04-07:00" msg="2/3 system pods running, waiting..."
[13:54:05.776][ApiProxy       ][Info   ] time="2018-10-10T13:54:05-07:00" msg="2/3 system pods running, waiting..."
```

**Comment by anwalkers** [comment]
@jherman Did you reset docker? I had to...

**Comment by gysi** [comment]
> I tried another experiment and it seems to have solved the corporate DNS server and firewall issue. I changed the DNS setting on the network tab of the docker settings to be "fixed" to goggle's DNS server (8.8.8.8). With this small change kubernetes has not problem spinning up after a reset.

This did it for me when I'm within a corporate network.

**Comment by rickynguyen4590** [comment]
Finally, I got it
![image](https://user-images.githubusercontent.com/2346112/47133362-ae0f3f00-d2d2-11e8-8f8a-4d79717fb94a.png)
And this is my checklist:

1. Make sure  firewall allow vpnkit.exe (If you use this function "Allow an app through the firewall", it's only added to inbound rule)
2. Make sure  KUBECONFIG Env variable correct. After docker installation , it isn't correct at all 'C:\Users\RickyNguyen.kube\config' and it should be 'C:\Users\RickyNguyen.kube\config'
3. Change DNS to public DNS, (8.8.8.8 google DNS in my case)
4. Remove .kube folder on USER directory
5. Rest Docker and K8s somestime

Good luck

**Comment by jherman** [comment]
@rickynguyen4590 This actually worked for me.  Not really sure why, because I could swear I've done these steps but maybe not in this order.  Somethings I noted:

#2 My KUBECONFIG envar was already properly set, so I left it alone
#3 You didn't specify if you changed the host DNS or DNS in the docker networks settings view.  I did both just to be safe.
#5 Since I was had reset everything to default, I only added K8s and it worked.  The only strange thing I see now is that logs still show:
```
[10:15:11.045][DnsUpdater     ][Info   ] Network configuration change detected
[10:15:11.045][DnsUpdater     ][Error  ] Unable to update dns settings: Value cannot be null.
Parameter name: first
```
At least the good news is that k8s is running.  Thanks for the tips!

**Comment by JoseThen** [comment]
At one point I managed to get this to work using @jherman and @rickynguyen4590 's steps, however when I chose to restart docker and kubernetes completely (using the docker icon in the tool bar) the issue came back.

Even tried using Docker Edge.

**Comment by dradkov** [comment]
@jherman how to change host DNS and with what?I've tried all steps above exept change host with no success.

**Comment by jherman** [comment]
> @jherman how to change host DNS and with what?I've tried all steps above exept change host with no success.

@dradkov The in the "Network" tab of the Docker settings.  You can see a screenshot posted above from someone else.  I used Google's DNS, 8.8.8.8, just like in the screenshot. I also changed it in the network adapter setting in windows.

**Comment by davidshen84** [comment]
I found a lot of people, include me, have this problem, and the root cause is because the Kubernetes installation package cannot be downloaded. I wonder if they could allow users to download the Kubernetes for Windows package and install it manually, then enable it in the Docker's setting dialog.

**Comment by JoseThen** [comment]
I was able to get this working even after restarting docker::

1. Change DNS to fixed and use 8.8.8.8, this is within docker for window's settings
2. Remove the `.kube`
3. Add the `KUBECONFIG` environment variable to **System Variables** and have the path be `C:\Users\[MYUSER]\.kube\config`. Note that before I had it set as a **User Variable**.
4. Restart Docker from the **Docker for Window**'s reset tab in settings.
5. Restart Kubernetes Cluster from the **Docker for Window**'s reset tab in settings (you can do this a number of times).
6. Afterwards just wait for some time and **Kubernetes is running** should display

I hope this can help someone, this issue is a pain.

**Comment by MihaMarkic** [comment]
For me the @anwalkers tip to set fixed DNS Server IP did it.

**Comment by liuhewei** [comment]
> I found a lot of people, include me, have this problem, and the root cause is because the Kubernetes installation package cannot be downloaded. I wonder if they could allow users to download the Kubernetes for Windows package and install it manually, then enable it in the Docker's setting dialog.

Do you know the package contents or even the download link? Thanks.

**Comment by Euan-McVie** [comment]
For reference we found that the cause was due to our corporate DNS having a rogue localhost.domain.com entry that cause the issue under etcd-io/etcd#9070 to occur.

The workaround as per kubernetes/kubernetes#57709 to force set to 127.0.01 looks promising. Does anyone know if it is possible to override kubeadm config options as part of docker for windows???

**Comment by ManiacDC** [comment]
@Euan-McVie just found the same issue on our corporate network...

**Comment by dimz87** [comment]
> I was able to get this working even after restarting docker::
> 
> 1. Change DNS to fixed and use 8.8.8.8, this is within docker for window's settings
> 2. Remove the `.kube`
> 3. Add the `KUBECONFIG` environment variable to **System Variables** and have the path be `C:\Users\[MYUSER]\.kube\config`. Note that before I had it set as a **User Variable**.
> 4. Restart Docker from the **Docker for Window**'s reset tab in settings.
> 5. Restart Kubernetes Cluster from the **Docker for Window**'s reset tab in settings (you can do this a number of times).
> 6. Afterwards just wait for some time and **Kubernetes is running** should display
> 
> I hope this can help someone, this issue is a pain.

If you are in indonesia and using indihome as a connection, this issue is resolved using this approach and DNSCrypt help/VPN

**Comment by inech** [comment]
For me the only thing which helped was to to remove `C:\ProgramData\DockerDesktop\pki` folder and restart Docker. As described here https://github.com/docker/for-win/issues/3769#issuecomment-486046718

**Comment by akeyboardlife** [comment]
> I found a lot of people, include me, have this problem, and the root cause is because the Kubernetes installation package cannot be downloaded. I wonder if they could allow users to download the Kubernetes for Windows package and install it manually, then enable it in the Docker's setting dialog.

I find setting the proxy in Docker Desktop GUI help when you are behind the corporate firewall or GFW in China.

> http://docker.for.win.localhost:8080

I think it's possible to manually download the images, as shown in [here](https://github.com/AliyunContainerService/k8s-for-docker-desktop/blob/master/README_en.md). The repo used an mirror registry to bypass the GFW.

The images needed are listed below (Docker Desktop: 2.0.0.3 stable, kub: v1.10.11).

If you don't see this images in

> docker image ls

Then it must be the network problem, same as the error:

> "Node status error: Get https://localhost:6445/api/v1/nodes: EOF"

- k8s.gcr.io/kube-proxy-amd64                
	- v1.10.11            
		-7387003276ac
- k8s.gcr.io/kube-apiserver-amd64            
	- v1.10.11            
		-e851a7aeb6e8
- k8s.gcr.io/kube-controller-manager-amd64   
	- v1.10.11            
		-978cfa2028bf
- k8s.gcr.io/kube-scheduler-amd64            
	- v1.10.11            
		-d2c751d562c6
- docker/kube-compose-controller             
	- v0.4.12             
		-02a45592fbea
- docker/kube-compose-api-server             
	- v0.4.12             
		-0f92c77fa676
- k8s.gcr.io/etcd-amd64                      
	- 3.1.12              
		-52920ad46f5b
- k8s.gcr.io/k8s-dns-dnsmasq-nanny-amd64     
	- 1.14.8              
		-c2ce1ffb51ed
- k8s.gcr.io/k8s-dns-sidecar-amd64           
	- 1.14.8              
		-6f7f2dc7fab5
- k8s.gcr.io/k8s-dns-kube-dns-amd64          
	- 1.14.8              
		-80cc5ea4b547
- k8s.gcr.io/pause-amd64                     
	- 3.1                 
		-da86e6ba6ca1

If you got this error:

> "0/3 system pods running, waiting..."

I found switch to stable version help.

**Comment by yaodwwy** [comment]
### My solution:
upgrade 
docker Version to  **2.1.0.0**  
Channel : edge
**Docker 19.03.1**
problem solved!

**Comment by pwlodek** [comment]
I struggled with the same issue after upgrading from Docker Desktop on Windows, v2.0.0.0 to v2.1.0.0 what helped me was just to remove 'c:\ProgramData\DockerDesktop\pki' and reset Docker to defaults, didnt change DNS (i.e. left it on automatic), firewall was already configured properly.

**Comment by JerryLerman** [comment]
I struggled with this for the past month and none of the suggestions here worked. I just removed Webroot (due to the awful AV test results), switching to Windows Defender, and having done this, Kubernetes began working again, FWIW.

**Comment by rustedwizard** [comment]
Change DNS to fixed this issue
![Capture](https://user-images.githubusercontent.com/6314177/65399600-775b6780-dd72-11e9-803b-577f2ea41e9a.PNG)

**Comment by Lavaong** [comment]
I suggest you reinstall the Docker Desktop and set Docker Desktop's  Network to 8.8.8.8

**Comment by mdavid626** [comment]
This is still not solved. I am on 2.1.0.5 Docker.
- Change DNS to fixed and use 8.8.8.8, this is within docker for window's settings
- Remove the .kube config folder
- Add the KUBECONFIG environment variable to System Variables and have the path be C:\Users\[MYUSER]\.kube\config. Note that before I had it set as a User Variable.
- Remove c:\ProgramData\DockerDesktop\pki
- Disable Windows Firewall and Windows Defender
- Reset to factory defaults

I always get the same `"Cannot list nodes: Get https://kubernetes.docker.internal:6443/api/v1/nodes: EOF"`.

**Comment by mrbrazzi** [comment]
- [X] I have tried with the latest version of my channel (Stable)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: E37D09A7-F695-4F6A-9380-A544CF140879/20200127005241

### Expected behavior
Kubernetes start after is enabled

### Actual behavior
**Kubernetes failed to start**
![image](https://user-images.githubusercontent.com/1132397/73144810-6ea7d480-4077-11ea-801e-a34dda42a101.png)

### Information
  - Windows Version: Windows 10 Pro 1909 build 18363.592
  - Docker Desktop Version: 2.2.0.0 (42247)

### Steps to reproduce the behavior
  1. Go to Settings > Kubernetes and click on _[ ] Enable Kubernetes_

**Comment by phonzia** [comment]
> This is still not solved. I am on 2.1.0.5 Docker.
> 
> * Change DNS to fixed and use 8.8.8.8, this is within docker for window's settings
> * Remove the .kube config folder
> * Add the KUBECONFIG environment variable to System Variables and have the path be C:\Users[MYUSER].kube\config. Note that before I had it set as a User Variable.
> * Remove c:\ProgramData\DockerDesktop\pki
> * Disable Windows Firewall and Windows Defender
> * Reset to factory defaults
> 
> I always get the same `"Cannot list nodes: Get https://kubernetes.docker.internal:6443/api/v1/nodes: EOF"`.

I have the same problem here,

**Comment by gezhao2000** [comment]
> > This is still not solved. I am on 2.1.0.5 Docker.
> > 
> > * Change DNS to fixed and use 8.8.8.8, this is within docker for window's settings
> > * Remove the .kube config folder
> > * Add the KUBECONFIG environment variable to System Variables and have the path be C:\Users[MYUSER].kube\config. Note that before I had it set as a User Variable.
> > * Remove c:\ProgramData\DockerDesktop\pki
> > * Disable Windows Firewall and Windows Defender
> > * Reset to factory defaults
> > 
> > I always get the same `"Cannot list nodes: Get https://kubernetes.docker.internal:6443/api/v1/nodes: EOF"`.
> 
> I have the same problem here,

add a line in your local hosts
127.0.0.1 kubernetes.docker.internal

**Comment by hantsy** [comment]
@phonzia Got the same issues.

**Comment by Hemaprasanthi** [comment]
I fixed this by restarting the docker-desktop

**Comment by anitconsultantllc** [comment]
If you didn't uninstall or disable your anti-virus program before installing Docker Desktop on Windows 10 (Enterprise) and it's Kubernetes will not start, this may help you.  I've been troubleshooting this for over a week now and finally resolved it.  No matter how many times I uninstalled, then reinstalled Docker in ANY instance I ran into the same problem with Kubernetes never finally starting.  If I ONLY followed instructions well I could have avoided all these issues and I must say Docker does warn you (see image).  Unfortunately, they weren't very clear in there message about which pieces would fail but nonetheless (see warning below).
 
![image](https://user-images.githubusercontent.com/6926175/78324658-e512f800-753a-11ea-9239-713e2f1e3387.png)

In short, my anti-virus program put a lock on the host file so Docker could never update it and add this line, "127.0.0.1 kubernetes.docker.internal', in my local hosts file, "C:\Windows\System32\drivers\etc\hosts".

So either uninstall your anti-virus as warned or find the setting within your anti-virus program that prevents updates to your local host file and turn it off like I did with mine here.
![image](https://user-images.githubusercontent.com/6926175/78324944-cf520280-753b-11ea-886f-cc5b5662e787.png)

Then add a line in your hosts file, "C:\Windows\System32\drivers\etc\hosts", save it, re-open and verify it saved correctly(important).  This is important because on Windows 10 Enterprise you must open notepad in Administrator's mode by typing notepad in the run dialog box then when it's visible right-click on it and choose "Run As Administrator", in order to save the file.
![image](https://user-images.githubusercontent.com/6926175/78325525-71261f00-753d-11ea-9fb2-9082a4e85f5f.png)

     127.0.0.1 kubernetes.docker.internal

I tested the hosts file change by using a Powershell commandlet, "Resolve-DnsName", and could finally see that "kubernetes.docker.internal" was resolving.
![image](https://user-images.githubusercontent.com/6926175/78326183-5a80c780-753f-11ea-93ef-03cb81bfd9b5.png)

However, simply restarting Docker Desktop didn't resolve my issue.
![image](https://user-images.githubusercontent.com/6926175/78326233-7edca400-753f-11ea-8bc5-df4431d1ec41.png)

Instead, I had to follow a more thorough cleansing of Docker Desktop to get it working again.  So, I then followed [maddy10s](https://github.com/docker/for-mac/issues/2990#issuecomment-531656361), "Docker Reset Sequence", by following steps below.  Yes, even though his issue was originally reported as a MAC issue, not Windows, it worked for me and I experienced the same issues below.  

1. kubectl config delete-context docker-for-desktop (optional)
2. kubectl config delete-cluster docker-desktop (optional)
3. Reset to Factory defaults
4. Enable Kubernetes.
5. Here I waited for quite long time it was still showing installing kubernetes cluster.
6. Then I clicked on Run in background. Make sure cluster is installed by running kubectl config view
7. Restarted Docker
8. Now both Docker and Kubernetes are running

I hope this helps save you some time.  I hope the Docker Developers start reporting error's a bit more stringently both in their documentation and as their installer runs into these types of issues.  I mean really, couldn't a warning message not been thrown once you weren't able to update the hosts file locally? We've all written that code at some point as developers.  Good day (END OF SOAPBOX).

systeminfo
========
OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.18363 N/A Build 18363
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
Total Physical Memory:     16,307 MB
System Model:              Alienware 18
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 60 Stepping 3 GenuineIntel ~2801 Mhz

**Comment by Diluka** [comment]
47A10DD9-CCC7-4F86-A58C-3E1C80017E2E/20200422144701

**Comment by abdullahanwar** [comment]
> > > This is still not solved. I am on 2.1.0.5 Docker.
> > > 
> > > * Change DNS to fixed and use 8.8.8.8, this is within docker for window's settings
> > > * Remove the .kube config folder
> > > * Add the KUBECONFIG environment variable to System Variables and have the path be C:\Users[MYUSER].kube\config. Note that before I had it set as a User Variable.
> > > * Remove c:\ProgramData\DockerDesktop\pki
> > > * Disable Windows Firewall and Windows Defender
> > > * Reset to factory defaults
> > > 
> > > I always get the same `"Cannot list nodes: Get https://kubernetes.docker.internal:6443/api/v1/nodes: EOF"`.
> > 
> > 
> > I have the same problem here,
> 
> add a line in your local hosts
> 127.0.0.1 kubernetes.docker.internal

adding line in /etc/hosts didn't solve the issue, still showing,  "can't list nodes 

Had anyone able to solve the issue ??

**Comment by alamin-mahamud** [comment]
My K8S installation Journey on Mac  -

* stable version was giving me this issue
* then after reading through issues reinstalling to edge 
* tried to keep on eyes with this log
```
 pred='process matches ".*(ocker|vpnkit).*"
  || (process in {"taskgated-helper", "launchservicesd", "kernel"} && eventMessage contains[c] "docker")'
/usr/bin/log stream --style syslog --level=debug --color=always --predicate "$pred"
```
* checking my `/etc/hosts` it was fine.
```
##
# Host Database
#
# localhost is used to configure the loopback interface
# when the system is booting.  Do not change this entry.
##
127.0.0.1       localhost
255.255.255.255 broadcasthost
::1             localhost

# Added by Docker Desktop
# To allow the same kube context to work on the host and the container:
127.0.0.1 kubernetes.docker.internal
# End of section
```
* tried `Reset to Kubernetes Cluster` Did not work
* tried deleting `~/.kube/` or `~/.kube/config` did not work
* I had two contexts, tried to delete one or the other did not work 
```
docker-desktop
docker-for-desktop
```
* when i was doing `kubectl cluster-info`
i was getting nothing
* then again after resetting to factory defaults i lost hope and left as it is
* then after a day/two (38h) i was seeing  kubernetes master is running in `kubectl cluster-info`, but not `KubeDNS`
* the log changed now its trying to list 0/3 |  1/3 | 2/3 nodes. 
* then after a while the KubeDNS was running
```
KubeDNS is running at https://kubernetes.docker.internal:6443/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy
```
* tried removing the `.pki` directory
* no immediate results
* did `kubectl -n kube-system get pods`
```
😡  ~ kubectl -n kube-system get pods
NAME                                     READY   STATUS             RESTARTS   AGE
coredns-5644d7b6d9-j826z                 0/1     ImagePullBackOff   0          10m
coredns-5644d7b6d9-mq6hm                 0/1     ImagePullBackOff   0          10m
etcd-docker-desktop                      1/1     Running            0          9m40s
kube-apiserver-docker-desktop            1/1     Running            0          9m36s
kube-controller-manager-docker-desktop   1/1     Running            0          9m33s
kube-proxy-lwbnf                         0/1     ImagePullBackOff   0          10m
kube-scheduler-docker-desktop            1/1     Running            0          9m33s
```
* after a while k8s showing **GREEN**
![image](https://user-images.githubusercontent.com/11760918/81382420-314fea00-9130-11ea-91e1-ffd4a54c280c.png)

**Comment by Gsonovb** [comment]
have the same issue
  - Diagnostics ID:FB71B142-CA5F-48F8-BDC7-7AE4445E1394/20200512090644

The k8s of docker desktop does not work properly,

I tried to install minikube myself, no problem.



For some reasons, I can't directly access k8s.gcr.io, etc., so I can't confirm the installation,

Is there an alternative? thank you

**Comment by Karrrar** [comment]
I did every thing, delete all config file, reinstall docker desktop nothing works 
but
I fix it after i changed the host and port in WSL "P.S im new to kubernetes :)"
$ kubectl config set-cluster docker-desktop --server=https://kubernetes.docker.internal:6443
$ kubectl config set-context docker-desktop --cluster=docker-desktop
$ kubectl config use-context docker-desktop

Good luck

**Comment by kevinzhamg** [comment]
I don't know what to say. I nearly give up. I tried every method above, but no use.
I solved this issue by waiting for a very very long night (sleeping).

**Comment by Hemaprasanthi** [comment]
Did you try restarting your computer?

**Comment by kevinzhamg** [comment]
nope, just let it hanging on background. I changed DNS, deleted ./kube/config and restart Docker and so on. But still no luky. Then, it maybe fix the issue by itsefl. lmao

**Comment by hantsy** [comment]
Move to minikube and resolve my problem

**Comment by infolock** [comment]
This happens to me every time a new update for docker comes out.   Today is one of those days (new update).   Kubernetes is now stuck at "Starting...".   This issue has been around since 2017 from what I can tell from searches.

I'm cool with it If the issue is too difficult to fix, too problamatic to fix, or poses too many other issues to fix.  I'd just like to know that instead of finding myself searching fro this error from time to time =) haha. 

The solutions for me have been removing the `pki` folder (as mentioned above) or just doing a complete `Reset` (and thus, `re-install` of the containers) of Kubernetes.  Not sure what else one can do otherwise.
