### ISSUE TITLE
Docker desktop installation hangs in Windows 10 build 1903

### ISSUE THREAD

**Issue by softveda** [docker/for-win#3986]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Docker Desktop Installer should run and installer wizard should display to guide the installation.
### Actual behavior
Installer windows is displayed with a all white screen
### Information

  - Windows Version: 1903 (OS Build 18362.116)
  - Docker for Windows Version: 2.0.4.34207

### Steps to reproduce the behavior

  1. Run Docker Desktop Installer to upgrade (current docker version is 18.09.3, build 774a1f4)
  2. A white screen is shown in installer window and the wizard hangs
![installer](https://user-images.githubusercontent.com/1845906/58414098-c0015d80-80bd-11e9-9737-6f36290365ce.png)
  3. Also any screen displayed from Docker tray icon menu (e.g. About, Settings, etc.) also show the same white screen.

**Comment by PashCracken** [comment]
I have the same issue. I think it's just the GUI that is messed up. I pressed Enter a few times after waiting a bit and the installer seemed to complete and upgraded docker-desktop. But GUI in settings and everywhere are just blank Windows so I hope this is fixed soon.

**Comment by softveda** [comment]
Uninstall window was also white screen. After this I tried to install the Stable channel and this also hangs. It must be somthing to do with windows 10 build 1903 update as I had installed the stable channel in previous version of Windows 10 succesfully.
Is there a way to install and unistall from the command line without the wizard.

**Comment by ktmitton** [comment]
I had issues with updates/uninstalls too. My "fix" was to remove all the images manually from the c:/ProgramData/Docker/images (there was something that made me suspicious it was having trouble managing them), then I had no trouble.

**Comment by dmitry-weirdo** [comment]
Still the same problem.
This thread https://forums.docker.com/t/installer-for-windows-10-hangs-during-installation/63285 says to “Allow an app through Controlled folder access”, but I cannot access it due to my company laptop limitations :(
