### ISSUE TITLE
Upgrade to 2.1.0.0 hangs.

### ISSUE THREAD

**Issue by JD-4810** [docker/for-win#4460]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics

### Expected behavior
Docker upgrades to version 2.1.0.0.
### Actual behavior
The installer hangs on upgrading. Rebooted the system. Cleaned docker old installation by using the script from here : https://success.docker.com/article/how-to-completely-remove-docker-in-windows-10
Rebooted.
Real-time protection in windows security set to Off.
Ran the installer again. Still hanging. 
### Information
  - Windows Version: Windows 10 Enterprise Version 1809
  - Docker Desktop Version: 2.1.0.0

Error in event viewer : 
Faulting application name: com.docker.service, version: 2.1.0.36874, time stamp: 0xfaa31dea
Faulting module name: KERNELBASE.dll, version: 10.0.17763.475, time stamp: 0x69a188f0
Exception code: 0xe0434352
Fault offset: 0x0000000000039129
Faulting process id: 0x133c
Faulting application start time: 0x01d54cf15542ff02
Faulting application path: C:\Program Files\Docker\Docker\com.docker.service
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: d5fc5223-4364-4586-a27d-9b3cebb04ea7
Faulting package full name: 
Faulting package-relative application ID:

Application: com.docker.service
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.MissingMethodException
   at Docker.Core.Logger.Initialize(System.String, Docker.Core.ConsoleMode)
   at Docker.Service.DockerService..ctor()
   at Docker.Service.Program.Main()

**Comment by mikeparker** [comment]
Can you try 2.1.0.1 please, we fixed a few hanging issues there.

**Comment by ternag** [comment]
I'm experiencing the same issue.

2.1.0.0 hung when the installer was "Installing components"
2.1.0.1 gets 3 step further but hangs at "Deploying components: Run Docker Desktop backend service"

The same errors are still precent in the Event viewer, though the version of the com.docker.service is now "version: 2.1.0.37199", which is expected I guess.

**Comment by JD-4810** [comment]
> I'm experiencing the same issue.
> 
> 2.1.0.0 hung when the installer was "Installing components"
> 2.1.0.1 gets 3 step further but hangs at "Deploying components: Run Docker Desktop backend service"
> 
> The same errors are still precent in the Event viewer, though the version of the com.docker.service is now "version: 2.1.0.37199", which is expected I guess.

I got it working by cleaning my old docker components using the script from the link mentioned in the original message above and installing the version "Docker Community Edition 2.0.0.3 2019-02-15" from https://docs.docker.com/docker-for-windows/release-notes/ . Its just a workaround to continue my development. Will test the latest update over the weekend to see how it goes.

**Comment by ternag** [comment]
@JD-4810 Thx. 2.0.0.3 is working for me too.

**Comment by tushar-chauhan** [comment]
I am getting similar error for latest Docker Desktop installer for version 2.1.0.3.
Was anyone able to resolve this without downgrading the Decker Desktop version?

**Comment by DD-UX** [comment]
I'm also having the same issue trying to install `v2.1.0.5` on Windows 10. It frozes at `com.docker.service`.
Tried to remove it with [this Powershell script](https://success.docker.com/article/how-to-completely-remove-docker-in-windows-10). Any clue how to solve it in the meantime? Thanks

**Comment by DD-UX** [comment]
> I'm also having the same issue trying to install `v2.1.0.5` on Windows 10. It frozes at `com.docker.service`.
> Tried to remove it with [this Powershell script](https://success.docker.com/article/how-to-completely-remove-docker-in-windows-10). Any clue how to solve it in the meantime? Thanks

Been able to succeed it using newer version [here](https://docs.docker.com/docker-for-windows/edge-release-notes/)
