### ISSUE TITLE
Docker starts on login even when Start Docker when you log in" checkbox is cleared

### ISSUE THREAD

**Issue by josephby** [docker/for-win#476]
### Expected behavior
1. Start Windows
2. Log In
Docker should not start at log in. Docker icon should not be visible in the System Tray.

### Actual behavior
1. Start Windows
2. Log In

#### Results:
* Docker dialog box appears warning that Hyper-V is not installed
* Docker icon is visible in system tray. 
* If you right click the Docker icon and click "Settings," you will see that "Docker is running" and that the "Start Docker when you log in" checkbox is cleared.

### Information
**Output of `docker version`:**

```
Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Wed Jan 18 16:20:26 2017
 OS/Arch:      windows/amd64
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.25/version: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.
```

**Output of `docker info`:**

```
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.25/info: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

```
Edition: Windows 10 Pro
Version 1607
Running as standard user (i.e. non-Administrator)
```

### Steps to reproduce the behavior
  1. Start Windows
  2. Log In
  3. Right Click Docker Icon in System Tray
  4. Click "Settings"
  5. Clear "Start Docker when you log in" checkbox
  6. Restart Windows
  7. Log In

Re-opened after being originally opened as Docker issue [30423](https://github.com/docker/docker/issues/30423).

**Comment by simonferquel** [comment]
What version of Docker for Windows are you using ? I did not manage to reproduce the issue

**Comment by josephby** [comment]
1.13.0 (9795).
Also, note that the user I am using is *not* an Administrator.

**Comment by rneugeba** [comment]
I too can not reproduce it. I'm not running this as administrator either, though I am in the local admin group (you have to be in order to use Docker for Windows) but I start the app with my normal credentials.

Out of curiosity, why do you get the Hyper-V warning? Did you disable it?

**Comment by josephby** [comment]
I upgraded to 1.13.1 and can no longer reproduce this. Thanks!

**Comment by rneugeba** [comment]
Thanks for checking and closing. Glad it's fixed for you, though not sure why it was broken in the first place...

**Comment by MorganMarshall** [comment]
Running as admin, on a new install, docker is exhibiting the behavior listed above. Still starting up when "start docker when you log in" is unchecked.

**Comment by TheBelgarion** [comment]
i think the problem is:

during install, you are asked to run install as administrator or admin account.
all right are only applied to that account but not ur basic user account.

e.g. had the same problem, that my user account was not in docker-users because only my local admin account got moved into that group.

Now I also disabled "start when log in" but it still starts, my guess is that my user does not have the right to really change to starting of the docker service!?

I startet the services.msc with my Lokal Admin an set the docker service to start manually

**Comment by shawnshaddock** [comment]
How is this issue closed? I just installed the latest stable version of docker for windows and it's still exhibiting this behavior. I am not using the local admin account, but my user account is an admin.
I have the "Start Docker desktop when you log in" checkbox unchecked, but sure enough Docker starts every time I log in.

**Comment by shawnshaddock** [comment]
I found a workaround, if you do what @TheBelgarion says the docker service will not start, but the tray icon will still attempt to start and will give you an error message. To prevent this in Windows 10 click the Start menu, type and run "Startup tasks". Turn off Docker Desktop.

**Comment by jonaspetersorensen** [comment]
This bug was resolved in v1.13.1 and has now been reintroduced in latest stable version. For those of us that have multipurpose work machines it is pretty annoying.

**Comment by kbroomfield** [comment]
I am experiencing this issue in the latest stable build as well. I was able to resolve it using the "Startup Tasks" method that @shawnshaddock mentioned, but shouldn't have to do that.

**Comment by am11** [comment]
Used @shawnshaddock's method too to fix the behavior on my machine.
However, there is still a bug in implementation of this option:
:
![image](https://user-images.githubusercontent.com/3840695/50554099-3049b580-0cbd-11e9-9d2d-e72085400596.png)

```cmd
:: Windows Version (latest insider build)
C:\>ver
Microsoft Windows [Version 10.0.18305.1003]

:: docker version
C:\>docker --version
Docker version 18.09.0, build 4d60db4
```

could this issue or #3040 be reopened?

**Comment by GelosSnake** [comment]
Issue still part of docker.
Docker version 18.09.1, build 4c52b90
Only solved as @am11 suggested.

**Comment by albertolo** [comment]
HI, latest docker update, destroyed my docker installation, had to reset docker, and recreate my containers. 

Docker starts on login even when checkbox is cleared. 

Microsoft Windows [Version 10.0.17763.316]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\Users\alberto.lo>ver

Microsoft Windows [Version 10.0.17763.316]

C:\Users\alberto.lo>docker --version
Docker version 18.09.2, build 6247962

**Comment by CerosDev** [comment]
This issue should be reopen. Facing the same issue with 18.09.2

**Comment by Yivan** [comment]
Same should be reopened.
See this comment for problem description `https://forums.docker.com/t/docker-desktop-always-starts-although-disabled/63494/30`.

**Comment by elgabito** [comment]
Same issue, as-of current version installed today.

**Comment by ThiefMaster** [comment]
How the hell i this ridiculous issue not fixed after two years?

**Comment by mloskot** [comment]
Apparently, it can :-)
Meanwhile, have a look at this explanation of root of the problem and workaround https://github.com/docker/for-win/issues/2950#issuecomment-481758261

**Comment by am11** [comment]
Thanks! In my existing installation (which was up-to-date), I only had `Docker for Windows` registry key. So I uninstalled, then reinstalled and found that right after installation (and before running docker for the first time), it creates only obsolete registry key called `Docker for Windows`. After the first launch of Docker Desktop, it creates second key `Docker Desktop`. Ran a script which deletes the obsolete key safely:

```powershell
# ran in powershell
$path = 'HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Run'
if ((Get-Item $path).Property -contains 'Docker for Windows')
{
    Remove-ItemProperty -Path $path -Name 'Docker for Windows'
}
```

While the product was renamed from `Docker for Windows` to `Docker Desktop` back in January 2019 as per https://docs.docker.com/docker-for-windows/release-notes/#docker-community-edition-2002-2019-01-16, installer filename is still the same in past two releases: `Docker for Windows Installer.exe`. Couldn't locate the source code of installer, we can send a PR if it is open source? :)

**Comment by mloskot** [comment]
> Remove-ItemProperty -Path $path -Name 'Docker for Windows'

Shouldn't it rename to `Docker Desktop` ?

**Comment by am11** [comment]
Nope, only needs removal of extra legacy property. `Docker Desktop` prop is created and deleted when we toggle the auto-start setting:

![image](https://user-images.githubusercontent.com/3840695/57203052-f531f880-6fb4-11e9-8814-9104f1d24fd4.png)
