### ISSUE TITLE
Error occurs on Docker Desktop startup - wsl exited with code -1

### ISSUE THREAD

**Issue by wipash** [docker/for-win#5097]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 8CB3A15A-5A73-4C5A-8006-95B850987CA4/20191108065921

### Expected behavior
Docker Desktop starts successfully

### Actual behavior
Docker Desktop fails to start

```
wsl exited with code -1. Stderr is:


   at Docker.Backend.ContainerEngine.WslEngine.DeployDistro(String name, String source, String destinationDir)
   at Docker.Backend.ContainerEngine.WslEngine.DoStart(Settings settings, String daemonOptions, Credential credential)
   at Docker.Backend.ContainerEngine.WslEngine.Start(Settings settings, String daemonOptions, Credential credential, Boolean retry)
   at Docker.Backend.ContainerEngine.WslEngine.Start(Settings settings, String daemonOptions, Credential credential, Boolean retry)
   at Docker.Backend.ContainerEngine.WslEngine.Start(Settings settings, String daemonOptions, Credential credential)
   at Docker.Backend.BackendNamedPipeServer.<Run>b__8_2(Object[] args)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)
```

### Information

  - Windows Version: Windows 10 Pro Insider build 19018.vb_release.191101-1402
  - Docker Desktop Version: 2.1.5.0
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

This problem appeared with the update to 2.1.5.0. Prior to this it was working properly in WSL 2 mode.

Perhaps a WSL instance is missing?
```
PS > wsl -l -v
  NAME                   STATE           VERSION
* Ubuntu                 Stopped         2
  docker-desktop-data    Stopped         2
```

### Steps to reproduce the behavior

  1. Start Docker Desktop
  2. Task tray icon appears for a few seconds before turning red
  3. Error window appears

**Comment by wipash** [comment]
Solved by uninstalling, manually removing the docker-desktop-data WSL distribution, and then reinstalling.

**Comment by verglor** [comment]
I have exactly the same problem and I don't think the need for reinstalling wsl distribution is acceptable solution. There is a problem that should be investigated and solved correctly and this issue should be reopened

**Comment by stiangarthus** [comment]
Same problem here....

**Comment by Estyn** [comment]
I also have the same problem.

**Comment by Amitie10g** [comment]
I'm running **Docker 2.1.6.1**, and I still have the same issue. No WSL2 instance were created, and I've installed Ubuntu from the Microsoft Store and works perfectly.

**Comment by luisgilg** [comment]
I solved starting manually the distro
`wsl -d docker-desktop-data`
then restarting Docker Desktop
