### ISSUE TITLE
Installation fails: The Server service is not started.

### ISSUE THREAD

**Issue by markbaas** [docker/for-win#5150]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [-] I have uploaded Diagnostics
Docker isn't even installed.

### Expected behavior
Docker Edge 2.1.5.0 installs
### Actual behavior
Crashes
### Information
Problem appears only on edge since wsl2 backend was implemented. WSL2 Tech preview worked fine.

  - Windows Version: Windows Build 19023
  - Docker Desktop Version: 2.1.5.0

### Steps to reproduce the behavior
Start the installer.

https://docs.docker.com/docker-for-windows/troubleshoot/
![image](https://user-images.githubusercontent.com/1153495/68950748-13c34880-07bd-11ea-9e8a-1b77e20c9f86.png)

### Log
The Server service is not started.

   at System.DirectoryServices.DirectoryEntry.RefreshCache()
   at System.DirectoryServices.AccountManagement.PrincipalContext.DoMachineInit()
   at System.DirectoryServices.AccountManagement.PrincipalContext.Initialize()
   at System.DirectoryServices.AccountManagement.PrincipalContext.get_QueryCtx()
   at System.DirectoryServices.AccountManagement.Principal.FindByIdentityWithTypeHelper(PrincipalContext context, Type principalType, Nullable`1 identityType, String identityValue, DateTime refDate)
   at System.DirectoryServices.AccountManagement.Principal.FindByIdentityWithType(PrincipalContext context, Type principalType, String identityValue)
   at System.DirectoryServices.AccountManagement.GroupPrincipal.FindByIdentity(PrincipalContext context, String identityValue)
   at CommunityInstaller.CreateGroupAction.<DoAsync>b__33_0()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at CommunityInstaller.InstallWorkflow.<HandleD4WPackage>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<ProcessAsync>d__24.MoveNext()

**Comment by HabibMAALEM** [comment]
Same issue with Docker Desktop 2.2.0

![Error Docker](https://user-images.githubusercontent.com/6323478/72879718-bdfba700-3cfd-11ea-92ce-cadb9f8753cc.PNG)

**Comment by mat007** [comment]
Thanks for reporting this, could you guys look in the Windows Event Viewer to see if any error is being reported by the `DockerService`?

![image](https://user-images.githubusercontent.com/2386884/72886413-12a51f00-3d0a-11ea-8e07-3ae8cd3590fd.png)

**Comment by jdanas** [comment]
not really sure what happen tho i try to install it also to my desktop im not running windows server. running in windows 10  build 18362 and hyper-v enabled.  and still cannot install docker desktop. thank you!

**Comment by devanshujoshi** [comment]
Any Update on this issue. It seems to be consistent for me.

**Comment by mat007** [comment]
@devanshujoshi do you have anything showing up in the Windows Event Viewer?

**Comment by jdanas** [comment]
how can i install this on my desktop instead? not running a windows server on my side. i want to use docker for windows in localhost development thank you

**Comment by nabilgasri** [comment]
Hello,

I got the same error here.
In the event log I have the following error 10016 :

"The application-specific permission settings do not grant Local Activation permission for the COM Server application with CLSID
{D63B10C5-BB46-4990-A94F-E40B9D520160}
and APPID
{9CA88EE3-ACB7-47C8-AFC4-AB702511C276}
to the user ************* SID (*************) from address LocalHost (using LRPC) running in the application container Unavailable SID (Unavailable). This security permission can be modified using the Component Services administrative tool.
"
Below a link from Microsoft that explains the error
https://support.microsoft.com/en-us/help/4022522/dcom-event-id-10016-is-logged-in-windows

**Comment by AnicetR** [comment]
Exactly the same issue here : 

`Le service Serveur n’a pas démarré.

   à System.DirectoryServices.DirectoryEntry.RefreshCache()
   à System.DirectoryServices.AccountManagement.PrincipalContext.DoMachineInit()
   à System.DirectoryServices.AccountManagement.PrincipalContext.Initialize()
   à System.DirectoryServices.AccountManagement.PrincipalContext.get_QueryCtx()
   à System.DirectoryServices.AccountManagement.Principal.FindByIdentityWithTypeHelper(PrincipalContext context, Type principalType, Nullable`1 identityType, String identityValue, DateTime refDate)
   à System.DirectoryServices.AccountManagement.Principal.FindByIdentityWithType(PrincipalContext context, Type principalType, String identityValue)
   à System.DirectoryServices.AccountManagement.GroupPrincipal.FindByIdentity(PrincipalContext context, String identityValue)
   à CommunityInstaller.CreateGroupAction.<DoAsync>b__33_0()
   à System.Threading.Tasks.Task.Execute()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   à CommunityInstaller.InstallWorkflow.<HandleD4WPackageAsync>d__29.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à CommunityInstaller.InstallWorkflow.<ProcessAsync>d__24.MoveNext()`


Did someone found a workaround ?

**Comment by mat007** [comment]
@nabilgasri after reading the information at the link you provided I’m not sure this is the culprit:
> These events can be safely ignored because they do not adversely affect functionality and are by design. This is the recommend action for these events.

Is there anything else in the Event Viewer?

**Comment by nabilgasri** [comment]
@mat007 
It was the only event int eventviewer
The link says it can be ignored but I think that the Docker Installer is trying to access the User/Group information from the entreprise directory which is forbidden and this generates the 10016 error event.

**Comment by nabilgasri** [comment]
By the way the installation of the version 2.1.0.5 works fine https://download.docker.com/win/stable/40693/Docker%20Desktop%20Installer.exe

**Comment by vgmello** [comment]
I had the same issue, the problem was because the windows service "**Server**" was disabled. Enabling and starting it up fixed for me. 
![image](https://user-images.githubusercontent.com/4777793/73533506-edee2d00-4416-11ea-8026-b7519db53864.png)

**Comment by nabilgasri** [comment]
thanks @vgmello this helps installing the 2.2.0 version

**Comment by mat007** [comment]
Nice catch @vgmello !
I’ll create an internal ticket to see how we can fix the service dependencies.
Thanks!

**Comment by SumanthShetty** [comment]
Hi @vgmello  ,

It may be elementary of me but where can i find this setting ?

**Comment by vgmello** [comment]
> Hi @vgmello ,
> 
> It may be elementary of me but where can i find this setting ?

Press Windows + R, type services.msc, look for a service with a name of **Server** and try to start it. If it is disabled you will need to enable it first by going to the service properties and changing the startup type from disabled to Manual or Automatic

Detailed Instructions: https://computerstepbystep.com/server-service-windows-7.html (this very similar on Win10)

**Comment by Wyulliam** [comment]
> > Hi @vgmello ,
> > It may be elementary of me but where can i find this setting ?
> 
> Press Windows + R, type services.msc, look for a service with a name of **Server** and try to start it. If it is disabled you will need to enable it first by going to the service properties and changing the startup type from disabled to Manual or Automatic
> 
> Detailed Instructions: https://computerstepbystep.com/server-service-windows-7.html (this very similar on Win10)

Additional bonus question: Why this Server service only appears on the services.msc but not on the Task Manager service tab?

**Comment by mryserb** [comment]
With the release of Docker for Desktop 2.2.x the Server service (a.k.a. lanmanserver) shouldn't be needed anymore to my knowledge (see release notes). The installer should then not try to start that service, ift it's not needed. Some companys prevent from using lanmanserver, so it would be of great help if it would be removed from the installer

**Comment by mknarula** [comment]
i am facing the same error? Any resolutions?

**Comment by mat007** [comment]
@mknarula we have fixed this in our master branch, it will be available in the next Edge release in a few days (and much later in Stable).
When I say fixed it’s actually that we’re now checking for the Server service in a prerequisite step in the installer and correctly report an error if we fail to start it.

A workaround has been explained in this issue: manually start the service if need before running the installer.

**Comment by gillesdouaire** [comment]
The fix actually broke our ability to install Docker Desktop Edge. On my machine, the server Service is enabled and runs, but it's blocking the install nonetheless.

![image](https://user-images.githubusercontent.com/29061201/75776611-4d936d00-5d22-11ea-9996-b5053011fe5b.png)

I don't understand why you added this sort of validation. When HyperV is not enabled, you ask permission for enabling it at install time, why can't the same behaviour be applied here?

**Comment by mat007** [comment]
> The fix actually broke our ability to install Docker Desktop Edge. On my machine, the server Service is enabled and runs, but it's blocking the install nonetheless.

Is this during an update? Is there an error containing `Failed to run prerequisite service` in either `%LOCALAPPDATA%\Docker\Log.txt` or `%LOCALAPPDATA%\Docker\install-log.txt` around the time of the failed install?

> I don't understand why you added this sort of validation. When HyperV is not enabled, you ask permission for enabling it at install time, why can't the same behaviour be applied here?

That’s what we do here: we check that service is running and if not try to run it and if that fails then you’ll get the error you’re seeing.
We added the check as a prerequisite because not having that service running was failing the install later during the process anyway albeit in a less clean manner.

It seems to code isn’t as robust as we thought it was, I’ll be happy to get some help getting to the bottom of this issue.
Thanks!

**Comment by gillesdouaire** [comment]
Thanks. This indeed happened during an install. In the logs:

`[07:34:36.851] [InstallWorkflow] Checking prerequisites
[07:34:37.257] [OsVersionPreRequisite] Failed to run prerequisite service: System.AggregateException: One or more errors occurred. ---> CommunityInstaller.Win32ExceptionWithContext: Failed to open service: Access is denied
   at CommunityInstaller.ServicePreRequisite.<EnsureServiceRunningAsync>d__14.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at CommunityInstaller.ServicePreRequisite.get_IsFullFilled()
---> (Inner Exception #0) CommunityInstaller.Win32ExceptionWithContext (0x80004005): Failed to open service: Access is denied
   at CommunityInstaller.ServicePreRequisite.<EnsureServiceRunningAsync>d__14.MoveNext()<---

[07:34:37.267] [InstallWorkflow] Prerequisite failed: Docker Desktop requires the Server service to be enabled.`

**Comment by davidovich** [comment]
I re-downloaded Docker Desktop Installer.exe and executed as Administrator, I still get the error. Same log as @gillesdouaire. The Server service is running. The edge version 2.2.2.0 is broken for me.

**Comment by mat007** [comment]
What happens if you run this in a administrator cmd shell?
```
sc query lanmanserver
```

**Comment by davidovich** [comment]
```
C:\WINDOWS\system32>sc query lanmanserver

SERVICE_NAME: lanmanserver
        TYPE               : 30  WIN32
        STATE              : 4  RUNNING
                                (STOPPABLE, NOT_PAUSABLE, IGNORES_SHUTDOWN)
        WIN32_EXIT_CODE    : 0  (0x0)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0
```

**Comment by mat007** [comment]
Here is an internal build for you guys to try, we have limited the access to services with only what was needed (like query and start) instead of «everything»: https://download-stage.docker.com/win/edge/43381/Docker%20Desktop%20Installer.exe
Let me know if that makes a difference?
Thanks for you help!

**Comment by davidovich** [comment]
@mat007 The version 43381 you have provided allowed me to install. I did not have a Windows machine to test yesterday.

**Comment by mat007** [comment]
Thanks @davidovich that’s great news!

**Comment by gillesdouaire** [comment]
back from vacations - I confirm, it works for me too. thanks!

**Comment by stephen-turner** [comment]
This is now released in Edge 2.2.3.0, so I'm going to close this ticket.

**Comment by repo-gsr** [comment]
@vgmello 

You are am facing same issue.

issue got resolved by starting the Server Service.

Thanks a lot and you saved my time...

**Comment by wjpdeveloper** [comment]
thanks @vgmello , it work.

**Comment by sol-idsnake** [comment]
Not sure if this helps, but the problem persists with Docker Desktop 2.3.0.2 (45183) on Win 10 Pro 1909.

Ran it for the first time and got same error as OP: ```The Server service is not started```. I'm on a nearly fresh install of Windows 10. 

[@vgmello](https://github.com/docker/for-win/issues/5150#issuecomment-580683869) 's answer does work, and I found that the service needs to be set to 'manual', at least. Having the Server service on ```disabled``` will cause the Installer to fail. 

Even after activating the service, the installer still freezes at times. I noticed that the Installer continues running if you right-click the taskbar entry and select close. Even if you don't confirm whether you want to quit the Installer continues its job. 

Running the installer with Admin rights and running the Server service seems to be the golden ratio. Worked without problems.

**Comment by HongChongxi** [comment]
I am also getting the same error when installing (as Administrator) the Stable release of Docker for Windows. I am using Windows 10 (Build: 19041). Can anybody advise?

![image](https://user-images.githubusercontent.com/52709640/84623343-a70a5b00-af11-11ea-8d92-c631e94afaf5.png)
