### ISSUE TITLE
Unexpected API error (HTTP code 502): Bad response from Docker engine

### ISSUE THREAD

**Issue by benedict-odonovan** [docker/for-win#6191]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 2DFBB5B6-D613-45B4-B759-05D5E0D65EA1/20200401101227

### Expected behavior
Docker-compose runs continuously.
### Actual behavior
After some seemingly random period of time (normally longer than 10 minutes) all running docker containers fail with "Unexpected API error (HTTP code 502): Bad response from Docker engine". 

Attempting to call docker-compose again returns "open \\.\pipe\docker_engine_linux: The system cannot find the file specified."

To run docker-compose again I need to restart docker from the tray.
### Information

  - Windows Version: Windows Server 2019 Standard
  - Docker Desktop Version: 2.2.0.4 (43472)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: Yes, inside a VMWare 7,1 VM

This is on a fresh install of the latest stable Docker Desktop on a newly provisioned VM inside VMWare. It happens every time I run docker-compose up, with the problem occurring after different periods of time.

Looking at the logs I've noticed that every crash is accompanied by:

```
[11:03:48.026][VpnKitBridge      ][Info   ] time="2020-04-01T11:03:48+01:00" msg="Multiplexer main loop failed with The network connection was aborted by the local system."
[11:03:48.027][VpnKitBridge      ][Info   ] time="2020-04-01T11:03:48+01:00" msg="Event trace:"
...
...
[11:03:48.253][VpnKitBridge      ][Info   ] time="2020-04-01T11:03:48+01:00" msg="End of state dump"
[11:03:48.253][VpnKitBridge      ][Info   ] time="2020-04-01T11:03:48+01:00" msg="error CloseWrite to: file has already been closed"
[11:03:48.257][GoBackendProcess  ][Warning] time="2020-04-01T11:03:48+01:00" msg="Resyncer ports: while watching docker events: unexpected EOF"
[11:03:48.258][GoBackendProcess  ][Info   ] time="2020-04-01T11:03:48+01:00" msg="disconnected data connection: multiplexer is offline"
[11:03:48.258][GoBackendProcess  ][Error  ] time="2020-04-01T11:03:48+01:00" msg="error accepting subconnection: accept: multiplexer is not running"
[11:03:48.258][GoBackendProcess  ][Info   ] time="2020-04-01T11:03:48+01:00" msg="established connection to vpnkit-forwarder"
[11:03:48.259][GoBackendProcess  ][Info   ] time="2020-04-01T11:03:48+01:00" msg="listening on unix:\\\\.\\pipe\\dockerVpnkitData for data connection"
[11:03:48.259][GoBackendProcess  ][Warning] time="2020-04-01T11:03:48+01:00" msg="Resyncer volumes: while watching docker events: unexpected EOF"
[11:03:48.259][VpnKitBridge      ][Info   ] time="2020-04-01T11:03:48+01:00" msg="error copying: file has already been closed"
[11:03:48.259][VpnKitBridge      ][Info   ] time="2020-04-01T11:03:48+01:00" msg="error CloseWrite to: An existing connection was forcibly closed by the remote host."
[11:03:48.259][VpnKitBridge      ][Info   ] time="2020-04-01T11:03:48+01:00" msg="error copying: file has already been closed"
[11:03:48.259][VpnKitBridge      ][Info   ] time="2020-04-01T11:03:48+01:00" msg="error CloseWrite to: An existing connection was forcibly closed by the remote host."
[11:03:48.260][VpnKit            ][Error  ] vpnkit.exe: Vmnet.Server.listen: read EOF so closing connection
[11:03:48.260][VpnKitBridge      ][Info   ] time="2020-04-01T11:03:48+01:00" msg="error copying: file has already been closed"
[11:03:48.260][VpnKit            ][Info   ] vpnkit.exe: Vmnet.Server.disconnect
[11:03:48.260][VpnKit            ][Info   ] vpnkit.exe: Vmnet.Server.listen returning Ok()
[11:03:48.260][VpnKit            ][Info   ] vpnkit.exe: TCP/IP stack disconnected
```

For a copy of the logs with the state dump included: [log sample.txt](https://github.com/docker/for-win/files/4414489/log.sample.txt)

### Steps to reproduce the behavior

Docker-compose:
```
version: "3.3"
services:
  rabbitmq:
    image: rabbitmq:3.8-management
    hostname: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - somenetwork

networks:
  somenetwork:
    driver: bridge

```

  1. Run `docker-compose up`
  2. Wait 10-40 minutes

**Comment by vytautas-petrikas** [comment]
Same issue occurs on versions 2.2.0.5 and 2.3.0.1 on Windows 10 Enterprise build 17763.

**Comment by robodude666** [comment]
Same issue on 2.2.0.5 (43884) on Windows 10 Enterprise 1809 (Build 17763.1158).

Once an ~hour docker will crash, requiring a restart of Docker Engine.

Diagnostics ID: `E2DC3A5C-A58E-4CB1-BF50-95F0A93B9D80/20200509174318`

```
λ docker version
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:23:10 2020
 OS/Arch:           windows/amd64
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:29:16 2020
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by robodude666** [comment]
Seems to have been fixed as part of 2.3.0.2 (45183); looks like there was a leak?

**Comment by mat007** [comment]
Maybe it was #5841?

**Comment by robodude666** [comment]
@mat007 I thought so... but nope, issue still exists :(. Just much less frequent.

**Comment by vytautas-petrikas** [comment]
Just tested with latest stable build and this issue is still relavant

**Comment by qootec** [comment]
Same here on:
* Engine 19.03.8
* Compose 1.25.5
* Windows 10.0.17763

Environment:
5 Ubuntu containers, quite busy with network traffic between them and to the cloud.

Observed behavior:
All services suddenly drop:
Unexpected API error for <<<containername>>> (HTTP code 502)
Response body:
Bad response from Docker engine

Commands such as docker ps are unable to contact docker daemon.
Restarting docker allows me to restart my docker-compose configuration.

I see this error mentioned already in 2017, so I guess this is a regression?

Thanks,
Johan

**Comment by mlilienthal** [comment]
Similar problem here:

Environment:

- tensorflow/tensorflow:latest-py3-jupyter used as a devcontainer in visual studio code.
- Windows 10 17763
`Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:43:18 2020
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:49:27 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
`

Behavior:

- Container does not respond few minutes after starting some longer running task (in this case model training).
- Resources (CPU/memory) seem not to be an issue here 
- VSCode looses connection to container.
- Commands are unable to contact Docker Server, a restart of docker is required.

Logs:

`[13:25:36.962][VpnKitBridge      ][Info   ] error copying: file has already been closed
[13:25:36.963][VpnKitBridge      ][Info   ] error copying: file has already been closed
[13:25:36.963][VpnKitBridge      ][Info   ] error CloseWrite to: An existing connection was forcibly closed by the remote host.
[13:25:36.963][VpnKitBridge      ][Info   ] error copying: file has already been closed
[13:25:36.963][VpnKitBridge      ][Info   ] error CloseWrite to: An existing connection was forcibly closed by the remote host.
[13:25:36.963][VpnKitBridge      ][Info   ] error dialing remote endpoint filesystem-event: connection refused
[13:25:36.963][VpnKitBridge      ][Info   ] error CloseWrite to: An existing connection was forcibly closed by the remote host.
[13:25:36.963][ApiProxy          ][Info   ] proxy >> GET /v1.40/exec/a46ae14d73698aa255d61ec300bd98b0ff1b8cbb13001f2e01fa9130752de06f/json\n
[13:25:36.963][ApiProxy          ][Info   ] proxy >> GET /v1.40/exec/946927957a2896112735619629659018ba60e9465c11745a8f5eb7c0f52f6e50/json\n
[13:25:36.963][ApiProxy          ][Info   ] error reading response from Docker:  unexpected EOF
[13:25:36.963][VpnKitBridge      ][Info   ] error dialing remote endpoint docker: connection refused
[13:25:36.964][ApiProxy          ][Info   ] proxy >> GET /v1.40/exec/b30a2b4023d93e7dd0b7ab927298894590690f7011d83b0c29fcbe3a7e4be207/json\n
[13:25:36.964][VpnKitBridge      ][Info   ] error dialing remote endpoint docker: connection refused
[13:25:36.964][ApiProxy          ][Info   ] error reading response from Docker:  unexpected EOF
[13:25:36.965][ApiProxy          ][Info   ] proxy >> GET /v1.40/exec/d7830556aa49d70d164457174d69b6d4829bfd5ea316456d2a56ab2d46fdd1e6/json\n
[13:25:36.965][VpnKitBridge      ][Info   ] error dialing remote endpoint docker: connection refused
[13:25:36.965][ApiProxy          ][Info   ] error reading response from Docker:  unexpected EOF
[13:25:36.967][ApiProxy          ][Info   ] proxy << POST /v1.40/exec/a46ae14d73698aa255d61ec300bd98b0ff1b8cbb13001f2e01fa9130752de06f/start (3h19m15.7503046s)\n
[13:25:36.959][GoBackendProcess  ][Info   ] disconnected data connection: multiplexer is offline
[13:25:36.968][GoBackendProcess  ][Warning] Resyncer volumes: while watching docker events: unexpected EOF
[13:25:36.968][GoBackendProcess  ][Error  ] error accepting subconnection: accept: multiplexer is not running
[13:25:36.968][ApiProxy          ][Info   ] proxy << POST /v1.40/exec/b30a2b4023d93e7dd0b7ab927298894590690f7011d83b0c29fcbe3a7e4be207/start (3h19m16.7793677s)\n
[13:25:36.968][GoBackendProcess  ][Info   ] established connection to vpnkit-forwarder
[13:25:36.968][GoBackendProcess  ][Info   ] listening on unix:\\\\.\\pipe\\dockerVpnkitData for data connection
[13:25:36.968][GoBackendProcess  ][Warning] Resyncer ports: while watching docker events: unexpected EOF
[13:25:36.969][ApiProxy          ][Info   ] proxy << POST /v1.40/exec/d7830556aa49d70d164457174d69b6d4829bfd5ea316456d2a56ab2d46fdd1e6/start (3h19m17.2523595s)\n
[13:25:36.973][VpnKitBridge      ][Info   ] error dialing remote endpoint docker: connection refused
[13:25:36.973][ApiProxy          ][Info   ] error reading response from Docker:  unexpected EOF
[13:25:36.974][ApiProxy          ][Info   ] proxy << POST /v1.40/exec/946927957a2896112735619629659018ba60e9465c11745a8f5eb7c0f52f6e50/start (3h19m15.7572911s)\n
[13:25:37.302][VpnKitBridge      ][Info   ] Proxy wsl2-bootstrap-expose-ports: context is done before proxy is established
[13:25:37.303][VpnKitBridge      ][Info   ] Error: accept: multiplexer is not running
[13:25:37.303][VpnKitBridge      ][Fatal  ] accept: multiplexer is not running
[13:25:37.341][VpnKitBridge      ][Error  ] Process died`

**Comment by ScottGuymer** [comment]
I'm seeing the same issue here. I often see it during `docker build` tasks in addition to running containers via `docker-compose`. 

I have captured the logs of it running and then crashing. I see a lot of `VpnKitBridge` traffic in the logs. I am using a VPN but the connection seems to be stable enough.

These seem to eb the first lines that indicate an issue after everthing is going ok
```
[07:50:02.439][VpnKitBridge      ][Info   ] Multiplexer main loop failed with The network connection was aborted by the local system.
[07:50:02.440][VpnKitBridge      ][Info   ] Event trace:
[07:50:02.440][VpnKitBridge      ][Info   ] send  366 Window 179256422
[07:50:02.440][VpnKitBridge      ][Info   ] send  3384 Window 178392613
[07:50:02.440][VpnKitBridge      ][Info   ] recv  37 Data length 250
[07:50:02.440][VpnKitBridge      ][Info   ] recv  37 Data length 214
[07:50:02.440][VpnKitBridge      ][Info   ] send  264729 Open Multiplexed Unix:docker
[07:50:02.440][VpnKitBridge      ][Info   ] send  264729 Window 65536
[07:50:02.440][VpnKitBridge      ][Info   ] recv  264729 Window 65536
[07:50:02.440][VpnKitBridge      ][Info   ] send  264729 Data length 4
[07:50:02.440][VpnKitBridge      ][Info   ] send  264729 Data length 252
[07:50:02.440][VpnKitBridge      ][Info   ] recv  37 Data length 185
[07:50:02.440][VpnKitBridge      ][Info   ] recv  37 Data length 177
[07:50:02.440][VpnKitBridge      ][Info   ] recv  37 Data length 151
[07:50:02.440][VpnKitBridge      ][Info   ] recv  264729 Data length 7151
[07:50:02.440][VpnKitBridge      ][Info   ] send  264729 Shutdown
[07:50:02.440][VpnKitBridge      ][Info   ] recv  264729 Shutdown
[07:50:02.440][VpnKitBridge      ][Info   ] recv  264729 Close
[07:50:02.440][VpnKitBridge      ][Info   ] send  264729 Close
[07:50:02.440][VpnKitBridge      ][Info   ] close 264729 -> Unix:docker
```

Then after a while of that i get this
```
[07:50:02.459][ApiProxy          ][Info   ] error reading response from Docker:  unexpected EOF
[07:50:02.459][ApiProxy          ][Info   ] error streaming response body from Docker:  unexpected EOF
[07:50:02.459][VpnKitBridge      ][Info   ] recv  264762 Data length 8652
[07:50:02.459][VpnKitBridge      ][Info   ] send  264762 Shutdown
[07:50:02.459][VpnKit            ][Error  ] vpnkit.exe: Vmnet.Server.listen: read EOF so closing connection
[07:50:02.460][VpnKit            ][Info   ] vpnkit.exe: Vmnet.Server.disconnect
[07:50:02.461][VpnKit            ][Info   ] vpnkit.exe: Vmnet.Server.listen returning Ok()
[07:50:02.461][VpnKit            ][Info   ] vpnkit.exe: TCP/IP stack disconnected
[07:50:02.460][ApiProxy          ][Info   ] error closing response body from Docker:  unexpected EOF
[07:50:02.459][VpnKitBridge      ][Info   ] recv  264762 Shutdown
[07:50:02.461][ApiProxy          ][Info   ] proxy << GET /v1.38/events?filters=%7B%22label%22%3A+%5B%22com.docker.compose.project%3Dincharge%22%2C+%22com.docker.compose.oneoff%3DFalse%22%5D%7D (13h50m26.8338805s)\n
[07:50:02.461][VpnKitBridge      ][Info   ] recv  264762 Close
[07:50:02.461][ApiProxy          ][Info   ] Cancel connection...
[07:50:02.461][VpnKitBridge      ][Info   ] send  264762 Close
[07:50:02.461][ApiProxy          ][Warning] ignored error: The handle is invalid.
[07:50:02.461][VpnKitBridge      ][Info   ] close 264762 -> Unix:docker
[07:50:02.460][GoBackendProcess  ][Warning] Resyncer volumes: while watching docker events: unexpected EOF
[07:50:02.461][VpnKitBridge      ][Info   ] send  264763 Open Multiplexed Unix:docker
[07:50:02.461][VpnKitBridge      ][Info   ] send  264763 Window 65536
[07:50:02.461][VpnKitBridge      ][Info   ] recv  37 Data length 162
[07:50:02.461][VpnKitBridge      ][Info   ] recv  37 Data length 143
[07:50:02.461][GoBackendProcess  ][Info   ] disconnected data connection: multiplexer is offline
[07:50:02.461][VpnKitBridge      ][Info   ] recv  37 Data length 502
[07:50:02.461][GoBackendProcess  ][Error  ] error accepting subconnection: accept: multiplexer is not running
```
Then going to this
```
[07:50:02.462][VpnKitBridge      ][Info   ] error copying: file has already been closed
[07:50:02.462][VpnKitBridge      ][Info   ] error CloseWrite to: An existing connection was forcibly closed by the remote host.
[07:50:02.462][VpnKitBridge      ][Info   ] error copying: file has already been closed
[07:50:02.462][VpnKitBridge      ][Info   ] error CloseWrite to: An existing connection was forcibly closed by the remote host.
[07:50:02.462][VpnKitBridge      ][Info   ] error copying: file has already been closed
[07:50:02.462][VpnKitBridge      ][Info   ] error CloseWrite to: An existing connection was forcibly closed by the remote host.
[07:50:02.462][VpnKitBridge      ][Info   ] error dialing remote endpoint filesystem-event: connection refused
[07:50:02.490][ApiProxy          ][Info   ] proxy >> POST /v1.38/containers/0cfadb0cd911de0652c233ebefa03cae77d557b4a9a81c327810c8228cda9ad1/wait\n
[07:50:02.490][VpnKitBridge      ][Info   ] error dialing remote endpoint docker: connection refused
[07:50:02.490][ApiProxy          ][Info   ] error reading response from Docker:  unexpected EOF
[07:50:02.491][ApiProxy          ][Info   ] proxy >> POST /v1.38/containers/c636333bfd9019f2700f9d05e0209855872c10fb92a486aa68a989a87b4ca00d/wait\n
[07:50:02.491][VpnKitBridge      ][Info   ] error dialing remote endpoint docker: connection refused
[07:50:02.491][ApiProxy          ][Info   ] error reading response from Docker:  unexpected EOF
[07:50:02.491][ApiProxy          ][Info   ] Cancel connection...
[07:50:02.491][ApiProxy          ][Warning] ignored error: The handle is invalid.
[07:50:02.492][ApiProxy          ][Info   ] proxy >> POST /v1.38/containers/94a2c5b6f69393d9a11e9968053e9861fd784e60988db189dfa477227641c4d6/wait\n
[07:50:02.492][VpnKitBridge      ][Info   ] error dialing remote endpoint docker: connection refused
[07:50:02.492][ApiProxy          ][Info   ] error reading response from Docker:  unexpected EOF
[07:50:02.494][ApiProxy          ][Info   ] proxy >> POST /v1.38/containers/0e228895cd888dfc6e84dfaa64fd0b9d4d72596d3166c6a0daa836c8b4d7ba5c/wait\n
[07:50:02.494][VpnKitBridge      ][Info   ] error dialing remote endpoint docker: connection refused
[07:50:02.495][ApiProxy          ][Info   ] error reading response from Docker:  unexpected EOF
[07:50:02.497][ApiProxy          ][Info   ] proxy >> POST /v1.38/containers/92836eff091e2d047ee107130b29fa5d77b998bda4d761976856dda2705193ab/wait\n
[07:50:02.497][ApiProxy          ][Info   ] proxy >> POST /v1.38/containers/c0f2340e6bb319ccd5cc918de58ce4b3f6388169da83acbf04c8c61bab8627e9/wait\n
[07:50:02.497][VpnKitBridge      ][Info   ] error dialing remote endpoint docker: connection refused
[07:50:02.498][ApiProxy          ][Info   ] error reading response from Docker:  unexpected EOF
[07:50:02.498][ApiProxy          ][Info   ] Cancel connection...
[07:50:02.498][ApiProxy          ][Warning] ignored error: The handle is invalid.
[07:50:02.498][ApiProxy          ][Info   ] proxy >> POST /v1.38/containers/f43fe061ddf2aebce4e0eaab3194c65ac6564dae553418061a7689795803213a/wait\n
[07:50:02.498][VpnKitBridge      ][Info   ] error dialing remote endpoint docker: connection refused
[07:50:02.498][ApiProxy          ][Info   ] error reading response from Docker:  unexpected EOF
[07:50:02.498][ApiProxy          ][Info   ] Cancel connection...
[07:50:02.498][ApiProxy          ][Warning] ignored error: The handle is invalid.
[07:50:02.499][ApiProxy          ][Info   ] proxy >> POST /v1.38/containers/5f6f47ca992055325c42dfd642179953ecdbd3f8b041b3e20ab753acb5601f35/wait\n
[07:50:02.499][VpnKitBridge      ][Info   ] error dialing remote endpoint docker: connection refused
[07:50:02.499][ApiProxy          ][Info   ] error reading response from Docker:  unexpected EOF
[07:50:02.501][ApiProxy          ][Info   ] proxy >> POST /v1.38/containers/83c72979f4e0d2ca5397d90c9584c1f736b77f063592cd6f8452e2ab7d3c42bf/wait\n
[07:50:02.501][VpnKitBridge      ][Info   ] error dialing remote endpoint docker: connection refused
[07:50:02.501][ApiProxy          ][Info   ] error reading response from Docker:  unexpected EOF
[07:50:02.501][ApiProxy          ][Info   ] Cancel connection...
[07:50:02.501][ApiProxy          ][Warning] ignored error: The handle is invalid.
[07:50:02.503][ApiProxy          ][Info   ] proxy >> POST /v1.38/containers/0f9bc65f3bd8d9ea57af60da5153fa421a4225990987ad3aa3a7d8d490116a23/wait\n
[07:50:02.503][VpnKitBridge      ][Info   ] error dialing remote endpoint docker: connection refused
[07:50:02.503][ApiProxy          ][Info   ] error reading response from Docker:  unexpected EOF
[07:50:02.507][VpnKitBridge      ][Info   ] error dialing remote endpoint docker: connection refused
[07:50:02.507][ApiProxy          ][Info   ] error reading response from Docker:  unexpected EOF
[07:50:02.599][VpnKitBridge      ][Info   ] Proxy wsl2-bootstrap-expose-ports: context is done before proxy is established
[07:50:02.599][VpnKitBridge      ][Info   ] Error: accept: multiplexer is not running
[07:50:02.599][VpnKitBridge      ][Fatal  ] accept: multiplexer is not running
[07:50:02.610][VpnKitBridge      ][Error  ] Process died
[07:50:02.690][ApiProxy          ][Error  ] Error closing raw stream to container: The pipe is being closed.
[07:50:02.690][ApiProxy          ][Error  ] Error closing raw stream to container: The pipe is being closed.
[07:50:02.690][ApiProxy          ][Error  ] Error closing raw stream to container: The pipe is being closed.
```

System info
```
❯ docker info
Client:
 Debug Mode: false

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 200
 Server Version: 19.03.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.76-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 5
 Total Memory: 7.757GiB
 Name: docker-desktop
 ID: 3EKN:AJSM:2AVQ:QOLT:4HUI:VWC2:45GG:3WGB:526P:6B6B:7YAM:MOGU
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 40
  Goroutines: 53
  System Time: 2020-08-31T07:28:07.672102247Z
  EventsListeners: 4
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

```
❯ [System.Environment]::OSVersion.Version

Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      17763  0

❯ Get-ComputerInfo | select WindowsProductName, WindowsVersion, OsHardwareAbstractionLayer

WindowsProductName    WindowsVersion OsHardwareAbstractionLayer
------------------    -------------- --------------------------
Windows 10 Enterprise 1803           10.0.17763.1369
```

**Comment by tijntje** [comment]
Any feedback on this, did you manage to resolve this? We are having the same issue on a production system.

**Comment by vytautas-petrikas** [comment]
@tijntje moved my environment to linux

**Comment by qootec** [comment]
@tijntje: Same here... We stayed with Windows (mandatory in this specific setup), have put Hyper-V active with an Ubuntu 18.04.3 LTS Server in it. This Ubuntu runs Docker and we never saw the problem again.

**Comment by kevindump** [comment]
@qootec :me too....
i run with 2.4.0.0(48506),it still happen again...

**Comment by ievgennaida** [comment]
Same issue on windows. 

```
Unexpected API error for {container_name} (HTTP code 502)
Response body:
Bad response from Docker engine
```
Docker is configured to use 4 GB of RAM.

**Comment by alligator77** [comment]
same issue in windows server 2019
![изображение](https://user-images.githubusercontent.com/6526798/96940311-0daf0f00-14d8-11eb-8fe5-baa0e66b360e.png)

**Comment by igorbljahhin** [comment]
I experienced same issues with Docker Desktop during last months. All issues with Docker Desktop disappeared after migration to new laptop. I still use Windows 10, same version of Docker Desktop, but now it is stable.

**Comment by cecini** [comment]
On wsl2 + win docker desktop. Use the remote-container: clone repposity in container volume and devcontainer config use Dockefile ,when the container build ,lead this error. 
Look at the build process lead the wsl distribution such as ubuntu oom. For wsl2 and win docker, and the remote-container: clone repposity in container volume , the image build is operated in an helper container, and the containter will consum all resource in possible.
As far i know ,the remote-container have no way to set build option(note, not build args) for the container build, so the build will always fail.

As a workaroud, is there any one know how to setting the help containter's run args? if this is can be set,the the final image build should be ok.

Now i just use  remote-container: clone repposity to create an simple image and do some work in the running container, let some preview build work placed in the running container.

**Comment by kevindump** [comment]
i still have problem on 2.5 with windows server 2019...
but i set an other server  run older docker, it  runs good more then 7 DAYS~
i think mayby the problem is on windows server 2019???

**Comment by dwpramik** [comment]
I've also seen similar behavior happening.

Windows Server 2019
Docker Desktop 3.0 (also saw this on 2.5)
Docker Resources: 8 GB Memory - 4 GB Swap

Containers will be up for anywhere from 1 hour - 24 hours, and then they just go down. Any docker commands result in: 
```
docker error response from daemon: open \\.\pupe\docker_engine_linux: the system cannot find the file specified
```
I have to fully restart docker desktop to get it working again.

**Comment by ScottGuymer** [comment]
I can't be 100% sure if it has certainly fixed it but I was advised to re-seat all the memory modules in my laptop. 

I did this and have not seen this issue recently.

**Comment by aeweiwi** [comment]
I am having the same problem also on windows server 2016. Any solution for that ?

**Comment by ievgennaida** [comment]
Problem gone after the migration to the wsl2

**Comment by jankap** [comment]
/remove-lifecycle stale

But problem is still there with WSL 1. No way to update to WSL2 due to Windows Server 2019, 1809. Company rules do not permit any updates.

What can we do?

**Comment by ievgennaida** [comment]
@jankap I guess the only way to register a new one and link this issue.
