### ISSUE TITLE
[WSL 1] Symlinks cause IO error on ntfs drive

### ISSUE THREAD

**Issue by greyphoenix** [docker/for-win#6276]
Short summary of issue
Creating a symlink on ntfs volume, and trying to access it within the container is causing IO error.

Repro steps below  (Using ubuntu 18.04 bash on windows 10)
```
[satya@DESKTOP-DEG2QFE] /mnt/d/test
$ touch abcd

[satya@DESKTOP-DEG2QFE] /mnt/d/test
$ ln -s abcd abcdsym

[satya@DESKTOP-DEG2QFE] /mnt/d/test
$ ls -l
total 0
-rwxrwxrwx 1 satya satya 0 Apr  8 21:18 abcd
lrwxrwxrwx 1 satya satya 4 Apr  8 21:18 abcdsym -> abcd

[satya@DESKTOP-DEG2QFE] /mnt/d/test
$ docker run -v "D:\test:/test" -it ubuntu:18.04 bash
root@5860ce26111f:/# ls /test
ls: cannot read symbolic link '/test/abcdsym': Input/output error
abcd  abcdsym
root@5860ce26111f:/# ls /test -l
**ls: cannot read symbolic link '/test/abcdsym': Input/output error**
total 0
-rwxr-xr-x 1 root root 0 Apr  9 04:18 abcd
lrwxr-xr-x 1 root root 0 Apr  9 04:18 abcdsym

root@583981b44408:/# mount | grep test
grpcfuse on /test type fuse.grpcfuse (rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other,max_read=1048576)
```

More details:
* Windows 10, pro 1903, 18362.720  
* Docker 2.2.0.5
* D: is NTFS volume 
* Using windows wsl1 bash
```
[satya@DESKTOP-DEG2QFE] /mnt/d/apstra
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
Codename:       bionic
```
I noticed issue:  #5582 
I tried it on bleeding edge 2.2.3.0 also.  similarly bad result.. The symlink is not even found.. 
```
[satya@DESKTOP-DEG2QFE] /mnt/d/test
$ docker run -v "D:\test:/test" -it ubuntu:18.04 bash
root@27d08579967d:/# ls -l /test
total 0
-rwxr-xr-x 1 root root 0 Apr  9 04:18 abcd
root@27d08579967d:/#
root@27d08579967d:/# exit

[satya@DESKTOP-DEG2QFE] /mnt/d/test
$ docker --version
Docker version 19.03.6, build 369ce74a3c

```

I am able to consistently reproduce it..

This used to be working with 
Docker Community Edition 18.06.1-ce-win73 2018-08-29

  - [x] I have tried with the latest version of my channel (Stable or Edge)  
    Stable - 2.2.05 & also edge 2.2.3.0
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: CE8D6A22-A19E-433B-9828-E0E67E3339BC/20200409044215

**Comment by greyphoenix** [comment]
any update on this?

**Comment by mat007** [comment]
We’ve fixed some file sharing bugs recently, have you tried with the latest Stable (2.3.0.3)?

**Comment by G-Rath** [comment]
@mat007 I've just upgraded to 2.3.0.5 from 2.1.x.x, and for me docker isn't even showing my symlinks.

I'm using WSLv1, and would love to get this resolved - I also can't remove folders with symlinks, which causes commands like `npm install` to fail at times because it can't remove the `.bin` folder.

I've been stuck on 2.1.x.x due to a number of problems in the new file sharing system that I've been pleased to see get fixed - this looks like the last blocker so am very keen to see it resolved.

(I'm hoping this is causing the problems in #7503 as well).

Let me know if you'd like me to make a new ticket :)

**Comment by G-Rath** [comment]
I've just downgraded to 2.1.0.5, which does result in the symlinks showing up but with the same problem described in the original issue:

![image](https://user-images.githubusercontent.com/3151613/93420690-95b35f00-f903-11ea-872d-26be32e66e9e.png)

So @mat007 I'd say no 2.3.0.3 does not fix this :)

**Comment by stephen-turner** [comment]
Is the WSL 1 only? If so, it's a "Won't Fix". I know some people blogged about how to make WSL 1 work, but we have never supported it, and indeed advised against using it.

**Comment by G-Rath** [comment]
@stephen-turner Yes this is with WSLv1 - I'll admit having it labeled as a "Won't Fix" is a little sad given that this was working enough in 2.1.0.5 to be usable, and that this is the first I've heard of WSLv1 not being supported and advised against.

I know of a number of issues reported here for problems experienced on WSLv1 that were fixed - there was never any mention of it not being supported.

As I've said this is the only blocker I know left for WSLv1 - is there any chance of getting some eyes on it to see if it could be an easy fix? I can't switch to WSLv2 until WSLG ships, which won't be for another year at least.

**Comment by stephen-turner** [comment]
Sorry, I'd love to say yes, but realistically we do not have capacity to look at any WSL 1 bugs.
