### ISSUE TITLE
High CPU usage while Docker Desktop is running on windows

### ISSUE THREAD

**Issue by HenrikPoulsen** [docker/for-win#6947]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: 4FDE0313-882E-40F4-BEAC-95C3BAEDEE00/20200529103928

### Expected behavior
No CPU activity when no containers are running

### Actual behavior
High CPU usage on the Vmmem process while docker desktop is running 
16% constant usage on CPU Intel(R) Core(TM) i9-9980HK CPU, aka 8 core machine
Windows Task manager also reports "Very High" power usage from the process while Docker Desktop is running.

### Information

  - Windows Version: Windows 10 Pro 1909 - build: 18363.836
  - Docker Desktop Version: 2.3.0.3 (45519)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No. Running on non-virtualized Alienware m15 R2 laptop 

### Steps to reproduce the behavior

I have no help to give here. Started after updating to a new version of docker desktop and now won't stop regardless of what I do, other than shutting down docker desktop.
  1. ...
  2. ...

**Comment by mat007** [comment]
Thanks for the report, there is already a couple of people impacted by this in #6564 would you be OK to close this one as a duplicate?

**Comment by HenrikPoulsen** [comment]
If that is the process, then sure go ahead.

**Comment by flavienlaurent** [comment]
@mat007 not sure it's the same issue but it's not the same steps to reproduce. In my case, no wake after sleep is involved.
I restarted my laptop from scratch and vmmem is using 15/20% cpu all the time when the first  container has started.

**Comment by mat007** [comment]
Is this with the WSL 2 backend? If yes maybe it’s https://github.com/microsoft/WSL/issues/4166?

**Comment by mat007** [comment]
> @mat007 not sure it's the same issue

You’re right, that other ticket has Docker Desktop running in a virtualized environment.

**Comment by Pirozek** [comment]
Same problem with this one, vmmem is using like 25% of my CPU without any containers actually running.

Diagnostics ID 92D9DBBE-5255-4969-81BC-398999CD4434/20200609095906 
![image](https://user-images.githubusercontent.com/3284619/84134618-21863700-aa49-11ea-981c-d7df20988cc1.png)

**Comment by dem1tris** [comment]
Same issue.
Vmmem utilizes 15-25% CPU just after Docker starts without any running containers.
com.docker.proxy.exe and Docker Desktop utilizes 2-5% CPU each.

"About" screenshot : https://user-images.githubusercontent.com/22416102/88632764-3e042e80-d0de-11ea-89d6-f4ef8aa5402d.png

**Comment by wiggisser** [comment]
I have Docker Desktop (v2.3.04) installed on my Win10 Pro Machine. I even have the high CPU usage caused by the "DockerDeskop VM" when Docker Desktop is not started at all. Didn't notice this in the past, so it might have started with one of the latest updates.

**Comment by tcpiplab** [comment]
On Windows 10 Pro, downgrading Docker Desktop to v2.3.0.2 solved the problem where the `Vmmem` process was super high and running the laptop fan on maximum speed.

**Comment by wiggisser** [comment]
Anyone had a chance to try this on the new 2.3.0.5 release?

**Comment by yiga2** [comment]
W10Pro here - not using Hyper-VM as I run DockerD in WSL - and 2.3.0.5 still makes Vmmem go off the chart.

**Comment by wiggisser** [comment]
Installed docker desktop 2.4 stable today. Didn't notice any extra CPU usage until now ...

**Comment by Pomax** [comment]
Also noticing 2.4 being surprisingly more cpu intensive compared to before, with vmmem using 40% cpu, and COM Surrogate (which is only active while Docker's running a container) at 25%, so something really weird is going on here because that much cpu for the COM process when nothing's happening in the container is a guaranteed bug.

**Comment by jacol84** [comment]
I have the same problem
![image](https://user-images.githubusercontent.com/11667049/98339074-71bef080-200b-11eb-95e9-7323727680a3.png)
I don't have any container running
![image](https://user-images.githubusercontent.com/11667049/98339376-e5f99400-200b-11eb-883c-bc7433fca451.png)

` 665 root     12:04 /usr/local/bin/dockerd --containerd /var/run/desktop-containerd/containerd.sock --pidfile /run/desktop/docker.pid --config-file /run/config/docker/daemon.json --swarm-default-advertise-addr=eth0`
and 
`   32 root      5:20 /usr/bin/vpnkit-bridge --pid-file=/run/vpnkit-bridge.pid --addr=stdio guest`

my windows version
![image](https://user-images.githubusercontent.com/11667049/98339922-c9aa2700-200c-11eb-9ba4-77a0e64473db.png)
`Microsoft Windows NT 10.0.19042.0`

**Comment by jacol84** [comment]
*FIXED*

**Comment by bradparks** [comment]
I have Docker Desktop running on mac, and it sporadically will make my system crawl. I was originally running a slightly older Docker desktop with the same issue, and upgraded to 2.5, but same issues persists.

![image](https://user-images.githubusercontent.com/185477/107771541-44bc6100-6d11-11eb-8ab6-72067316891b.png)

![image](https://user-images.githubusercontent.com/185477/107771590-5867c780-6d11-11eb-9673-2d5c067a028b.png)

![image](https://user-images.githubusercontent.com/185477/107771674-7af9e080-6d11-11eb-92d9-6627fec7965f.png)

**Comment by Pomax** [comment]
@bradparks this is the `for-win` repository, for the windows-specific build.

**Comment by bradparks** [comment]
whoops ! sorry - I googled and this came up, and I never noticed that it was Windows specific - my bad!

**Comment by acurvers** [comment]
any news on this the issue still persists

**Comment by caot** [comment]
It took the cpu around 25% of Windows 10. Docker is updated.

**Comment by wallyhall** [comment]
Still very much an issue here.  Making my work machine crawl at times, with no containers running.  Quitting Docker Desktop alleviates the issue immediately.
