### ISSUE TITLE
Unable to share drive, complains firewall is blocking

### ISSUE THREAD

**Issue by tcederquist** [docker/for-win#738]
### Expected behavior
Starting a container - mount a drive via -v. 

### Actual behavior
Was working this morning. Upgraded windows to build 1703 and it stopped working, issuing a docker restart and the container would not start with a share failure. Rebuilt the container after uninstalling/reinstalling and when starting - this is the exchange:
docker run --name ermngxatest --dns 172.30.0.2 -d -p 8183:443      -v D:\editor:/usr/share/nginx/html     ermngxa
docker: Error response from daemon: D: drive is not shared. Please share it in Docker for Windows Settings.

Opened the docker window panel and turned off/on sharing for the drive and it says a firewall is blocking the port 445. I turned off the windows firewall (I don't have any other 3rd party firewalls) and it still says firewall blocking. I downgraded docker from edge v17 to production ce v17 and didn't fix the issue, same error message.
Firewall detected
A firewall is blocking file Sharing between Windows and the containers. See documentation for more info.

### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
A diagnostic was uploaded with id: AF795227-392B-4452-A072-A18C1763F27D/2017-05-11_16-12-42
  - host distribution and version (Windows version, build number, etc)
Windows 10 build 1703

### Steps to reproduce the behavior

  1. open the docker config window
  2. pick the share tab
  3. click a drive and click apply
  4. check out the error message

**Comment by jasonterando** [comment]
This happens to me periodically, especially after a suspend.  The workaround I found on this forum is to go into the Network and Sharing Center, and in any NIC go into Properties, Uninstall and Reinstall the "File and Printer Sharing for Microsoft Network" service.  Most of the time, this will get drive sharing going again without having to restart Docker and/or resetting the mount credentials.

**Comment by tcederquist** [comment]
@jasonterando that Fixed it!

Thank you for the quick feedback!

**Comment by manuito** [comment]
I don't think you should close this ticket : to me, it seems to be a real issue :

- The problem was not there 2 months ago. I had no pb to share a drive with Docker on Windows 10 before ...
- If I restore the "File and Printer Sharing for Microsoft Network" service, it's OK until the next reboot or the next Windows Live update
- I don't think that a valid "fix" implies to update some NIC properties manually. It's more a workaround than a fix ...

Regarding the timeline, I think the problem can be related to the "famous" security patch on SMBv1 from March 14th (see [ms17-010](https://technet.microsoft.com/en-us/library/security/ms17-010.aspx) )

Could you please consider to reopen this ticket ?

**Comment by tcederquist** [comment]
A fair comment @manuito and I was 50/50 on leaving open vs closing. I'll reopen and see what happens.

**Comment by friism** [comment]
What Docker for Windows version are you using? Recent releases (eg. 17.05) include a fix that checks for this.

**Comment by elecomte-pro** [comment]
Mmm, I'm in 17.03.1-ce-win12, but when I check for updates, I have a message telling me that my Docker is up to date. Running on Win10 1703 - 15063.296.

The stable docker installer at https://download.docker.com/win/stable/InstallDocker.msi doesn't seems to provide a different version neither.
- Does this fix exists for CE, or on Enterprise Edition only ?
- Maybe v17.05 is on Edge channel only ?

**Comment by manuito** [comment]
Mmm, I'm in 17.03.1-ce-win12, but when I check for updates, I have a message telling me that my Docker is up to date. Running on Win10 1703 - 15063.296.
The stable docker installer at https://download.docker.com/win/stable/InstallDocker.msi doesn't seems to provide a different version neither.

- Does this fix exists for CE, or on Enterprise Edition only ?
- Maybe v17.05 is on Edge channel only ?

**Comment by friism** [comment]
Can you try the edge version? https://docs.docker.com/docker-for-windows/install/

**Comment by manuito** [comment]
Test done with Edge, now running 17.05.0-ce-win11 (12053) = exact same pb => "A firewall is blocking file Sharing between Windows and the containers...". Need to "restart" file sharing in NIC properties after each restart for workaround ... :'(

**Comment by friism** [comment]
Assigning @simonferquel - he'll take a look.

**Comment by jasonterando** [comment]
@manuito - do you, by chance, use a VPN or anything similar that might affect the network configuration on your machine?

**Comment by manuito** [comment]
mmm, yep, I have a VPN client on this machine, you're right I should test without it. I will try from the begining on another win computer and let you know.

**Comment by fcjbispo** [comment]
I`m facing the same issue for a considerable time. I just full reinstall Windows in a new machine and using edge version of Docker and Windows full updated and i only can share drives if switch off and on printer and file share on Docker NAT NIC created by installation. As mentioned, the shares lives only until next reboot.

**Comment by welja** [comment]
I also have this exact issue since 2 weeks ago. After reboot docker loses access to C and then i reapply "File and Printer Sharing for Microsoft Network" to fix it.

Version: 17.03.1-ce-win12 (12058)
OS: Windows 10 Pro
Edition: Professional
Id: 1703
Build: 15063

**Comment by jasonterando** [comment]
So, I don't know if this helps, but I had suspended my Windows 10 computer (fajitas and an IPA were waiting to be consumed).  Docker was running two Linux containers.  After consuming said fajitas and beverage, I resumed the computer.  Mounts were inaccessible.  I uninstalled and reinstalled the File and Printing Sharing service, and mounts worked.  Note:  I did not have to restart Docker, re-share drives, etc.  Just reinstalling the File and Printing service did the trick.  

Diagnostic log:  C7ED5F5F-3273-4BDE-9A44-A018CA0CBD67/2017-05-25_19-41-00

**Comment by hack2root** [comment]
Try Power Shell 3 command under Adminstator access rights as follows:

Set-NetConnectionProfile -interfacealias "vEthernet (DockerNAT)" -NetworkCategory Private

Then enable drive C,D share in Docker settings.

**Comment by Svobi** [comment]
@welja workaround works for me also.

Diagnostic Log: AEBA5F32-8C54-4C62-AE3C-1F1875F0F239/2017-05-29_18-38-47

**Comment by welja** [comment]
@hack2root Thanks for your tip, but sadly it does not fix the situation much. 
After a reboot i have to reapply your command line (or do the "File and Printer Sharing for Microsoft Network" thing ), and the docker sharing thing has to be redone aswell. But i could make it into a little script (when this starts to annoy me more :) )

**Comment by manuito** [comment]
Some improvement over there : With update **17.06.0-rc1-ce-win13 (12433**), now it seems to be OK, even after a reboot. **I do not need anymore to restart NIC properties for file sharing.**

After a look to the release note (https://docs.docker.com/docker-for-windows/release-notes/#docker-community-edition-17060-win13-release-notes-2017-06-01-17060-rc1-ce-win13-edge), there is "_New => Sharing a drive can be done on demand, the first time a mount is requested_". I suppose it provides a new way to request a Windows shared drive from Docker core, which fix our problem here.

As it is fixed on **EDGE** version only (17.06 beta), you may have to wait a while for an update on **STABLE** version (currently in 17.03)

**Comment by galtrold** [comment]
Just want to echo @manuito 
I also had this issue and it went away after upgrading to edge version 17.06.0-rc2-ce-win14 (12510).

**Comment by Rambrant** [comment]
I'm on Version 17.06.0-ce-win17 (12626) and I have the problem...
Set-NetConnectionProfile -interfacealias "vEthernet (DockerNAT)" -NetworkCategory Private fixes it (at least for now)

**Comment by davoutuk** [comment]
Any progress on this subject?

**Comment by elecomte-pro** [comment]
I'm back to the **stable** channel since the 17.06 version is not anymore reserved to **edge** and everything is OK for me. Currently running Version _**stable 17.06.0-ce-win19 (12801)**_, on up-to-date Windows 10 creators update **_(v1703 - 15063.483)_** =>The sharing is still OK even after a reboot. 

For the ones who still have some issues with shared drives : apply all updates (Docker Stable + Windows 10), "restart" file sharing in NIC properties "just to be sure", reboot and that should do the job.

Thanks to Docker team for the fix (and for the great job on Docker !) :-)

**Comment by manuito** [comment]
I'm back to the **stable** channel since the 17.06 version is not anymore reserved to **edge** and everything is OK for me. Currently running Version _**stable 17.06.0-ce-win19 (12801)**_, on up-to-date Windows 10 creators update **_(v1703 - 15063.483)_** =>The sharing is still OK even after a reboot. 

For the ones who still have some issues with shared drives : apply all updates (Docker Stable + Windows 10), "restart" file sharing in NIC properties "just to be sure", reboot and that should do the job.

Thanks to Docker team for the fix (and for the great job on Docker !) :-)

**Comment by arush1204** [comment]
Hi,
I'm facing the same issue. Here are the workarounds I have tried:
1. Unchecked and checked File and Printer Sharing for Microsoft Networks property. Uninstalled and Installed the property.
2. Docker version 17.06.0-ce, Windows 10
3. Set-NetConnectionProfile -InterfaceAlias "vEthernet (DockerNAT)" -NetworkCategory Private

Here are the logs:
[00:06:01.959][SambaShare     ][Error  ] Unable to mount C drive: firewall is blocking
[00:06:01.959][SambaShare     ][Info   ] Removing share C
[00:06:02.044][NamedPipeClient][Info   ] Received response for Mount
[00:06:02.044][NamedPipeServer][Info   ] Mount done in 00:00:03.3763313.

I uploaded the diagnostic:
A diagnostic was uploaded with id: 03D82A06-9616-4815-A02F-7B80AAB4FE78/2017-07-20_00-02-08

PS: This is my work computer, but from similar discussions I have read, issue could be something else.


I'd appreciate your help.

**Comment by davoutuk** [comment]
I've managed to resolve the problem.  The core issue was Norton blocking the firewall.   Once I'd worked out where to make the fix in Norton Security (not easy) then I can now have my Docker volume access a host volume on drive D

**Comment by harrygulliford** [comment]
@davoutuk So how did you fix this in Norton? Having the same issue.

**Comment by davoutuk** [comment]
After talking with Norton,  reset all Norton Firewall settings to the default,  install docker, run docker and the process should be OK.   At some point you will get a prompt to allow Docker to breach firewall.

**Comment by hack2root** [comment]
I'll try today - i found an issue is related to intel vt option in bios,
and windows system applicstion option virtualization technology both
enabled - got the same BSD on NOX app using accelerated mode (bios switch
of intel vt-d, vt), so by unchecking microsoft application virualization
support switch, a was able to run NOX. HOPE FULL REINSTALLING DOCKER STABLE
WILL HELP

19 июл. 2017 г. 9:38 ПП пользователь "davoutuk" <notifications@github.com>
написал:

**Comment by joelharkes** [comment]
Got it here on windows 10 now, reinstalling printer drivers didnt help for me :/

are there other options fixing this without needing to reinstall docker?

**Comment by davoutuk** [comment]
Earlier I wrote that Norton was the blocker, and that I had fixed it,  but that seems to have been a mirage.

Currently I have Docker auto starting on Windows 10 and it crashes with some form of access problem to drive D.   If I subsequently restart Docker then it works OK.

This long running problem should be resolvable if Docker are seriously interested in helping Windows 10 users - I just don't think they are interested.

**Comment by friism** [comment]
We’re very much interested in helping, but there’s not a lot we can do within the confines of the current bind-mount implementation.

In collaboration with Microsoft, we’re rolling out Linux container support powered by Linux Containers on Windows (LCOW). This will transition the host bind-mount implementation to be managed solely by the Windows platform, and we hope it’ll be more stable and reliable. Details here:

 * https://blog.docker.com/2017/11/docker-for-windows-17-11/
 * https://blog.docker.com/2017/09/preview-linux-containers-on-windows/

**Comment by MJTheOne** [comment]
My fix was:
https://github.com/docker/for-win/issues/1395#issuecomment-353933236

Editing Defender for the DockerNET Network

**Comment by kbjerke** [comment]
I am running the Edge version 18.02.0-ce and working on a company computer with Bitdefender Endpoint Security (Enterprise). If I uninstall Bitdefender, I am able to share drives, but as this isn't optional for me. I've tried all the suggestions.

**Comment by steffen-wirth** [comment]
i had a lot of trouble and so many wasted hours with this - it wasn't working with Avast Antivirus Firewall on and i had also trouble with win defender - Port 445 was configured - in the end it was the config of the Docker Nat - after making it a **private** network the message disapeared

**Comment by nomadcreator** [comment]
I have the same issue and need to solve. What I did are (after reading this thread and other sites) :

- Changed Norton firewall setting (allowed port 445) 
- Made Docker private 
- Uninstalled and reinstalled "File and Printer Sharing for Microsoft Network"

My OS is Windows 10 Pro, and tried Docker Edge and Stable.

**Comment by shawnj** [comment]
Same issue as above.  Fix was making DockerNAT network "Private" in Hyper V and restarting docker.

Windows 10 1703
Docker 17.12.0-ce-win47

**Comment by sheridp** [comment]
When I restart Docker, it resets DockerNAT to internal rather than private.  Any idea what's going on?

Docker version 18.03.1-ce, build 9ee9f40  
Hyper-V Manager Version: 10.0.14393.0

**Comment by efunkenbusch** [comment]
In my case, the problem appears to be that our domain policy forces the firewall to be enabled on the Private and Public profiles (disables it for the DomainAuthenticated profile). Even though I have the proper ports enabled on those profiles, it still is blocked. Turning off the Firewall service allows the drives to be mapped, so it's definitely a firewall/security policy issue.

I can reach port 445 on the Docker interface (I've remapped to 192.168.0.1 because our network uses the 10.* network).

I'm running Windows 10 1803, which of course has the issue where you cannot uninstall file and printer sharing. So that workaround is not possible.

![image](https://user-images.githubusercontent.com/36713219/44794728-b23e9c00-ab6e-11e8-8f7a-6fbdc25f9552.png)

**Comment by lasjen** [comment]
Just as a remainder for anyone having this issue. I faced this issue, and looked around for about an hour, trying almost every possible solution described., Finally I realized that I had a VPN Connection up and running. This was blocking! After disconnecting, the sharing went just fine. Now I could reconnect and run my docker container using my shared folder.

**Comment by herbinator** [comment]
same here when i connect to vpn. Then i have to change ip in docker settings Network and after docker restarted it is working again.

**Comment by delucaspinto** [comment]
I use Kaspersky Antivirus, deactivated the firewall for it and it worked for me

**Comment by sanditriana** [comment]
i had simillar issue.
before it. i disabled vEthernet(DockerNAT). and just enabled it. and somehow it work for me :).

can someone explain why its working?
ty

**Comment by tolgabalci** [comment]
@sanditriana, thanks that worked for me!  How bizarre.

**Comment by Glen-Moonpig** [comment]
Over 2 years later and still an issue. If my Windows laptop goes into suspended mode and then wakes the drive sharing no longer works with docker telling me a firewall is blocking it. None of the workarounds listed on this page work for me, I need a full reboot.
I have installed Docker version 18.09.2, build 6247962.

**Comment by stephen-turner** [comment]
This is fixed with the new filesharing implementation in 2.2.0.3, so closing this ticket.
