### ISSUE TITLE
Follow-up to: Docker forces Windows to open a log file on startup (issue with space in path?) #6552

### ISSUE THREAD

**Issue by archon810** [docker/for-win#7941]
Hi,

Since #6552 can no longer be reopened, I'm opening this follow-up. The bug still exists and is still creating the same file with every update.

The most recent update to Docker created `c:\Users\Artem` log file on 7/27/2020.

This was supposed to be fixed, but it never was?

@mat007 For your attention.

**Comment by archon810** [comment]
In case it matters, here's the contents of the file:

```
[13:50:47.375] [InstallHandler] No installation found
[13:50:47.385] [InstallHandler] Using embedded package
[13:50:47.682] [InstallWorkflow] Using package: res:CommunityInstaller.DockerDesktop.d4w
[13:50:47.689] [InstallWorkflow] Downloading
[13:50:49.292] [InstallWorkflow] Extracting manifest
[13:50:50.066] [InstallWorkflow] Checking prerequisites
[13:50:50.471] [InstallWorkflow] Unpacking artifacts
[13:52:03.046] [InstallWorkflow] Deploying component CommunityInstaller.CreateGroupAction
[13:52:16.758] [InstallWorkflow] Deploying component CommunityInstaller.AddToGroupAction
[13:52:30.403] [InstallWorkflow] Deploying component CommunityInstaller.EnableFeaturesAction
[13:52:31.060] [InstallWorkflow-EnableFeaturesAction] Enable Windows Feature VirtualMachinePlatform
[13:52:47.849] [InstallWorkflow] Deploying component CommunityInstaller.ServiceAction
[13:52:47.856] [InstallWorkflow-ServiceAction] Removing service
[13:52:47.861] [InstallWorkflow-ServiceAction] Creating service
[13:52:49.501] [InstallWorkflow] Deploying component CommunityInstaller.ShortcutAction
[13:52:49.520] [InstallWorkflow-ShortcutAction] Creating shortcut: C:\ProgramData\Microsoft\Windows\Start Menu\Docker Desktop.lnk/Docker Desktop
[13:52:49.587] [InstallWorkflow] Deploying component CommunityInstaller.ShortcutAction
[13:52:49.591] [InstallWorkflow-ShortcutAction] Ignore shortcut: C:\Users\Artem Russakovskii\Desktop\Docker Desktop.lnk/Docker Desktop
[13:52:49.595] [InstallWorkflow] Deploying component CommunityInstaller.AutoStartAction
[13:52:49.600] [InstallWorkflow] Deploying component CommunityInstaller.PathAction
[13:52:51.274] [InstallWorkflow] Deploying component CommunityInstaller.PathAction
[13:52:52.835] [InstallWorkflow] Deploying component CommunityInstaller.ExecAction
[13:52:54.112] [InstallWorkflow] Registering product
[13:52:54.975] [InstallWorkflow] Installation succeeded
```

**Comment by stephen-turner** [comment]
Thanks for the report, @archon810, and apologies for the inconvenience. I think this has been fixed on Edge, but we haven't had a full Stable release since then (only a patch release, which has security and other very high priority fixes only). @mat007 Can you confirm? -- I couldn't find the relevant commit.

**Comment by mat007** [comment]
It’s been release in Edge 2.3.1.0 (but apparently it’s missing from the release notes for an unknown reason…).
It hasn’t yet been released to Stable…

**Comment by mat007** [comment]
After double checking it’s supposed to have been fixed in Stable 2.3.0.4, see https://docs.docker.com/docker-for-windows/release-notes/#bug-fixes-and-minor-changes
```
Fixed the path to the installer log file default location when the username contains a space. Fixes docker/for-win#6552
```

Are you still experiencing the issue with that version?

**Comment by archon810** [comment]
I'll have to get back to you after the next update. I'm on that version now, but I don't recall if it had the issue or not.

**Comment by archon810** [comment]
I just installed 2.3.0.5 and this issue persists - the incorrect file was still created.

**Comment by mat007** [comment]
Thanks @archon810 I was able to reproduce it. It’s actually a slightly different bug than the one that was fixed in 2.3.0.4 as it’s in the upgrade code rather than the install from scratch code.

**Comment by djs55** [comment]
The fix for this has been released in [stable 2.4.0.0](https://desktop.docker.com/win/stable/48506/Docker%20Desktop%20Installer.exe).

**Comment by archon810** [comment]
@djs55 Nope. Updated 3 PCs to 2.4.0.0 today, and all 3 created the file again.

**Comment by stephen-turner** [comment]
Another report at #8718

**Comment by stephen-turner** [comment]
Sigh. We've definitely fixed two bugs in this area, but I guess there's another one. We'll have another look. Apologies for the inconvenience.

**Comment by stephen-turner** [comment]
@mat007 Is this because the upgrade process users the previous uninstaller, and will be fixed when upgrading from 2.4.0.0 to the next version? Or is there another bug?

**Comment by mat007** [comment]
> Is this because the upgrade process users the previous uninstaller, and will be fixed when upgrading from 2.4.0.0 to the next version?

Yes, exactly!

Here is how I have just verified that:
- I logged in as a user with a space in the name
- I installed Docker Desktop 2.4.0.0
- I opened regedit and changed the `Version` field in `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Docker Desktop` to a lower value e.g. `48505`
- I started Docker Desktop which prompted me with a new version update window
- I clicked yes to download and install Docker Desktop 2.4.0.0 (on top of itself!)
- I checked that no file had appeared in `C:\Users`

**Comment by stephen-turner** [comment]
@mat007 Sorry, but I'd like to make really sure of this. Could you start with 2.3.0.5, observe that you do get the bug when upgrading to 2.4.0.0, and then observe that you don't get it when upgrading to our latest internal build (2.4.0.1)?

**Comment by mat007** [comment]
>  Could you start with 2.3.0.5, observe that you do get the bug when upgrading to 2.4.0.0, and then observe that you don't get it when upgrading to our latest internal build (2.4.0.1)?

Yes, that’s actually what I did as before the steps I listed above I had installed 2.3.0.5, upgraded to 2.4.0.0, and deleted the file.
After that I upgraded to 2.4.0.0 again which I think proves the point (and is both safer and simpler than using a proxy to divert to an internal build).

**Comment by stephen-turner** [comment]
We really believe this is fixed. 2.5.0.0 is now released, and you should not see the problem when upgrading from 2.4.0.0 to 2.5.0.0. If you do, please post here again. Thank you.

**Comment by archon810** [comment]
Confirmed it's finally fixed with 2.5.0.0.

**Comment by stephen-turner** [comment]
Hooray, thank you!
