### ISSUE TITLE
WSL 2 on windows 10 1909

### ISSUE THREAD

**Issue by scrhall** [docker/for-win#8169]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: BBA9AF24-320A-4A7D-BEDE-50AB426AA0E8/20200821094159

### Expected behavior
enable wsl2 checkbox
### Actual behavior
disable wsl2 checkbox
### Information

  - Windows Version: 1909  18363.1049
  - Docker Desktop Version: 2.3.0.4 (46911)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: no

**Comment by stephen-turner** [comment]
It sounds like this issue is fixed now, so I'll close it.

**Comment by thexpand** [comment]
@stephen-turner When will this be expected to land on the Stable channel as well?

**Comment by stephen-turner** [comment]
Most likely at the end of September, although that's not definite yet.

**Comment by FortinFred** [comment]
Hi,

Just installed the Edge version with WSL2 on WIndows 1909 and I still can't enable WSL2 within Docker.

Note that I'm in a corporate setup so maybe something is in the way.

**Comment by tj-incycle** [comment]
@FortinFred make sure you have the [Windows Update KB4566116](https://support.microsoft.com/en-us/help/4566116/windows-10-update-kb4566116) installed on your machine. Without it, you won't be able to enable it. There is a good chance your corporate IT hasn't deployed it yet.
