### ISSUE TITLE
compinit:501: no such file or directory: /usr/share/zsh/vendor-completions/_docker

### ISSUE THREAD

**Issue by MaurGi** [docker/for-win#8336]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

No issues with zsh completions and compinit when starting a new shell

### Actual behavior

I installed Docker for Windows 2.3.0.4 on Windows 10 Version 2004 (build 19041.450) and enabled WSL integration. 
Then I turned off Docker for Windows because of resource consumptions.
Now I get this error every time I start my zsh shell:

```
compinit:501: no such file or directory: /usr/share/zsh/vendor-completions/_docker
```

I noticed that the file `/usr/share/zsh/vendor-completions/_docker` is a link to a wsl mount:

```
$ ls -l /usr/share/zsh/vendor-completions/_docker
lrwxrwxrwx 1 root root 74 Sep  3 11:17 /usr/share/zsh/vendor-completions/_docker -> /mnt/wsl/docker-desktop/cli-tools/usr/share/zsh/vendor-completions/_docker
```

so I assume this file is present only when Docker for Windows is running, but I need to turn it off or my machine won't make it.

my `~/.zshrc` file is:
```
plugins=(git docker zsh-completions)

source $ZSH/oh-my-zsh.sh

# zsh-completions
autoload -U compinit && compinit

```

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. Configure oh-my-zsh plugins, add docker
  2. Install Docker For Windows
  3. Turn off Docker for Windows
  4. Open a shell

**Comment by hostmit** [comment]
Any solution to this?

**Comment by stephen-turner** [comment]
@simonferquel Have you seen this before?

**Comment by hostmit** [comment]
I confirm this happens only with docker on windows turned off.

**Comment by simonferquel** [comment]
Yes, this is because completion scripts are symlinks to files in the cli-tools iso file. This iso file is mounted by Docker Desktop on startup. We could probably explore ways to remove the symlinks on a clean shutdown.

**Comment by khashashin** [comment]
On removing Docker the symlinks still appear (On Windows 10, WSL2)

**Comment by stephen-turner** [comment]
FYI This issue is in progress in our current sprint.

**Comment by stephen-turner** [comment]
Reopening this ticket. It's fixed internally, but not yet released.

**Comment by tik9** [comment]
Hi Stephen, when will be the release? Thanks.

**Comment by stephen-turner** [comment]
Provisionally scheduled for 2 Nov.

**Comment by brunosaboia** [comment]
This happens if you had WSL2 integration enabled (by checking `Resources → WSL Integration → Enable integration with my default WSL distro`) and then change your "default distro" back to WSL1 with `wsl --set-version linux-distro 1`.

Perhaps it is a good idea to make sure that the OP is running with the right settings. Pasting the result of `wsl --list --verbose` would help in such direction.

**Comment by LavHinsu** [comment]
any updates on this?

**Comment by stephen-turner** [comment]
@LavHinsu Yes, look two comments above yours.

**Comment by tik9** [comment]
@brunosaboia in order to be safe, I checked it with wsl -l -v and got 2.

**Comment by pavanjadhaw** [comment]
I was facing same issue,
heres what I did

First I removed the symlink 
```
sudo rm -rf /usr/share/zsh/vendor-completions/_docker
```

then I copied over the wsl completions

```
sudo cp /mnt/wsl/docker-desktop/cli-tools/usr/share/zsh/vendor-completions/_docker /usr/share/zsh/vendor-completions/
```

and made it non-writable 

```
sudo chattr +i /usr/share/zsh/vendor-completions/_docker
```

now next time we launch wsl when docker is not running we wont get that error

**Comment by tianheg** [comment]
the same problem, when I add `docker` in zsh plugins it's sloved:

```bash
plugins=(
docker
zsh-syntax-highlighting
zsh-autosuggestions
)
```

- Windows Version: 2004 (OS build 19041.572)
- Docker Desktop Version: 2.4.0.0(48506) [Channel stable]
- WSL2: Ubuntu-20.04

**Comment by huri3l** [comment]
I still face this issue, any updates?

**Comment by stephen-turner** [comment]
This was fixed in 2.5.0.0.

**Comment by G-Rath** [comment]
@stephen-turner do you know if this is related to #6276 at all? or otherwise if there's any way to get that problem looked at?

I've been stuck on 2.1.x.x for about a year now due to various bugs in the new volume sharing system, and this looks like the last main one left.

I've not tested 2.5.x.x myself, because everytime I change docker versions I lose all my containers which is a hassle (+ docker is critical for work, which is why I have to play it safe).

Happy to create a new issue, provide more info, etc to help get this fixed :)

**Comment by ianmartorell** [comment]
> This was fixed in 2.5.0.0.

I'm on version 3.0.0 (50684) and getting this error when starting a WSL 2 instance with Docker for Windows not running. Is there something else that needs to be done manually?

**Comment by 3ric-T** [comment]
> This was fixed in 2.5.0.0.

Same as @ianmartorell I'm on last version, 3.0.0 (50684) and the error still occurs when starting WSL2 instance without a running Docker for Windows instance.
Can you provide some manual proceudre which can prevent this?

**Comment by bodzio4749** [comment]
> > This was fixed in 2.5.0.0.
> 
> Same as @ianmartorell I'm on last version, 3.0.0 (50684) and the error still occurs when starting WSL2 instance without a running Docker for Windows instance.
> Can you provide some manual proceudre which can prevent this?

Starting the Docker Desktop fixed it for me.  I suppose adding logic to .zshrc script to test the docker presence prior to loading the theme proposed above: by @pavanjadhaw would be a good fix. Or, maybe replacing the error message with a notification "Docker Desktop not running"

**Comment by 3ric-T** [comment]
@bodzio4749 @pavanjadhaw The workaround works for me, thanks a lot
I'll have to remember to do this at every Docker Desktop upgrade

**Comment by michaelbehan** [comment]
I'm using macOS Catalina and I get this, even with docker in my zsh plugins.  This is with Docker Desktop running or not.

**Comment by shubhamjain839** [comment]
I face the same issue in WSL2 Ubuntu-20.04 
-added docker plugin but didn't fix it

**Comment by 3ric-T** [comment]
@shubhamjain839 In fact, the workaround described by @pavanjadhaw is working fir me on WSL2 Ubuntu-20.04

**Comment by shubhamjain839** [comment]
> @shubhamjain839 In fact, the workaround described by @pavanjadhaw is working fir me on WSL2 Ubuntu-20.04

Thanks, appreciated

**Comment by shubhamjain839** [comment]
> @shubhamjain839 In fact, the workaround described by @pavanjadhaw is working fir me on WSL2 Ubuntu-20.04

Thanks, appreciated

**Comment by dancingmonkey** [comment]
If you don't want this message to pop up on windows and you have deleted the docker program and still using the windows terminal with wsl than delete the folders `docker` and `docker-desktop` or anything that starts with docker in `C:\Users\<Username>\AppData\Roaming`

This worked for me :)
