### ISSUE TITLE
Containers and images not updating (refreshing)

### ISSUE THREAD

**Issue by Flightkick** [docker/for-win#9401]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
I expect the UI to be responsive and display the current state of my docker containers & images.

### Actual behavior
The list of containers and the list of images are populated on startup but their contents are not updated during runtime. For example: whenever I run a new container through a `docker run` command with Powershell I have to restart the Docker Desktop application to see the actual state.

### Information

  - Windows Version: Windows 10 Pro 19041
  - Docker Desktop Version: 2.5.0.17
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. Make sure there's a local docker image
  2. Check the 'Containers / Apps' tab
  3. Run a new container for the image in step 1 through powershell
  4. Check the 'Containers / Apps' tab - You should notice the container is not listed
  5. Restart Docker Desktop and check the tab again - You should notice the container is now listed properly.

**Comment by Eagleleader** [comment]
Have same issue since months on Windows 10 and 11 with current latest version of Docker.
Anyone has a workaround instead of restarting the Docker application ?

**Comment by johnpankowicz** [comment]
I just encountered this problem today. Up to now it always worked fine. A half-hour ago, I stopped and re-started WSL to try and fix an issue with responsiveness. I did a:
    "wsl --shutdown"
    Edited my .wlsconfig file to limit memory & processes
    Restarted the docker daemon by choosing "restart" under "Troubleshoot" in Docker Desktop
Now I can create new images on the command line, but none show up in the Docker Desktop UI.

**Comment by christopher-f-clark** [comment]
[](https://stackoverflow.com/posts/70729131/timeline)1


I have a running docker desktop (on MacOS if that matters). And I have used the command line (in a terminal) to create some containers. Ones that I created before running docker desktop show up in the "containers/apps" list, but more recent ones don't. How do I "refresh" the list of containers to show these new ones. I don't want to stop/start the actual running containers. I just want a current list of them in the desktop app.

**Comment by alwaysthecritic** [comment]
Still broken (Docker Desktop Mac here). I was hoping to find a "vote on issue" button, so this comment will have to do.

**Comment by Eagleleader** [comment]
One workaround for me : docker system prune : then it refreshes all info into the Desktop Client. 
But it is only a workaround.

**Comment by hotrungnhan** [comment]
can it be easily fix by a manual refresh button on every page ?

**Comment by paddelboot** [comment]
+1 

The list of images in the `images > local` tab does not correspond to the list of images I get from `docker images`.

**Comment by stephanierifai** [comment]
Thanks for the feedback we're currently investigating this 🕵️‍♀️ !

**Comment by mpetruc** [comment]
any updates with this situation? i'm experiencing something similar to @paddelboot: no images in Images on disc ->Local but "docker images" shows all my images. It appears that Containers/Apps and Volumes are unaffected (i.e. i can see containers and volumes in the desktop client). I'm also on Windows 11 with WSL2.

**Comment by nsmith22** [comment]
I am seeing this also with the latest Docker Desktop for Mac, version "4.11.0 (83626)". However, I have always observed that behavior with Docker Desktop for at least a year across various versions. So, this may be an old bug, but it definitely would be nice to see it fixed.

**Comment by andrei-z-albu** [comment]
Closing this issue as a fix has been pushed with the new release of Docker Desktop 4.12.0. See [release notes](https://docs.docker.com/desktop/release-notes/) for more details.

**Comment by lizzthabet** [comment]
docker desktop 4.12.0 makes a couple improvements to how the image list is fetched to address [#12693](https://github.com/docker/for-win/issues/12693) and [#6347](https://github.com/docker/for-mac/issues/6347), as well as reducing the number of times it's calculating disk usage. these changes should improve the accuracy of the ui. if you try 4.12.0+ and you're still seeing accuracy / latency issues, please let us know!

**Comment by JoeyK4816** [comment]
Hi, I am a very new docker desktop user, but I am having this same trouble on a brand new install for a brand new user. 

In the Images list, after building a new image from my own dockerfile using powershell, the UI does not show my new image. Clicking the refresh button doesn't seem to do anything. I then go to the system tray and right click-> exit docker desktop. When i restart the application, my recently created image appears in the list.

This trouble is reflected in other ways as well. When deleting an image or rebuilding it from powershell the changes aren't shown in the UI. In one instance after deleting an image in the UI of Docker Desktop, I went to build the image again in powershell only to discover the docker desktop hadn't actually deleted the image in the first place.

The previously mentioned command `docker system prune` does correct the information in the Images UI.

Note: I'm a windows 10 user on Docker Desktop v 4.12.0

**Comment by dhanuka0827** [comment]
I am very new to docker and I am facing a similar issue on Windows 11 with Docker Desktop 4.12.0. Image is not getting updated.
